### ISSUE TITLE
Error: UpstreamBridge - encountered exception

### ISSUE THREAD

**Issue by GEJMRovec** [SpigotMC/BungeeCord#1368]
Hello,
I keep getting this error every few seconds. Can you tell me what is wrong please?
Help is much appreciated. Thanks.

15:36:53 [INFO] [dreyar_] <-> InitialHandler has connected
15:36:53 [INFO] [patrik150350] -> UpstreamBridge has disconnected
15:36:53 [INFO] [dreyar_] <-> ServerConnector [Auth1] has connected
15:36:53 [INFO] [LadyCynic] <-> InitialHandler has connected
15:36:53 [INFO] [LadyCynic] <-> ServerConnector [Auth1] has connected
15:36:53 [SEVERE] [dreyar_] -> UpstreamBridge - encountered exception
java.lang.NullPointerException
	at net.md_5.bungee.connection.UpstreamBridge.handle(UpstreamBridge.java:114)
	at net.md_5.bungee.protocol.packet.Chat.handle(Chat.java:50)
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:75)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:745)
15:36:53 [INFO] [dreyar_] disconnected with: §fNullPointerException : null @ net.md_5.bungee.connection.UpstreamBridge:114
15:36:53 [INFO] [dreyar_] -> UpstreamBridge has disconnected
15:36:53 [SEVERE] [LadyCynic] -> UpstreamBridge - encountered exception
java.lang.NullPointerException
	at net.md_5.bungee.connection.UpstreamBridge.handle(UpstreamBridge.java:114)
	at net.md_5.bungee.protocol.packet.Chat.handle(Chat.java:50)
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:75)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:745)
15:36:53 [INFO] [LadyCynic] disconnected with: §fNullPointerException : null @ net.md_5.bungee.connection.UpstreamBridge:114
15:36:53 [INFO] [LadyCynic] -> UpstreamBridge has disconnected

**Comment by Janmm14** [comment]
Some information: Error occurres in this line:
https://github.com/SpigotMC/BungeeCord/blob/master/proxy/src/main/java/net/md_5/bungee/connection/UpstreamBridge.java#L114

variable con can't be null becasue it's accessed before, result of unsafe() can't be null.

So I think con.getServer() returns null.

**Comment by TheDoctorsLife** [comment]
I get the same error upon player join http://hastebin.com/umorerawun.avrasm

**Comment by md-5** [comment]
@TheDoctorsLife No, this is nothing to do with your error. You just have a tonne of broken plugins.

**Comment by TheDoctorsLife** [comment]
yep, thanks for clearing that up

**Comment by TheDoctorsLife** [comment]
ok, so that kinda fixed it, still getting this error http://hastebin.com/womagujoya.coffee but I can join now

**Comment by dentmaged** [comment]
Update BungeeCord
