### ISSUE TITLE
Big Big Error

### ISSUE THREAD

**Issue by SaroxDE** [SpigotMC/BungeeCord#1373]
http://www.mediafire.com/download/gl5gtw8hoo4449g/proxy.log.0

**Comment by Rocknest** [comment]
http://hastebin.com

**Comment by hibo98** [comment]
Same Problem #1372

**Comment by johnnywoof** [comment]
Same Issue.
`Caused by: java.lang.IllegalArgumentException: Cannot get ID for packet class net.md_5.bungee.protocol.packet.Kick
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
    at net.md_5.bungee.protocol.Protocol$DirectionData.getId(Protocol.java:170)
    at net.md_5.bungee.protocol.MinecraftEncoder.encode(MinecraftEncoder.java:23)
    at net.md_5.bungee.protocol.MinecraftEncoder.encode(MinecraftEncoder.java:9)
    at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
    ... 35 more
`

**Comment by md-5** [comment]
Duplicate
