### ISSUE TITLE
1.7.10 compatibility w/ Java 7 update 51

### ISSUE THREAD

**Issue by gabiwabi123** [SpigotMC/BungeeCord#1375]
Hi there when I start bungee cord w/ Java Update 51 I get Last login: Sun Feb 15 16:16:58 on ttys000
Gabis:~ gabi$ /Users/gabi/Desktop/Hub\ MC/tester.command ; exit;
Exception in thread "main" java.lang.UnsupportedClassVersionError: net/md_5/bungee/api/ProxyServer : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
logout

[Process completed]

I am trying to get it to work w/ my minecraft server which is a 1.7.9/10 server. I want to make a hub for my server and one other server. Please make a compatible version. Thanks a lot

**Comment by gabiwabi123** [comment]
I'm also on a apple computer but the terminal lines I pasted should say it.

**Comment by i9hdkill** [comment]
Are you sure that Java 6 is disabled?

**Comment by gabiwabi123** [comment]
It seems like it won't run because its trying to use the newer version and I read online that the way to fix it would be to force the JRE script (bungeecord) to work with the right version of java. So I want it to be able to run 2 versions of java at once the new one for everything else and the older version for bungeecord. Also its not java 6 i need its a older version of 7

**Comment by i9hdkill** [comment]
You need Java 7 or Java 8 for BungeeCord.
Osx uses Java 6 by default. You need a startup script that tells BungeeCord to start up with Java 7.

**Comment by gabiwabi123** [comment]
Could you link me to one please? :/ ;)

**Comment by gabiwabi123** [comment]
btw thanks for replying first time using github
