### ISSUE TITLE
Crashes Randomly?

### ISSUE THREAD

**Issue by OzOwnz** [SpigotMC/BungeeCord#1385]
```
01:48:13 [SEVERE] Exception in thread "main" 
01:48:13 [SEVERE] java.io.IOException: Input/output error
01:48:13 [SEVERE] 	at java.io.FileInputStream.read0(Native Method)
01:48:13 [SEVERE] 	at java.io.FileInputStream.read(FileInputStream.java:210)
01:48:13 [SEVERE] 	at jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:169)
01:48:13 [SEVERE] 	at jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:137)
01:48:13 [SEVERE] 	at jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:246)
01:48:13 [SEVERE] 	at jline.internal.InputStreamReader.read(InputStreamReader.java:261)
01:48:13 [SEVERE] 	at jline.internal.InputStreamReader.read(InputStreamReader.java:198)
01:48:13 [SEVERE] 	at jline.console.ConsoleReader.readCharacter(ConsoleReader.java:2145)
01:48:13 [SEVERE] 	at jline.console.ConsoleReader.readLine(ConsoleReader.java:2349)
01:48:13 [SEVERE] 	at jline.console.ConsoleReader.readLine(ConsoleReader.java:2269)
01:48:13 [SEVERE] 	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:54)
01:48:13 [SEVERE] 	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
```

**Comment by ninja-** [comment]
that looks like a problem with your wrapper

**Comment by OzOwnz** [comment]
@ninja- Using Linux screens and simply running the java argument. You think using screens is the problem?
