### ISSUE TITLE
java.util.NoSuchElementException: packet-encoder

### ISSUE THREAD

**Issue by mibby** [SpigotMC/BungeeCord#1386]
BungeeCord dev 1052.
Spigot git-Spigot-c3c767f-33d5de3

This error spams once in a while and disconnects all players from the instance. 
From the BungeeCord log.
http://paste.ubuntu.com/10532475/
```
[SEVERE] [mibby] <-> ServerConnector [Survival] - encountered exception
java.util.NoSuchElementException: packet-encoder
	at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:907)
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:157)
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:150)
	at net.md_5.bungee.netty.ChannelWrapper.addBefore(ChannelWrapper.java:69)
	at net.md_5.bungee.netty.ChannelWrapper.setCompressionThreshold(ChannelWrapper.java:81)
	at net.md_5.bungee.UserConnection.setCompressionThreshold(UserConnection.java:591)
	at net.md_5.bungee.ServerConnector.handle(ServerConnector.java:146)
	at net.md_5.bungee.protocol.packet.SetCompression.handle(SetCompression.java:36)
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:75)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:161)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:161)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:745)
[INFO] [mibby] disconnected with: §fException Connecting:NoSuchElementException : packet-encoder @ io.netty.channel.DefaultChannelPipeline:907
```

Those who are not disconnected with this error occurring in the console are instead disconnected with this message;
From the BungeeCord log.
```
disconnected with: §fException Connecting:ReadTimeoutException : null
```

From the Spigot log.
http://paste.ubuntu.com/10532463/
```
lost connection: Internal Exception: io.netty.handler.timeout.ReadTimeoutException
lost connection: Internal Exception: java.io.IOException: Broken pipe
lost connection: Internal Exception: java.io.IOException: Connection reset by peer
```

**Comment by md-5** [comment]
#1386

**Comment by mibby** [comment]
@md-5 You linked to this ticket and closed it? I'm a bit confused.

**Comment by md-5** [comment]
#1366 my bad
