### ISSUE TITLE
Shutting off BungeeCord when ServerInfo#ping is processing inside a scheduled task

### ISSUE THREAD

**Issue by Brian-Graham** [SpigotMC/BungeeCord#1403]
When you are calling the asynchronous method ServerInfo#ping inside a BungeeTask/Runnable through the ProxyServer#getScheduler() and you shut off the Proxy, it will hang until it can forcibly crash.

Here is one of my plugins that can reproduce the problem:
Source Code: https://bitbucket.org/Brian-Graham/niftybungee/src/51b0e1e75fa601b537935e19d657416c68567a6e/src/net/netcoding/niftybungee/minecraft/BungeeHelper.java?at=master#cl-127

You'll see all I do is load a task, process it and call it again after 400 milliseconds. The task itself works fine, but the testThis.ping will throw the following error is you shut down the proxy:

```
14:26:12 [SEVERE] Mar 16, 2015 2:26:12 PM io.netty.channel.AbstractChannel$AbstractUnsafe register
WARNING: Force-closing a channel whose registration task was not accepted by an event loop: [id: 0x88e53eb6]
java.util.concurrent.RejectedExecutionException: event executor terminated
    at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:745)
    at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:322)
    at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:728)
    at io.netty.channel.AbstractChannel$AbstractUnsafe.register(AbstractChannel.java:418)
    at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:60)
    at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:48)
    at io.netty.channel.MultithreadEventLoopGroup.register(MultithreadEventLoopGroup.java:64)
    at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:317)
    at io.netty.bootstrap.Bootstrap.doConnect(Bootstrap.java:133)
    at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:89)
    at net.md_5.bungee.BungeeServerInfo.ping(BungeeServerInfo.java:143)
    at net.md_5.bungee.BungeeServerInfo.ping(BungeeServerInfo.java:122)
    at net.netcoding.niftybungee.minecraft.BungeeHelper$NotifyServers.run(BungeeHelper.java:127)
    at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)


14:26:12 [SEVERE] Mar 16, 2015 2:26:12 PM io.netty.util.concurrent.DefaultPromise execute
SEVERE: Failed to submit a listener notification task. Event loop shut down?
java.util.concurrent.RejectedExecutionException: event executor terminated
    at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:745)
    at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:322)
    at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:728)
    at io.netty.util.concurrent.DefaultPromise.execute(DefaultPromise.java:671)
    at io.netty.util.concurrent.DefaultPromise.notifyLateListener(DefaultPromise.java:641)
    at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:138)
    at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:93)
    at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:28)
    at net.md_5.bungee.BungeeServerInfo.ping(BungeeServerInfo.java:143)
    at net.md_5.bungee.BungeeServerInfo.ping(BungeeServerInfo.java:122)
    at net.netcoding.niftybungee.minecraft.BungeeHelper$NotifyServers.run(BungeeHelper.java:127)
    at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by minecrafter** [comment]
My plugin [HubMagic](https://github.com/minecrafter/HubMagic) also experiences this issue. Someone seems to have taken my advice:

https://minecraft.minimum.io/wiki/HubMagic/FAQ#I_get_exceptions_when_I_close_my_proxy._Please_help.21

**Comment by md-5** [comment]
@minecrafter I'm not sure how your solution is better. With your proposed resolution plugins will miss any events occurring between them disabling and connections being closed.
