### ISSUE TITLE
Protocol HANDSHAKE ERROR LAG

### ISSUE THREAD

**Issue by MaTyyyx** [SpigotMC/BungeeCord#1424]
Hi, i have this error log, and this lagging my bungee server.
21:44:54 [SEVERE] [/118.69.174.30:62601] <-> InitialHandler - encountered exception
io.netty.handler.codec.DecoderException: net.md_5.bungee.protocol.BadPacketException: Did not read all bytes from packet class net.md_5.bungee.protocol.packet.Handshake 0 Protocol HANDSHAKE Direction net.md_5.bungee.protocol.Protocol$DirectionData@2fd3be3f
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:280)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:745)
Caused by: net.md_5.bungee.protocol.BadPacketException: Did not read all bytes from packet class net.md_5.bungee.protocol.packet.Handshake 0 Protocol HANDSHAKE Direction net.md_5.bungee.protocol.Protocol$DirectionData@2fd3be3f
	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:35)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249)
	... 17 more

**Comment by kamcio96** [comment]
client version? forge?

**Comment by MaTyyyx** [comment]
I don't know, i get this randomly. I have clean spigot 1649 without mods - no forge on server.

**Comment by kamcio96** [comment]
propably it is client bug or somebody edit client, it sends wrong packet length

**Comment by MaTyyyx** [comment]
yea, i know, somebody sends wrong packet to lag my server, but how repair it?

**Comment by kamcio96** [comment]
it doesn't make lag, it is handshake packet (before any events) so it only makes spam

 TODO disable spam?

**Comment by ninja-** [comment]
@Matyyyx looks like we have been hit by the same attacker with a custom tool - I investigated the problem and the fix will be commited soon, a bug allowed to eat bungee's memory until it crashes - also you can notice how the IPs are always proxys coming from China, Russia etc.

**Comment by md-5** [comment]
Not a bug

**Comment by ninja-** [comment]
just another feature

**Comment by ninja-** [comment]
@md-5 your comment deleting is childish. back to the problem, atm 3 servers had been knocked off by a tool that leaves the mentioned stacktrace
