### ISSUE TITLE
Crash...

### ISSUE THREAD

**Issue by kukubaczek** [SpigotMC/BungeeCord#1430]
Error, and sudennly kick all players from servers

```
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
    at java.lang.Thread.run(Thread.java:745)
Caused by: net.md_5.bungee.protocol.BadPacketException: Did not read all bytes from packet class net.md_5.bungee.protocol.packet.Handshake 0 Protocol HANDSHAKE Direction net.md_5.bungee.protocol.Protocol$DirectionData@55022627
    at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:37)
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:247)
    ... 17 more
20:47:20 [SEVERE] [/77.247.181.162:45136] <-> InitialHandler - encountered exception
io.netty.handler.codec.DecoderException: net.md_5.bungee.protocol.BadPacketException: Did not read all bytes from packet class net.md_5.bungee.protocol.packet.Handshake 0 Protocol HANDSHAKE Direction net.md_5.bungee.protocol.Protocol$DirectionData@55022627
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:278)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:147)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:161)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
    at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
    at java.lang.Thread.run(Thread.java:745)
Caused by: net.md_5.bungee.protocol.BadPacketException: Did not read all bytes from packet class net.md_5.bungee.protocol.packet.Handshake 0 Protocol HANDSHAKE Direction net.md_5.bungee.protocol.Protocol$DirectionData@55022627
    at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:37)
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:247)
    ... 17 more
```

[20:47:01 INFO]: Lampard_Pro lost connection: Disconnected
[20:47:34 INFO]: MrGrzes lost connection: Disconnected
[20:47:37 INFO]: Zbucki lost connection: Timed out
[20:47:38 INFO]: mega_gaming lost connection: Timed out
[20:47:38 INFO]: ppo11 lost connection: Timed out
[20:47:44 INFO]: angry9999 lost connection: Timed out
[20:47:44 INFO]: huberthubi lost connection: Timed out
[20:47:56 INFO]: bloczek lost connection: Timed out

**Comment by xnerdian** [comment]
acha

**Comment by kamcio96** [comment]
hahahahahhahahhahahahahahhahahhahahha :D
Pozdrawiam xD

**Comment by kukubaczek** [comment]
Czyli jak to naprawić? :[

**Comment by defabricated** [comment]
Memory leak...

Ktoś ładnie napierdala cię pakietami, które mają więcej bitów niż powinny mieć, Bungee nie ma pamięci to się wykrzacza.

Dopóki to nie zostanie poprawione możesz spróbować poblokować sobie inne kraje na iptables, będzie działać dopóki ktoś nie zacznie wysyłać tych pakietów z polskiego IP.

**Comment by kamcio96** [comment]
iptables nic nie daje
to też nie dosy

kuku komu nie zapłaciłeś? xD

**Comment by mcwnuq** [comment]
iptables to pomoc doraźna, blokowanie całego ruchu z poza Polski nie ma sensu a blokowanie kolejnych źródeł to robota bardziej mozolna niż robienie na drutach (albo robienie druta jak kto woli ^^)
@kukubaczek kto mieczem wojuje od miecza ginie ;]

**Comment by md-5** [comment]
Update Bungee

**Comment by mcwnuq** [comment]
@md-5 you mean update it to the #1058 build? In this build this crash was repaird?

**Comment by md-5** [comment]
Update to latest bungee

**Comment by kukubaczek** [comment]
Ja akurat nigdzie nie wojowalem :x

**Comment by kamcio96** [comment]
Taaa... :D

**Comment by magacraft99** [comment]
i have the same bug with bungeecord 1061

**Comment by magacraft99** [comment]
[INFOS] Enabled plugin cmd_alert version git:cmd_alert:1.8-SNAPSHOT:"88e71ea":1061 by SpigotMC
17:17:43 [INFOS] Enabled plugin cmd_send version git:cmd_send:1.8-SNAPSHOT:"88e71ea":1061 by SpigotMC
17:17:43 [INFOS] Enabled plugin cmd_list version git:cmd_list:1.8-SNAPSHOT:"88e71ea":1061 by SpigotMC
17:17:43 [INFOS] Listening on /0.0.0.0:25565
17:18:05 [INFOS] [/127.0.0.1:52599] <-> InitialHandler has connected
17:18:08 [INFOS] [/127.0.0.1:52611] <-> InitialHandler has connected
17:18:08 [GRAVE] [magacraft99] <-> InitialHandler - encountered exception
java.lang.ExceptionInInitializerError
	at javax.crypto.Cipher.getInstance(Cipher.java:510)
	at net.md_5.bungee.EncryptionUtil.getSecret(EncryptionUtil.java:58)
	at net.md_5.bungee.connection.InitialHandler.handle(InitialHandler.java:370)
	at net.md_5.bungee.protocol.packet.EncryptionResponse.handle(EncryptionResponse.java:53)
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:75)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:161)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:161)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.SecurityException: Can not initialize cryptographic mechanism
	at javax.crypto.JceSecurity.<clinit>(JceSecurity.java:89)
	... 24 more
Caused by: java.lang.SecurityException: Cannot locate policy or framework files!
	at javax.crypto.JceSecurity.setupJurisdictionPolicies(JceSecurity.java:254)
	at javax.crypto.JceSecurity.access$000(JceSecurity.java:48)
	at javax.crypto.JceSecurity$1.run(JceSecurity.java:81)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.crypto.JceSecurity.<clinit>(JceSecurity.java:78)
	... 24 more
