### ISSUE TITLE
Lag and crash!

### ISSUE THREAD

**Issue by kukubaczek** [SpigotMC/BungeeCord#1433]
Error:
17:25:08 [SEVERE] [/96.44.189.102:2716] <-> InitialHandler - encountered exception
io.netty.handler.codec.DecoderException: net.md_5.bungee.protocol.BadPacketException: Did not read all bytes from packet class net.md_5.bungee.protocol.packet.Handshake 0 Protocol HANDSHAKE Direction net.md_5.bungee.protocol.Protocol$DirectionData@69a36792
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:278)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:147)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:161)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
    at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
    at java.lang.Thread.run(Thread.java:745)
Caused by: net.md_5.bungee.protocol.BadPacketException: Did not read all bytes from packet class net.md_5.bungee.protocol.packet.Handshake 0 Protocol HANDSHAKE Direction net.md_5.bungee.protocol.Protocol$DirectionData@69a36792
    at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:37)
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:247)
    ... 17 mo

**Comment by kamcio96** [comment]
Lepiej przyznaj się komu nie zapłaciłeś :P

**Comment by kukubaczek** [comment]
Eee Tobie? Za co miałem Ci niby płacić? xd

**Comment by kamcio96** [comment]
Nieeeeeee xD ja w takie gówna się na bawie

**Comment by kukubaczek** [comment]
To podejrzewasz kogoś? :< Bo ja sobie nie przypominam, żebym komuś nie zapłacił... Jednemu youtuberowi nie zapłaciłem bo jutro to zrobie xd

**Comment by kamcio96** [comment]
podejrzewam kogoś kto znalazł ten bug :p

**Comment by kukubaczek** [comment]
Tyle to wiem... Ale z open souruce to szybko tego nie poprawią xd

**Comment by kukubaczek** [comment]
Właśnie co z MyHardem? xd

**Comment by kamcio96** [comment]
aktualnie jestem w trakcie testów tego, jak coś wyjdzie to będzie PR

co do myharda, to ja za 3 tygodnie mam myture xD wiec na razie nie ma tematu

ENG:
currently im testing my idea, i will create PR if something works

**Comment by md-5** [comment]
Update

**Comment by kukubaczek** [comment]
I am usig latest version.

**Comment by md-5** [comment]
What version?

**Comment by kukubaczek** [comment]
#1059
