### ISSUE TITLE
Server lag and crash!

### ISSUE THREAD

**Issue by kukubaczek** [SpigotMC/BungeeCord#1434]
Version of Bungee:
![zrzut ekranu 2015-04-14 16 08 19](https://cloud.githubusercontent.com/assets/6909820/7138402/8041dc8c-e2c0-11e4-83b6-58ce32725694.png)

```
16:03:58 [SEVERE] [/77.247.181.162:58593] <-> InitialHandler - encountered exception

io.netty.handler.codec.DecoderException: net.md_5.bungee.protocol.BadPacketException: Did not read all bytes from packet class net.md_5.bungee.protocol.packet.Handshake 0 Protocol HANDSHAKE Direction net.md_5.bungee.protocol.Protocol$DirectionData@5473e9b5

    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:278)

    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:147)

    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)

    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)

    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:161)

    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)

    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)

    at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150)

    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)

    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)

    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)

    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)

    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)

    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)

    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)

    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)

    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)

    at java.lang.Thread.run(Thread.java:745)

Caused by: net.md_5.bungee.protocol.BadPacketException: Did not read all bytes from packet class net.md_5.bungee.protocol.packet.Handshake 0 Protocol HANDSHAKE Direction net.md_5.bungee.protocol.Protocol$DirectionData@5473e9b5

    at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:37)

    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:247)

    ... 17 more
```

Bots atack the server and server generate this error ^^ and all players was kicked with message "Timed out".

Start line:
```
screen -S "Bungee" java -Xmx16G -jar BungeeCord.jar
```

**Comment by kamcio96** [comment]
Przestań spamowac tym...

**Comment by kukubaczek** [comment]
To niech kurde to poprawią, a nie zamykają tylko zgłoszenia...

**Comment by Janmm14** [comment]
16 gb is too much for bungeecord. java's gc pauses are likely to kill your server.

**Comment by kukubaczek** [comment]
Last I have 4gb, 8gb and this problem.

**Comment by kukubaczek** [comment]
This code help this error?

```
    @EventHandler
    public void onPing(ProxyPingEvent event) {

    	ServerPing sp = event.getResponse();
    	String ip = event.getConnection().getAddress().getAddress().toString();
    	

    	sp.getPlayers().setMax(event.getResponse().getPlayers().getOnline()+5);
		if(!ping.containsKey(ip)){
			ping.put(ip, System.currentTimeMillis());
			sp.setDescription("§8» §6MC.XFAST.PL §c«» \n§7Nowa edycja §aEasySurvival§7 w piatek o §a18:00§7!");
			return;
		}
		
		if(ping.get(ip) + 5000 > System.currentTimeMillis()){
			
	    	TextComponent msg = new TextComponent( "Error 569" );
	    	event.getConnection().disconnect(msg);
		}
		
		sp.setDescription("§8» §6MC.XFAST.PL §c«» \n§7Nowa edycja §aEasySurvival§7 w piatek o §a18:00§7!");
		ping.put(ip, System.currentTimeMillis());
    }
```

**Comment by kukubaczek** [comment]
[15:21:24 INFO]: angelika12 lost connection: Timed out
[15:21:24 INFO]: kuba123 lost connection: Timed out
[15:21:24 INFO]: Srey1337 lost connection: Timed out
[15:21:25 INFO]: [MC.XFAST.PL] Masz sprawe/cheatera pisz na /helpop
[15:21:25 INFO]: Kamil191 lost connection: Timed out
[15:21:25 INFO]: LoczeK13 lost connection: Timed out
[15:21:25 INFO]: Mistral1234 lost connection: Timed out
[15:21:25 INFO]: ZEK lost connection: Timed out
[15:21:25 INFO]: AdAsOwski04 lost connection: Timed out
[15:21:25 INFO]: ADAMEK lost connection: Timed out
[15:21:25 INFO]: BartekXD2 lost connection: Timed out
[15:21:25 INFO]: Boxon lost connection: Timed out
[15:21:26 INFO]: Lord_Viper lost connection: Timed out
[15:21:26 INFO]: Final_Architect lost connection: Timed out
[15:21:26 INFO]: elo23333 lost connection: Timed out
[15:21:26 INFO]: piotr123pl lost connection: Timed out
[15:21:29 INFO]: lolpo1231 lost connection: Timed out
[15:21:29 INFO]: harestonxd lost connection: Timed out
[15:21:29 INFO]: blackYT lost connection: Timed out
[15:21:29 INFO]: lolexddd lost connection: Timed out
[15:21:30 INFO]: Chaos lost connection: Timed out
[15:21:30 INFO]: Kaylea123 lost connection: Timed out
[15:21:30 INFO]: frOzen123321 lost connection: Timed out

**Comment by kamcio96** [comment]
No, that code isn't helpful

**Comment by kamcio96** [comment]
No, that code isn't helpful

**Comment by kukubaczek** [comment]
Can you help me? I will pay xd

**Comment by kukubaczek** [comment]
Help me!

**Comment by pedroo21** [comment]
Same happened to me.

**Comment by kukubaczek** [comment]
@up
Update bungee.
29 lip 2015 06:38 "pedroo21" <notifications@github.com> napisał(a):

**Comment by i9hdkill** [comment]
Please open a new ticket if this issue still persists in the latest version.
