### ISSUE TITLE
Bungeecord not allowing players join server

### ISSUE THREAD

**Issue by xanderc2** [SpigotMC/BungeeCord#1438]
That's the situation: i own many modded servers all running with bungeecord (aprox 50 players each)

now i'm going to host a new modpack but....
Modded pack (aprox 100 mods) with:
 forge 1370
 cauldron 1370
bungeecord 1059

server and client perfectly connect

when i try to put bungeecord between client and server i got an error from netty handler,
that's what i get from bungeecord console:

io.netty.handler.codec.DecoderException: java.lang.ArrayIndexOutOfBoundsException: -26
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:278)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:147)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:161)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
    at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ArrayIndexOutOfBoundsException: -26
    at net.md_5.bungee.protocol.Protocol$DirectionData.hasPacket(Protocol.java:125)
    at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:31)
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:247)
    ... 17 more

**Comment by XxCoolGamesxX** [comment]
Look on is: https://github.com/SpigotMC/BungeeCord/issues/1437

**Comment by XxCoolGamesxX** [comment]
Is the mod CoFH Core do the error. :P

**Comment by xanderc2** [comment]
OH! very nice thanks for the answer, understand, any way to fix it right now?

**Comment by XxCoolGamesxX** [comment]
No, recommended you put back to old version of it. 

COFHCORE-3.0.0RC7-211

If you have is mods it to put back to old version too.

MINEFACTORYRELOADED-2.8.0RC8-86
THERMALEXPANSION-4.0.0RC7-141
THERMALFOUNDATION-1.0.0RC7-62

Nope is help you. :P

**Comment by xanderc2** [comment]
oh damn, i hope they will fix it in the future, well, let's wait....

**Comment by XxCoolGamesxX** [comment]
Yup ;P
