### ISSUE TITLE
crash bungee

### ISSUE THREAD

**Issue by origamerpro** [SpigotMC/BungeeCord#1454]
crash error
14:01:49 [SEVERE] May 01, 2015 2:01:49 PM io.netty.channel.AbstractChannelHandlerContext invokeExceptionCaught
WARNING: An exception was thrown by a user handler's exceptionCaught() method while handling the following exception:
java.lang.ClassCastException: net.md_5.bungee.api.event.PreLoginEvent cannot be cast to java.lang.String
    at net.md_5.bungee.connection.InitialHandler$4.done(InitialHandler.java:327)
    at net.md_5.bungee.api.event.AsyncEvent.postCall(AsyncEvent.java:39)
    at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:365)
    at net.md_5.bungee.connection.InitialHandler.handle(InitialHandler.java:362)
    at net.md_5.bungee.protocol.packet.LoginRequest.handle(LoginRequest.java:39)
    at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:75)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
    at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
    at java.lang.Thread.run(Thread.java:745)

**Comment by yawkat** [comment]
Version?

**Comment by origamerpro** [comment]
#1059

**Comment by kamcio96** [comment]
java.lang.ClassCastException: net.md_5.bungee.api.event.PreLoginEvent cannot be cast to java.lang.String
at net.md_5.bungee.connection.InitialHandler$4.done(InitialHandler.java:327)

https://github.com/SpigotMC/BungeeCord/blob/master/proxy/src/main/java/net/md_5/bungee/connection/InitialHandler.java#L327
Did you edit that file?

**Comment by origamerpro** [comment]
not edit 327 string , edit session link on my web server.

**Comment by md-5** [comment]
We don't support edited Bungee
