### ISSUE TITLE
Packet Encoder Errors Occasionally in logs build 1059

### ISSUE THREAD

**Issue by mcraftpete** [SpigotMC/BungeeCord#1460]
Hi,
I see some of these errors on build 1059 ... not sure what it is or if its causing a real problem but wanted to report it just in case :)
08:59:47 [INFO] Loaded player Â§9timefree
08:59:47 [INFO] [timefree] <-> ServerConnector [hub] has connected
08:59:47 [INFO] [timefree] -> UpstreamBridge has disconnected
08:59:47 [SEVERE] [timefree] <-> ServerConnector [hub] - encountered exception
java.util.NoSuchElementException: packet-encoder
	at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:907)
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:157)
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:150)
	at net.md_5.bungee.netty.ChannelWrapper.addBefore(ChannelWrapper.java:69)
	at net.md_5.bungee.netty.ChannelWrapper.setCompressionThreshold(ChannelWrapper.java:81)
	at net.md_5.bungee.UserConnection.setCompressionThreshold(UserConnection.java:591)
	at net.md_5.bungee.ServerConnector.handle(ServerConnector.java:146)
	at net.md_5.bungee.protocol.packet.SetCompression.handle(SetCompression.java:36)
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:75)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:161)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:161)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Unknown Source)
08:59:47 [INFO] [timefree] disconnected with: Â§fException Connecting:NoSuchElementException : packet-encoder @ io.netty.channel.DefaultChannelPipeline:907
08:59:47 [INFO] [timefree] <-> ServerConnector [hub] has disconnected
08:59:47 [WARNING] [/184.6.228.113:63780] <-> InitialHandler - read timed out

**Comment by md-5** [comment]
#1489
