### ISSUE TITLE
bungeecord crash 1061

### ISSUE THREAD

**Issue by magacraft99** [SpigotMC/BungeeCord#1464]
[INFOS] Enabled plugin cmd_alert version git:cmd_alert:1.8-SNAPSHOT:"88e71ea":1061 by SpigotMC
17:17:43 [INFOS] Enabled plugin cmd_send version git:cmd_send:1.8-SNAPSHOT:"88e71ea":1061 by SpigotMC
17:17:43 [INFOS] Enabled plugin cmd_list version git:cmd_list:1.8-SNAPSHOT:"88e71ea":1061 by SpigotMC
17:17:43 [INFOS] Listening on /0.0.0.0:25565
17:18:05 [INFOS] [/127.0.0.1:52599] <-> InitialHandler has connected
17:18:08 [INFOS] [/127.0.0.1:52611] <-> InitialHandler has connected
17:18:08 [GRAVE] [magacraft99] <-> InitialHandler - encountered exception
java.lang.ExceptionInInitializerError
at javax.crypto.Cipher.getInstance(Cipher.java:510)
at net.md_5.bungee.EncryptionUtil.getSecret(EncryptionUtil.java:58)
at net.md_5.bungee.connection.InitialHandler.handle(InitialHandler.java:370)
at net.md_5.bungee.protocol.packet.EncryptionResponse.handle(EncryptionResponse.java:53)
at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:75)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:161)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:161)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.SecurityException: Can not initialize cryptographic mechanism
at javax.crypto.JceSecurity.(JceSecurity.java:89)
... 24 more
Caused by: java.lang.SecurityException: Cannot locate policy or framework files!
at javax.crypto.JceSecurity.setupJurisdictionPolicies(JceSecurity.java:254)
at javax.crypto.JceSecurity.access$000(JceSecurity.java:48)
at javax.crypto.JceSecurity$1.run(JceSecurity.java:81)
at java.security.AccessController.doPrivileged(Native Method)
at javax.crypto.JceSecurity.(JceSecurity.java:78)
... 24 more

**Comment by kamcio96** [comment]
os?

**Comment by magacraft99** [comment]
windows 8.1

**Comment by Phineas-0510** [comment]
Plugin list?

**Comment by Brombeersaft** [comment]
Whats your java version?

**Comment by kamcio96** [comment]
and java version? :D

**Comment by magacraft99** [comment]
no plugin and java 7

**Comment by magacraft99** [comment]
somebody can help me ?

**Comment by Janmm14** [comment]
try to reinstall java

**Comment by Janmm14** [comment]
or try java 8

**Comment by magacraft99** [comment]
i had java 8 and i must use java 7.

now it work very well.
thanks for helping.

**Comment by md-5** [comment]
> Caused by: java.lang.SecurityException: Cannot locate policy or framework files!

Yeah your java broke
