### ISSUE TITLE
Bungee CRASH [UNSOLVED] [SEVERE] java.util.NoSuchElementException: packet-encoder

### ISSUE THREAD

**Issue by JamesHooks90** [SpigotMC/BungeeCord#1471]
1. Error in BungeeCoord
2. Massive Lag
3. Bungee Dies
4. Cant reach the server

I seen all git hub posts/issues + spigot, no help found.

______________________________________________________________________________
00:53:47 [INFO] [/:] <-> InitialHandler has connected
00:53:47 [SEVERE] [J@viXD] <-> ServerConnector [Lobby] - encountered exception
java.util.NoSuchElementException: packet-encoder
	at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:907)
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:157)
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:150)
	at net.md_5.bungee.netty.ChannelWrapper.addBefore(ChannelWrapper.java:69)
	at net.md_5.bungee.netty.ChannelWrapper.setCompressionThreshold(ChannelWrapper.java:81)
	at net.md_5.bungee.UserConnection.setCompressionThreshold(UserConnection.java:591)
	at net.md_5.bungee.ServerConnector.handle(ServerConnector.java:146)
	at net.md_5.bungee.protocol.packet.SetCompression.handle(SetCompression.java:36)
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:75)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Unknown Source)
00:53:47 [INFO] [J@viXD] <-> ServerConnector [Lobby] has disconnected
00:53:47 [INFO] [DarkFairy47] -> UpstreamBridge has disconnected
00:53:47 [INFO] [bimbo] -> UpstreamBridge has disconnected
00:53:47 [INFO] [ale2000] <-> ServerConnector [Lobby] has connected

**Comment by JamesHooks90** [comment]
#1366 Is no solution for me. Downgrade? Nope I tried 5 versions.

**Comment by JamesHooks90** [comment]
http://www.spigotmc.org/threads/what-do-you-think-packet-encoder.68787/

**Comment by JamesHooks90** [comment]
bump

**Comment by md-5** [comment]
#1489
