### ISSUE TITLE
What is this error?

### ISSUE THREAD

**Issue by agusztin** [SpigotMC/BungeeCord#1479]
What is this error?
if need the config.yml just tell me
[...]
22:22:18 [INFORMACIÓN] [jared] -> UpstreamBridge has disconnected
22:22:18 [INFORMACIÓN] [jared] disconnected with: §f[Proxy] Lost connection to server.
22:22:18 [INFORMACIÓN] [jared] <-> DownstreamBridge <-> [SkyWars] has disconnected
22:22:20 [GRAVE] may 24, 2015 10:22:20 PM io.netty.channel.DefaultChannelPipeline$TailContext exceptionCaught
ADVERTENCIA: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.IllegalStateException: No session!
	at net.md_5.bungee.query.QueryHandler.channelRead0(QueryHandler.java:82)
	at net.md_5.bungee.query.QueryHandler.channelRead0(QueryHandler.java:20)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
	at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Unknown Source)
[...]

**Comment by nikosgram13** [comment]
I need your configuration file... :smile:

**Comment by agusztin** [comment]
http://pastebin.com/xpkiZPd3
I have enable the port 25565 tpc and 25565 udp for gametracker

**Comment by md-5** [comment]
Just people sending invalid gametracker data

**Comment by agusztin** [comment]
So, is a bug with little importance?
i need disable my server from gametracker?

**Comment by nikosgram13** [comment]
You can disable the query or use some Proxy server.

**Comment by agusztin** [comment]
I know but is a error with little importance or no?

**Comment by Janmm14** [comment]
If you do not have other errors, then I would say the importance is low
