### ISSUE TITLE
Bungee crasher (new...)

### ISSUE THREAD

**Issue by kukubaczek** [SpigotMC/BungeeCord#1489]
```
14:55:28 [SEVERE] [Dawideczej] <-> ServerConnector [Lobby] - encountered exception
java.util.NoSuchElementException: packet-encoder
 at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:907)
 at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:157)
 at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:150)
 at net.md_5.bungee.netty.ChannelWrapper.addBefore(ChannelWrapper.java:69)
 at net.md_5.bungee.netty.ChannelWrapper.setCompressionThreshold(ChannelWrapper.java:81)
 at net.md_5.bungee.UserConnection.setCompressionThreshold(UserConnection.java:591)
 at net.md_5.bungee.ServerConnector.handle(ServerConnector.java:146)
 at net.md_5.bungee.protocol.packet.SetCompression.handle(SetCompression.java:36)
 at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:75)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
 at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
 at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
 at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
 at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
 at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
 at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
 at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
 at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
 at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
 at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
 at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
 at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
 at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
 at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
 at java.lang.Thread.run(Thread.java:745)
14:55:28 [INFO] [Dawideczej] disconnected with: §fException Connecting:NoSuchElementException : packet-encoder @ io.netty.channel.DefaultChannelPipeline:907
```

When I have this error my server is freeze, and kicking players.

**Comment by yawkat** [comment]
Plugins? Bungee version? Ping passthrough enabled? Online mode? Is this error spammed? CPU / mem load?

**Comment by Xayanix** [comment]
Should be ping_passthrough turned on?

**Comment by yawkat** [comment]
No, should not be turned on

**Comment by yawkat** [comment]
Someone says [this commit](https://github.com/OvercastNetwork/BungeeCord/commit/2b06ebc7508ed385e0d3f4131b248856f4d378c5) might fix this, but keep this issue open please

**Comment by Xayanix** [comment]
BungeeCord version: #1068
Plugins: AnimMOTD, BungeeMSG, NS_AdminChat (custom), NS_Bungee (custom), SlashServer, SwiftMOTD
Ping_Passthrough: false

Error appears once, after this bungee is getting freeezed for some time.

**Comment by Xayanix** [comment]
I think that this fix is working, server didn't crash since 3 hours.

**Comment by kukubaczek** [comment]
Can you give me link to this fix?

**Comment by md-5** [comment]
Ignoring an exception is not a fix.

**Comment by Xayanix** [comment]
But works ^^.
Server didn't crash.


Fix it, please.

**Comment by kukubaczek** [comment]
Add this to original BungeeCord.

**Comment by Xayanix** [comment]
This code fixed this issue: http://pastebin.com/Q95YdwaS
If error occurs: http://pastebin.com/uLhT0cAK
Bungee did not crash.

**Comment by kukubaczek** [comment]
Can you give me DL? Or @md-5 can you fix this in official commit?

**Comment by kukubaczek** [comment]
@md-5
Please add this to official Bungee cord.

**Comment by Janmm14** [comment]
Wouldn't it be better to insert packet-encoder into the pipeline if its missing instead of just wrapping the exception or ignoring it?

**Comment by yawkat** [comment]
A check would be better, yes.

**Comment by md-5** [comment]
And yet no one can explain how packet-encoder which is added on connection goes missing.
This issue won't be fixed until someone can identify that.
