### ISSUE TITLE
Cauldron 1.7.10 not connecting

### ISSUE THREAD

**Issue by Yanniclord** [SpigotMC/BungeeCord#1497]
Hey, i got an issue with my Bungeecord setup, and im sure its on Bungee and Cauldron its connection site. I am running these builds in the Bungee network:

Bungeecord: Bungeecord #1013
Spigot (Lobby Server): spigot-1.7.10-SNAPSHOT-b1657
Cauldron (Modded Server): Cauldron-Reloaded-1.7.10-1.1388.1.0 (MC: 1.7.10)

The log i am getting: 

io.netty.handler.codec.DecoderException: java.lang.ArrayIndexOutOfBoundsException: -26
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:280)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:722)
Caused by: java.lang.ArrayIndexOutOfBoundsException: -26
	at net.md_5.bungee.protocol.Protocol$DirectionData.hasPacket(Protocol.java:125)
	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:29)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249)
	... 17 more

Thanks for the attention :)

**Comment by Janmm14** [comment]
Cauldron seems to use negative packet ids:

io.netty.handler.codec.DecoderException: java.lang.ArrayIndexOutOfBoundsException: -26

@md_5 earlier said he won't fix that

**Comment by Yanniclord** [comment]
Aha well nevermind, someone else forked Bungeecord and fixed especially this for modded servers. My network now runs fine, so thanks for nothing, saying he wont fix it doesnt give it a reason. Like Bungeecord with mods is amazing i promise you, sadly md_5 doesnt give official support on this. But ye as i said i got it already going.

**Comment by Janmm14** [comment]
That's why its open-source. So anyone can do what he wants.
