### ISSUE TITLE
Too many open files Build #1071

### ISSUE THREAD

**Issue by JamesHooks90** [SpigotMC/BungeeCord#1500]
I never had this problem before with any other versions.
>19:44:51 [SEVERE] Jun 10, 2015 7:44:51 PM io.netty.channel.DefaultChannelPipeline$TailContext exceptionCaught
WARNING: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.io.IOException: Too many open files
	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
	at sun.nio.ch.ServerSocketChannelImpl.accept(Unknown Source)
	at io.netty.channel.socket.nio.NioServerSocketChannel.doReadMessages(NioServerSocketChannel.java:135)
	at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:69)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Unknown Source)

I get this error like thousands of hundreds times, every player connection.

Our server got like 800/900 players. With a reset the issue goes away, but after x time goes back.

**Comment by minecrafter** [comment]
Raise your file limit and ulimit

**Comment by LordAkkarin** [comment]
This is not an issue with Bungeecord. It's rather your system running out of files (or sockets in this case) that may be opened. You will need to extend those values according to your Linux distribution's documentation ;-)

**Comment by JamesHooks90** [comment]
Thanks for your support, I will look in to it!
