### ISSUE TITLE
Why can't use my public ip to login bungeecord?

### ISSUE THREAD

**Issue by TheBlueKingLP** [SpigotMC/BungeeCord#1511]
15:50:55 [warn] Could not bind to host tbknetwork.servegame.com/116.48.xx.xxx:25565

java.net.BindException: Can't assign requested address

at sun.nio.ch.Net.bind0(Native Method)

at sun.nio.ch.Net.bind(Net.java:436)

at sun.nio.ch.Net.bind(Net.java:428)

at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:214)

at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)

at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:125)

at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:478)

at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1021)

at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:455)

at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:440)

at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:844)

at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:197)

at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:350)

at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)

at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)

at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)

at java.lang.Thread.run(Thread.java:745)

i am not using router!
i am using NO-IP( http://no-ip.com )
my bungeecord config:

groups:
TheBlueKingLP:
- admin
disabled_commands:
- disabledcommandhere
player_limit: -1
stats: 7c586d7f-fe82-4fef-bff6-bf7c2b2565e7
permissions:
default:
- bungeecord.command.server
- bungeecord.command.list
admin:
- bungeecord.command.alert
- bungeecord.command.end
- bungeecord.command.ip
- bungeecord.command.reload
listeners:
- query_port: 25577
motd: '&1Another Bungee server'
tab_list: GLOBAL_PING
query_enabled: false
forced_hosts:
tbknetwork.servegame.com: pvp
ping_passthrough: false
default_server: lobby
bind_local_address: false
fallback_server: lobby
host: tbknetwork.servegame.com:25565
max_players: 1
tab_size: 60
force_default_server: false
timeout: 300000
connection_throttle: 4000
servers:
lobby:
motd: '&1Just another BungeeCord - Forced Host'
address: localhost:60000
restricted: false
ip_forward: true
online_mode: true

**Comment by minecrafter** [comment]
Output of `ipconfig`?

**Comment by TheBlueKingLP** [comment]
i am use mac,no ipconfig

**Comment by XxCoolGamesxX** [comment]
Sure work the cmd of the ipconfig.

http://www.maclife.com/article/columns/terminal_101_find_your_ip_address

**Comment by Janmm14** [comment]
it would be nice if you used pastebin for your config or surround your config by ```

**Comment by Janmm14** [comment]
you can't input your public ip into your bungee config. use 0.0.0.0 as the default is.

**Comment by TheBlueKingLP** [comment]
bit i use 0.0.0.0 only can use LogMeIn Hamachi / 127.0.0.1 to login my server

**Comment by Janmm14** [comment]
that's normal
