### ISSUE TITLE
Server Timeout kick issue without any reports

### ISSUE THREAD

**Issue by DavidStyler10** [SpigotMC/BungeeCord#1519]
Dear Bungeecord development team!
One of my Spigot based servers (connected in a bungeecoord network) throws an IOException (Without printing the stacktrace) every few minutes. Here everything that is visible in the console:

PlayerName lost connection: Internal Exception: java.io.IOException: Error while read(...): Connection reset by peer

There is always an other player that gets kicked. I dont think this is client based because there is no player that dont gets kicked. The kick message is "The Server you were on previously went down. You have been teleported to the lobby". After the kick you can join and continue playing. 
Are there any known sources that can generate this issue?

~ David

**Comment by Janmm14** [comment]
Do you have set connection throttle **IN bukkit.yml** to -1?

**Comment by i9hdkill** [comment]
Yes it's set to -1 
We got this problem on all our Bukkit servers.
Even on servers on the same physical machine.
Quite strange. Don't know when it started.
BungeeCord #1071 and Spigot 1.8.7 built on the 26.06

**Comment by 9190281** [comment]
Can confirm this is an issue, been happening with my network, too.

**Comment by terokorp** [comment]
+1

**Comment by pedroo21** [comment]
This has been happening in my full Network. From a moment without reason, whole network get's freezed and you can see everyone getting disconnected in bungee logs for "timed out".

I don't know if this is related but mojang website server was down during that moment.

**Comment by griffen4** [comment]
Can confirm this is still and issue. Please update with a fix. As soon as u get a chance

**Comment by sebastianbinder** [comment]
Happening here as well, started today. Don't know why...

**Comment by Foreme** [comment]
Still happening for me, it has happened on all 3 of the server connected to the bungee network but it happens most frequently on the Survival server and is a rare occurrence in the Hub or Creative. On Survival, after the daily server restart no player can connect and every player gets this error. The only way to fix it is to restart the server multiple times until players can connect again. Not sure why it happens on Survival so often and not the other servers (happens almost every time the server restarts) Survival has more plugins and is used more, that's the only difference.

**Comment by Foreme** [comment]
`[06:27:32] [Server thread/INFO]: Done (19.512s)! For help, type "help" or "?"
[06:27:32] [Server thread/INFO]: Starting GS4 status listener
[06:27:32] [Query Listener #1/INFO]: Query running on 0.0.0.0:25564
[06:27:32] [Craft Scheduler Thread - 0/INFO]: Starting ws client
[06:27:32] [Thread-46/INFO]: The server has connected to the main proxy server
[06:27:32] [Craft Scheduler Thread - 0/INFO]: [NoCheatPlus] Added hook: AllViolations(NCP) [1.0].
[06:27:32] [Craft Scheduler Thread - 0/INFO]: [NoCheatPlus] Added hook: Citizens2(cncp) [2.0].
[06:27:32] [Craft Scheduler Thread - 0/INFO]: [NoCheatPlus] Added hook: mcMMO(cncp) [2.3].
[06:27:32] [Craft Scheduler Thread - 6/INFO]: [GAListener] Connection established!
[06:27:32] [Craft Scheduler Thread - 6/INFO]: [GAListener] Found database: GALVOTE
[06:27:32] [Craft Scheduler Thread - 6/INFO]: [GAListener] Using database: GALVOTE
[06:27:32] [Craft Scheduler Thread - 6/INFO]: [GAListener] Loaded 195 queued votes
[06:27:32] [Server thread/INFO]: CONSOLE issued server command: /baltop 
[06:27:32] [Server thread/INFO]: CONSOLE issued server command: /baltop 
[06:27:32] [Server thread/INFO]: [NoCheatPlus] Post-enable running...
[06:27:32] [Thread-49/INFO]: UUID of player RizDaRZR is 35d2b9f3-ef6a-4e85-933e-027ca4fa854c
[06:27:32] [Server thread/INFO]: [NoCheatPlus] Post-enable finished.
[06:27:32] [Server thread/INFO]: [BanManager] The following commands are blocked whilst muted:
[06:27:32] [Server thread/INFO]: [BanManager] msg - w m t pm emsg epm tell etell whisper ewhisper 
[06:27:32] [Server thread/INFO]: [BanManager] The following commands are blocked whilst soft muted:
[06:27:32] [Server thread/INFO]: [BanManager] msg - w m t pm emsg epm tell etell whisper ewhisper 
[06:27:32] [Server thread/INFO]: [Citizens] Loaded 6 NPCs.
[06:27:32] [Craft Scheduler Thread - 32/INFO]: [Vault] Checking for Updates ... 
[06:27:32] [Craft Scheduler Thread - 13/INFO]: [LWC] [LWC] The updater ran into a minor issue: http://update.griefcraft.com/lwc/branch/stable/LATEST
[06:27:32] [Craft Scheduler Thread - 13/INFO]: [LWC] [LWC] This can probably be ignored.
[06:27:33] [Craft Scheduler Thread - 32/INFO]: [Vault] No new version available
[06:27:33] [Server thread/INFO]: too_pyro[/74.195.42.216:41611] logged in with entity id 490 at ([world]-11060.059040347482, 51.0, -5741.626408085171)
[06:27:33] [Server thread/INFO]: RizDaRZR[/94.187.195.245:54672] logged in with entity id 495 at ([world]-2759.5, 81.0, 13885.5)
[06:27:33] [Server thread/INFO]: too_pyro lost connection: Disconnected
[06:27:33] [Server thread/INFO]: RizDaRZR lost connection: Internal Exception: java.io.IOException: Error while write(...): Broken pipe
[06:27:33] [Server thread/INFO]: [mcMMO] Aborting profile loading recovery for too_pyro - player logged out
[06:27:33] [Server thread/INFO]: [mcMMO] Aborting profile loading recovery for RizDaRZR - player logged out
[06:27:33] [Craft Scheduler Thread - 20/ERROR]: [FeatherBoard] java.lang.IllegalArgumentException: A team with the name 'MVdWFB011' already exists!
	at net.minecraft.server.v1_8_R3.Scoreboard.createTeam(SourceFile:218)
	at org.bukkit.craftbukkit.v1_8_R3.scoreboard.CraftScoreboard.registerNewTeam(CraftScoreboard.java:142)
	at be.maximvdw.featherboardcore.l.g.a(Sidebarv5.java:346)
	at be.maximvdw.featherboardcore.l.g.a(Sidebarv5.java:248)
	at be.maximvdw.featherboardcore.l.g.b(Sidebarv5.java:331)
	at be.maximvdw.featherboardcore.l.b.b(SidebarWrapper.java:178)
	at be.maximvdw.featherboard.BoardGroup.init(Unknown Source)
	at be.maximvdw.featherboard.b.a$1.run(PlayerListener.java:58)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

[06:27:33] [Server thread/INFO]: [AncientGatesReloaded v1.8.4] Loading gates from disk
[06:27:33] [Server thread/INFO]: [AncientGatesReloaded v1.8.4] 1
[06:27:33] [Server thread/INFO]: [AncientGatesReloaded v1.8.4] 1
[06:27:33] [Server thread/INFO]: [AncientGatesReloaded v1.8.4] Loading gates into memory
[06:27:34] [Server thread/INFO]: [AncientGatesReloaded v1.8.4] Enabled
[06:27:48] [Thread-52/INFO]: UUID of player too_pyro is 8421e328-a184-41b2-a40b-561a50a73866
[06:27:48] [Server thread/WARN]: Failed to handle packet for /74.195.42.216:35385
java.lang.NegativeArraySizeException
	at java.util.AbstractCollection.toArray(AbstractCollection.java:136) ~[?:1.8.0_40]
	at java.util.ArrayList.addAll(ArrayList.java:577) ~[?:1.8.0_40]
	at net.minecraft.server.v1_8_R3.PacketPlayOutScoreboardTeam.<init>(SourceFile:48) ~[spigot.jar:git-Spigot-db6de12-930a59c]
	at net.minecraft.server.v1_8_R3.PlayerList.sendScoreboard(PlayerList.java:197) ~[spigot.jar:git-Spigot-db6de12-930a59c]
	at net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.java:141) ~[spigot.jar:git-Spigot-db6de12-930a59c]
	at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:144) ~[spigot.jar:git-Spigot-db6de12-930a59c]
	at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:54) ~[spigot.jar:git-Spigot-db6de12-930a59c]
	at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:231) ~[spigot.jar:git-Spigot-db6de12-930a59c]
	at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:148) [spigot.jar:git-Spigot-db6de12-930a59c]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:814) [spigot.jar:git-Spigot-db6de12-930a59c]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-db6de12-930a59c]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-db6de12-930a59c]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-db6de12-930a59c]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_40]
[06:27:49] [Server thread/INFO]: too_pyro lost connection: Internal server error
[06:28:12] [Thread-53/INFO]: UUID of player Da_Crazy_One is 2bc3b5c4-f190-423e-8f90-ecd95573a47a
[06:28:13] [Server thread/INFO]: [LoyaltyRewards] Excecuting reward for Da_Crazy_One for logging in 1 days in a row.
[06:28:13] [Server thread/INFO]: Da_Crazy_One[/118.92.65.209:36099] logged in with entity id 1040 at ([world]15991.32677459251, 72.0, -11844.137756449205)
[06:28:13] [Netty Epoll Server IO #2/WARN]: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.nio.channels.ClosedChannelException
[06:28:13] [Server thread/INFO]: Da_Crazy_One lost connection: Disconnected
[06:28:13] [Server thread/INFO]: [mcMMO] Aborting profile loading recovery for Da_Crazy_One - player logged out
[06:28:13] [Server thread/INFO]: [0;37;1m[3m C[0;35;1m[3mR[0;37;1m[3mLootbox [0;35;1m➢[m [0;37;1mThat was an invalid player![m
[06:28:26] [Thread-54/INFO]: UUID of player Da_Crazy_One is 2bc3b5c4-f190-423e-8f90-ecd95573a47a
[06:28:26] [Server thread/INFO]: Da_Crazy_One[/118.92.65.209:56777] logged in with entity id 1120 at ([world]15991.32677459251, 72.0, -11844.137756449205)
[06:28:26] [Server thread/INFO]: Da_Crazy_One lost connection: Internal Exception: java.io.IOException: Error while write(...): Broken pipe
[06:28:26] [Server thread/INFO]: [mcMMO] Aborting profile loading recovery for Da_Crazy_One - player logged out
[06:28:41] [Thread-55/INFO]: UUID of player Da_Crazy_One is 2bc3b5c4-f190-423e-8f90-ecd95573a47a
[06:28:41] [Server thread/INFO]: Da_Crazy_One[/118.92.65.209:44596] logged in with entity id 1200 at ([world]15991.32677459251, 72.0, -11844.137756449205)
[06:28:41] [Server thread/INFO]: Da_Crazy_One lost connection: Internal Exception: java.io.IOException: Error while write(...): Broken pipe
[06:28:41] [Server thread/INFO]: [mcMMO] Aborting profile loading recovery for Da_Crazy_One - player logged out
[06:28:58] [Server thread/INFO]: [0;37;22m● [0;37;1m[21mCrafters[0;35;1m[21mRefuge [0;37;22m● Unknown command. Type "/help" for help.[m
[06:29:02] [Server thread/INFO]: Saving...
[06:29:02] [Server thread/INFO]: Saved the world
[06:29:03] [Server thread/INFO]: [Server] - Server is shutting down -
[06:29:08] [Thread-56/INFO]: UUID of player Da_Crazy_One is 2bc3b5c4-f190-423e-8f90-ecd95573a47a
[06:29:08] [Server thread/INFO]: Da_Crazy_One[/118.92.65.209:42324] logged in with entity id 1280 at ([world]15991.32677459251, 72.0, -11844.137756449205)
[06:29:08] [Server thread/INFO]: Da_Crazy_One lost connection: Disconnected
[06:29:08] [Server thread/INFO]: [mcMMO] Aborting profile loading recovery for Da_Crazy_One - player logged out
[06:29:09] [Server thread/INFO]: Stopping the server
[06:29:09] [Server thread/INFO]: Stopping server`

**Comment by i9hdkill** [comment]
Fixed. Was a linux server issue.

**Comment by ScuroK** [comment]
@i9hdkill  how did you fix it? i have similar issues on my linux server
