### ISSUE TITLE
Internal Exception: java.io.IOException: Broken pipe

### ISSUE THREAD

**Issue by mcraftpete** [SpigotMC/BungeeCord#1526]
Not sure if this is bungee or spigot and couldn't find a fix anywhere.
Bungee :1071
Spigot build 20150617

[14:46:10] [Server thread/INFO]: mcraftpete[/5.62.27.102:37867] logged in with entity id 542 at ([world]401.3386492433025, 73.67581053946196, -37.42131288642516)
[14:46:10] [Server thread/INFO]: mcraftpete lost connection: Internal Exception: java.io.IOException: Broken pipe
[14:46:13] [Thread-46/INFO]: UUID of player CaoshB is c5a4c7c8-6b03-4ce8-a4c5-d7d89f462dc6
[14:46:13] [Server thread/INFO]: CaoshB[/70.49.153.21:53136] logged in with entity id 543 at ([world]394.5, 70.5, -101.5)
[14:46:13] [Craft Scheduler Thread - 5/INFO]: [GAListener] Player: CaoshB has 0 votes
[14:46:13] [Server thread/INFO]: CaoshB lost connection: Internal Exception: java.io.IOException: Connection reset by peer
[14:46:17] [Thread-47/INFO]: UUID of player skullmaster99 is aec0412b-a4b2-4a85-a12e-f78a49da4e9b
[14:46:17] [Server thread/INFO]: skullmaster99[/66.223.132.206:50645] logged in with entity id 544 at ([world]394.5, 70.5, -101.5)
[14:46:17] [Server thread/INFO]: skullmaster99 lost connection: Internal Exception: java.io.IOException: Connection reset by peer
[14:46:18] [Thread-48/INFO]: UUID of player CaoshB is c5a4c7c8-6b03-4ce8-a4c5-d7d89f462dc6
[14:46:18] [Server thread/INFO]: CaoshB[/70.49.153.21:45443] logged in with entity id 547 at ([world]394.5, 70.5, -101.5)
[14:46:18] [Craft Scheduler Thread - 24/INFO]: [GAListener] Player: CaoshB has 0 votes
[14:46:18] [Server thread/INFO]: CaoshB lost connection: Internal Exception: java.io.IOException: Connection reset by peer

Not ure if this is bungee or spigot issue ?

**Comment by mcraftpete** [comment]
Hi,
I just checked bungee to match the time to this event and have this in the logs...

14:47:35 [SEVERE] [mcraftpete] <-> DownstreamBridge <-> [Bending] - encountered exception
java.lang.IllegalArgumentException: Team MVdW80 already exists in this scoreboard
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
	at net.md_5.bungee.api.score.Scoreboard.addTeam(Scoreboard.java:68)
	at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:183)
	at net.md_5.bungee.protocol.packet.Team.handle(Team.java:106)
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:76)

**Comment by kamcio96** [comment]
bukkit plugins shouldn't use scoreboard api in PlayerJoinEvent

**Comment by mcraftpete** [comment]
Not sure what you mean ? This is a plugin issue possibly ?

**Comment by XxCoolGamesxX** [comment]
What plugin's you have on the BungeeCord ?

**Comment by kamcio96** [comment]
and on craftbukkit?

**Comment by mcraftpete** [comment]
I have none on bungeecord , and this happens on multiple servers of mine , and I have different plugins on each , I have tried disabling etc too , but its only at restarts , so I made less restarts and only at times when I am awake :P

**Comment by mcraftpete** [comment]
I read online and there are many many ppl with this same issue.

**Comment by Janmm14** [comment]
Maybe we have to modify bungee to delay the scoreboard packet handling after joining another server a bit

**Comment by kamcio96** [comment]
I suggest to write to plugin's authors. They should add delay for scoreboard after player join. 
@Janmm14 i think we should find a better solution

**Comment by i9hdkill** [comment]
Please open a new ticket if this issue still persists in the latest version.

**Comment by Kainzo** [comment]
I am seeing this issue again, heh...
