### ISSUE TITLE
Not expecting PING

### ISSUE THREAD

**Issue by Foreme** [SpigotMC/BungeeCord#1536]
This anything to worry about?

java.lang.IllegalStateException: Not expecting PING
    at com.google.common.base.Preconditions.checkState(Preconditions.java:173)
    at net.md_5.bungee.connection.InitialHandler.handle(InitialHandler.java:244)
    at net.md_5.bungee.protocol.packet.PingPacket.handle(PingPacket.java:35)
    at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:76)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:161)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
    at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
    at java.lang.Thread.run(Thread.java:745)

**Comment by md-5** [comment]
No, just means a client is sending invalid data.

**Comment by chillerkraft** [comment]
does it have to send 30 lines of spam every 30 mins?

**Comment by Janmm14** [comment]
@chillerkraft All previous reports on reducing console messages have been rejected because you can/should use log filters.

**Comment by chillerkraft** [comment]
@Janmm14 so i should use a log filter plugin to filter out those messages? i've been interested in finding a plugin like that, but haven't had much luck.. :/

**Comment by growlf** [comment]
Try setting up something like Log.io and restrict acces to it to your local net.  Super simple, very flexible: http://logio.org/

**Comment by maxlehot1234** [comment]
Anyone have a video guide about how to restrict it? Is it work great with multicraft panel/console?
Thanks
