### ISSUE TITLE
ResourcePack kicking player

### ISSUE THREAD

**Issue by TobyMellor** [SpigotMC/BungeeCord#1541]
Hello,
I'm trying to prompt a resourcepack using player.setResourcepack().
When I do this, it pops up to the player saying "100%", then kicks them to the hub with the message "The server has gone down and you have been sent to the hub", but the server didn't go down and everything is still running -- only I got kicked/ received this message.
When looking at the Bungee console, I received this error:
`07:44:46 [SEVERE] [IntenseArmadillo] <-> DownstreamBridge <-> [Prison] - encountered exception
io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:99)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:161)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:161)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IndexOutOfBoundsException
at io.netty.buffer.EmptyByteBuf.readByte(EmptyByteBuf.java:440)
at net.md_5.bungee.protocol.DefinedPacket.readVarInt(DefinedPacket.java:111)
at net.md_5.bungee.protocol.DefinedPacket.readVarInt(DefinedPacket.java:101)
at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:28)
at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:10)
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89)
... 19 more
07:44:46 [INFO] [IntenseArmadillo] <-> DownstreamBridge <-> [Prison] has disconnected
07:44:46 [INFO] [IntenseArmadillo] <-> ServerConnector [Hub] has connected`.

This is what was received on the clients console:
`[12:40:44] [Client thread/INFO]: Reloading ResourceManager: Default
[12:40:44] [Client thread/INFO]: SoundSystem shutting down...
[12:40:45] [Client thread/WARN]: Author: Paul Lamb, www.paulscode.com
[12:40:45] [Sound Library Loader/INFO]: Starting up SoundSystem...
[12:40:45] [Thread-12/INFO]: Initializing LWJGL OpenAL
[12:40:45] [Thread-12/INFO]: (The LWJGL binding of OpenAL. For more information, see http://www.lwjgl.org)
[12:40:45] [Thread-12/INFO]: OpenAL initialized.
[12:40:45] [Sound Library Loader/INFO]: Sound engine started
[12:40:45] [Client thread/INFO]: Created: 512x512 textures-atlas
[12:40:46] [Client thread/INFO]: [CHAT] The server you were previously on went down, you have been connected to the lobby
[12:40:48] [Client thread/INFO]: [CHAT] //in hub from here on out, server did not actually "go down"
[12:40:48] [Client thread/INFO]: Reloading ResourceManager: Default, legacy
[12:40:48] [Client thread/INFO]: SoundSystem shutting down...
[12:40:48] [Client thread/WARN]: Author: Paul Lamb, www.paulscode.com
[12:40:48] [Sound Library Loader/INFO]: Starting up SoundSystem...
[12:40:48] [Thread-14/INFO]: Initializing LWJGL OpenAL
[12:40:48] [Thread-14/INFO]: (The LWJGL binding of OpenAL. For more information, see http://www.lwjgl.org)
[12:40:48] [Thread-14/INFO]: OpenAL initialized.
[12:40:49] [Sound Library Loader/INFO]: Sound engine started
[12:40:49] [Client thread/INFO]: Created: 512x512 textures-atlas`

Additional Information:
07:48:36 [INFO] This server is running BungeeCord version git:BungeeCord-Bootstrap:1.8-SNAPSHOT:"f3c14cf":1073 by md_5

**Comment by nerdtron123** [comment]
What code r u using and any error in prison console

**Comment by TobyMellor** [comment]
Thanks for replying!
No errors in Prison Console, only bungee.
I'm using player.setResourcePack(URL); which works on a non-bungee server.
I'm also using https://www.spigotmc.org/resources/api-resourcepackapi-1-7-1-8.2397/ in order to get the resourcepack events. I'm not doing anything special other than using this plugin ^.
If anyone has anything they'd like me to try, or if anyone can suggest action I can take that'd be great!
Thanks!
Toby.

**Comment by i9hdkill** [comment]
Please open a new ticket if this issue still persists in the latest version.
