### ISSUE TITLE
java.lang.IllegalStateException: Not expecting PING

### ISSUE THREAD

**Issue by mibby** [SpigotMC/BungeeCord#1544]
BungeeCord dev 1076
Spigot 1.8.7 git-Spigot-b2c2c63-a3cb1bc 

```
05:54:52 [SEVERE] [/IP:PORT] <-> InitialHandler - encountered exception
java.lang.IllegalStateException: Not expecting PING
	at com.google.common.base.Preconditions.checkState(Preconditions.java:173)
	at net.md_5.bungee.connection.InitialHandler.handle(InitialHandler.java:244)
	at net.md_5.bungee.protocol.packet.PingPacket.handle(PingPacket.java:35)
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:76)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:161)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by greatman** [comment]
A client probably sending something Bungee doesn't accept at the current state. Can be safely ignored.

**Comment by MarkLalor** [comment]
Is there an effective way to suppress this output to the console? My console becomes filled with these errors to the point that it detracts from the rest of the info. And I'd rather not block them completely with iptables but I guess it can be a last resort. If it can be safely ignored, it can be safely suppressed, right?

**Comment by Janmm14** [comment]
It might be lowered to a one-line notice but I would never suppress it completely.

**Comment by MarkLalor** [comment]
Good point, I agree. I just don't think it deserves a 30-line stack trace as long as it's not harmful (still essential to show for debugging purposes in case you're actually trying to interact with the server)
