### ISSUE TITLE
java.io.IOException: Too many open files // Before crash bungee

### ISSUE THREAD

**Issue by JamesHooks90** [SpigotMC/BungeeCord#1551]
09:35:49 [SEVERE] Jul 27, 2015 9:35:49 AM io.netty.channel.DefaultChannelPipeline$TailContext exceptionCaught
WARNING: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.io.IOException: Too many open files
	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
	at sun.nio.ch.ServerSocketChannelImpl.accept(Unknown Source)
	at sun.nio.ch.ServerSocketChannelImpl.accept(Unknown Source)
	at io.netty.channel.socket.nio.NioServerSocketChannel.doReadMessages(NioServerSocketChannel.java:135)
	at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:69)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Unknown Source)

**Comment by kamcio96** [comment]
do you have plugin with motd animation?

**Comment by pedroo21** [comment]
You need to increase the max amount of open files or remove AnimMotd.

**Comment by JamesHooks90** [comment]
ServerLustPlusUniversal.jar How I incrase the max amount? @pedroo21 @kamcio96

**Comment by kamcio96** [comment]
It is system limit, plugin should close connection. 
Try use other plugin or create shortest motd with connection closing

**Comment by JamesHooks90** [comment]
I used another Thanks.
