### ISSUE TITLE
io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(3) + length(97) exceeds writerIndex(14): PooledUnsafeDirectByteBuf(ridx: 3, widx: 14, cap: 14)

### ISSUE THREAD

**Issue by JamesHooks90** [SpigotMC/BungeeCord#1556]
Strange bungee error. Help?

11:17:16 [SEVERE] [/81.61.208.101:64296] <-> InitialHandler - encountered exception
io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(3) + length(97) exceeds writerIndex(14): PooledUnsafeDirectByteBuf(ridx: 3, widx: 14, cap: 14)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:161)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.ByteToMessageDecoder.handlerRemoved(ByteToMessageDecoder.java:108)
	at io.netty.channel.DefaultChannelPipeline.callHandlerRemoved0(DefaultChannelPipeline.java:526)
	at io.netty.channel.DefaultChannelPipeline.callHandlerRemoved(DefaultChannelPipeline.java:520)
	at io.netty.channel.DefaultChannelPipeline.remove0(DefaultChannelPipeline.java:350)
	at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:321)
	at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:298)
	at net.md_5.bungee.protocol.LegacyDecoder.decode(LegacyDecoder.java:37)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:247)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:147)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(3) + length(97) exceeds writerIndex(14): PooledUnsafeDirectByteBuf(ridx: 3, widx: 14, cap: 14)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1175)
	at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:676)
	at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:684)
	at net.md_5.bungee.protocol.DefinedPacket.readString(DefinedPacket.java:31)
	at net.md_5.bungee.protocol.packet.Handshake.read(Handshake.java:27)
	at net.md_5.bungee.protocol.DefinedPacket.read(DefinedPacket.java:196)
	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:34)
	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:10)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89)
	... 27 more

**Comment by ninja-** [comment]
seems like a LegacyDecoder bug but harmless, I personally removed LegacyDecoder

**Comment by Janmm14** [comment]
Bungeecord version?

**Comment by i9hdkill** [comment]
Please open a new ticket if this issue still persists in the latest version.
