### ISSUE TITLE
Recently suffer from server crash.

### ISSUE THREAD

**Issue by JHXSMatthew** [SpigotMC/BungeeCord#1568]
Edit 
Finally.. someone found what cause this.
When bc received incomplete data stream , bc did not free those. Those data were stored in directio memory then crash server.
Please take a look and fix this

Original:
Same error occurred a few times while players was trying to enter other spigot servers.
After this, whole  server crashed with 100% CPU usage.  
Current spigot version :1.8.7
Current BC build :Latest
4G RAM was allocated to JVM (BC) .

20:54:24 [SEVERE] [bupei_yonyou] <-> DownstreamBridge <-> [kitbattle] - encountered exception
java.lang.OutOfMemoryError: Direct buffer memory
	at java.nio.Bits.reserveMemory(Unknown Source)
	at java.nio.DirectByteBuffer.<init>(Unknown Source)
	at java.nio.ByteBuffer.allocateDirect(Unknown Source)
	at io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:437)
	at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:179)
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:168)
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:98)
	at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:250)
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:155)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.copy(PooledUnsafeDirectByteBuf.java:320)
	at io.netty.buffer.AbstractByteBuf.copy(AbstractByteBuf.java:919)
	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:24)
	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:10)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:161)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:161)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Unknown Source)

**Comment by JHXSMatthew** [comment]
java.lang.OutOfMemoryError: Direct buffer memory @ io.netty.handler.codec.ByteToMessageDecoder:278

**Comment by PhanaticD** [comment]
you need to allocate more ram then

**Comment by JHXSMatthew** [comment]
Is 4GB ram  not enough for 200 players ?

**Comment by JHXSMatthew** [comment]
btw, I cannot see why 512MB direct memory.is not enough.

**Comment by JHXSMatthew** [comment]
Finally.. someone found what cause this.
When bc received incomplete data stream , bc did not free those. Those data were stored in directio memory then crash server.
Please take a look and fix this.

**Comment by ninja-** [comment]
I don't think so @JHXSMatthew. Please give more details of what you found to be your problem because MinecraftDecoder always releases the buffer no matter what.

**Comment by ninja-** [comment]
@JHXSMatthew ?
