### ISSUE TITLE
Error occurred while connecting to login servers, are they down?

### ISSUE THREAD

**Issue by ACCFfan** [SpigotMC/BungeeCord#1592]
I just got my VPS today for the second time (my old one was deleted because I didn't need it anymore) and when I installed BungeeCord, it took a bit but I got everything working "right". Upon logging in though, it says "Error occurred while connecting to login servers, are they down?" I cannot ping minecraft.net, and the error that it gives me in the console is:

Caused by: java.security.ProviderException: java.security.KeyException
at sun.security.ec.ECKeyPairGenerator.generateKeyPair(ECKeyPairGenerator.java:146)
at java.security.KeyPairGenerator$Delegate.generateKeyPair(KeyPairGenerator.java:704)
at sun.security.ssl.ECDHCrypt.<init>(ECDHCrypt.java:78)
at sun.security.ssl.ClientHandshaker.serverKeyExchange(ClientHandshaker.java:714)
at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:278)
at sun.security.ssl.Handshaker.processLoop(Handshaker.java:913)
at sun.security.ssl.Handshaker$1.run(Handshaker.java:853)
at sun.security.ssl.Handshaker$1.run(Handshaker.java:851)
at java.security.AccessController.doPrivileged(Native Method)
at sun.security.ssl.Handshaker$DelegatedTask.run(Handshaker.java:1285)
at io.netty.handler.ssl.SslHandler.runDelegatedTasks(SslHandler.java:1161)
at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1064)
... 16 more
Caused by: java.security.KeyException
at sun.security.ec.ECKeyPairGenerator.generateECKeyPair(Native Method)
at sun.security.ec.ECKeyPairGenerator.generateKeyPair(ECKeyPairGenerator.java:126)
... 27 more

I thought it may be my provider (MPServ) at fault, but they said "We are not currently having any sort of network/hardware issues at this time." It works if it is in offline mode though, but I am not risking that.

Thanks, ACCFfan.

**Comment by md-5** [comment]
You need to install the java ca-certificates package.
