### ISSUE TITLE
server switch when talking in chat

### ISSUE THREAD

**Issue by random1167** [SpigotMC/BungeeCord#1605]
when i talk in one server it puts me on the other but not the other way around 
2 servers Survive and fun
(talk on survive automatically puts you on fun)
but i can run commands on the server without getting put on server fun.
here is bungees console
09:46:39 [SEVERE] [Narcholas] <-> DownstreamBridge <-> [survive] - encountered exception
io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(0) + length(1) exceeds writerIndex(0): UnpooledUnsafeDirectByteBuf(ridx: 0, widx: 0, cap: 0)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:99)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
    at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:152)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(0) + length(1) exceeds writerIndex(0): UnpooledUnsafeDirectByteBuf(ridx: 0, widx: 0, cap: 0)
    at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1166)
    at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:570)
    at net.md_5.bungee.protocol.DefinedPacket.readVarInt(DefinedPacket.java:111)
    at net.md_5.bungee.protocol.DefinedPacket.readVarInt(DefinedPacket.java:101)
    at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:28)
    at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:10)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89)
    ... 19 more
pastebin.com/FFLDK2XV

**Comment by aikar** [comment]
the ultimate issue is that the connection crashed, and it sent you back to the default server.

I believe theres a bug in the newer bungees, try going back to 

http://ci.md-5.net/job/BungeeCord/1083/artifact/bootstrap/target/BungeeCord.jar

This is the build I use and have not had this issue.

**Comment by random1167** [comment]
11:23:43 [SEVERE] [rex1167] <-> DownstreamBridge <-> [survive] - encountered exception
io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:99)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
    at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:152)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IndexOutOfBoundsException
    at io.netty.buffer.EmptyByteBuf.readByte(EmptyByteBuf.java:440)
    at net.md_5.bungee.protocol.DefinedPacket.readVarInt(DefinedPacket.java:111)
    at net.md_5.bungee.protocol.DefinedPacket.readVarInt(DefinedPacket.java:101)
    at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:28)
    at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:10)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89)
    ... 19 more
11:23:43 [INFO] [rex1167] disconnected with: DecoderException : java.lang.IndexOutOfBoundsException @ io.netty.handler.codec.MessageToMessageDecoder:99
11:23:43 [INFO] [rex1167] disconnected with: [Proxy] Lost connection to server.
11:23:43 [INFO] [rex1167] <-> DownstreamBridge <-> [survive] has disconnected
11:23:44 [INFO] [rex1167] -> UpstreamBridge has disconnected

**Comment by random1167** [comment]
i just dont know what happened,could a plugin NOT on the "bungee server" make the MessageToMessageDecoder error ?..im posting this after testing the bungee plugins and am about to test Spigot's plugins

**Comment by random1167** [comment]
it was chatcontrol paid .......
Going take up the issue with  kangarko 
Sorry for the DRAMA
