### ISSUE TITLE
greload command error

### ISSUE THREAD

**Issue by SirWilli** [SpigotMC/BungeeCord#1642]
I removed and added few server in the bungee config and did run greload but got this error:
```
>greload
05:44:53 [INFO] An internal error occurred whilst executing this command, please check the console log for details.
05:44:53 [WARNING] Error in dispatching command
java.lang.IllegalArgumentException: Server trilogy removed on reload!
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
    at net.md_5.bungee.conf.Configuration.load(Configuration.java:96)
    at net.md_5.bungee.command.CommandReload.execute(CommandReload.java:20)
    at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:162)
    at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:116)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:61)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
```

Is this a bug or is it not intended to be able to reload if a server got removed?

**Comment by md-5** [comment]
Intended
