### ISSUE TITLE
Bungee kicks , server stays at 0 online.

### ISSUE THREAD

**Issue by surgetheurge** [SpigotMC/BungeeCord#1663]
I made an issue before. issue 1625 I think.
Well it's happening again, but now with a much bigger error.
09:07:49 [SEVERE] Error authenticating Taylor443 with minecraft.net
java.net.UnknownHostException: sessionserver.mojang.com
	at java.net.InetAddress.getAllByName0(InetAddress.java:1273)
	at java.net.InetAddress.getAllByName(InetAddress.java:1185)
	at java.net.InetAddress.getAllByName(InetAddress.java:1119)
	at java.net.InetAddress.getByName(InetAddress.java:1069)
	at net.md_5.bungee.http.HttpClient.get(HttpClient.java:65)
	at net.md_5.bungee.connection.InitialHandler.handle(InitialHandler.java:414)
	at net.md_5.bungee.protocol.packet.EncryptionResponse.handle(EncryptionResponse.java:53)
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:76)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:152)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at java.lang.Thread.run(Thread.java:745)

Anyway I had intreppid do an os reinstall, didn't work. Had them make me a new server, 20 minutes ago it happened again, so it didn't work.
Anyway the error is much bigger now, I'm hoping someone could tell me what to do. 
https://i.gyazo.com/1989b7932c50871a7f60c012c3e07416.png
Heres an image of the playercount. You can see when it happens, the player count drops very sharply. Anyway, if nothing can be done code wise, i'm hoping someone could teach me what to say to intrepid to fix this problem. I can't really invest into advertising if my server keeps going offline at high playercounts.

**Comment by md-5** [comment]
Server configuration issue, check your DNS, eg: ping sessionserver.mojang.com

**Comment by surgetheurge** [comment]
Hey.
I can't ping sessionserver.mojang.com from anywhere.

**Comment by Janmm14** [comment]
Then you need to xhange the servers dns settings. Google can help there.

Google the command and maybe use google's dns: 8.8.8.8 / 8.8.4.4
