### ISSUE TITLE
Unknown login cancellation error

### ISSUE THREAD

**Issue by Fishy246** [SpigotMC/BungeeCord#1680]
To keep this brief,
I am making a bungeecord bans system that incorporates a mysql database to store the ban information, when a player joins I run a query to find out whether the player is in the bans table and if they are then retrieve the ban reason and disconnect them with the reason and relevant information. However I have tried a few login methods eg.. PostLogin PreLogin Login and they have all had the same effect of producing a stacktrace which seems to be down to bungeecord and not to me.
##### The Method
```java
    @EventHandler
    void onJoin(PreLoginEvent e) {
        ProxiedPlayer p = (ProxiedPlayer) e.getConnection();
        if (user.isBanned(p)) try {
            PreparedStatement query = Core.getInstance().c.prepareStatement("SELECT id, reason, date, bannedby FROM `Bans` WHERE uuid='" + p.getUniqueId() + "'");
            ResultSet set = query.executeQuery();

            e.setCancelled(true);
            e.setCancelReason(chat.prefix+"You Have Been Banned\n&cFor: "+set.getString("reason"));
            return;
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
```
##### The Stacktrace
```
21:23:58 [SEVERE] [Fishy246] <-> InitialHandler - encountered exception
java.lang.Error: Method became inaccessible: PreLoginEvent(cancelled=false, cancelReason=null, connection=[Fishy246] <-> InitialHandler)
    at net.md_5.bungee.event.EventBus.post(EventBus.java:49)
    at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:374)
    at net.md_5.bungee.connection.InitialHandler.handle(InitialHandler.java:362)
    at net.md_5.bungee.protocol.packet.LoginRequest.handle(LoginRequest.java:39)
    at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:76)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
    at io.netty.handler.codec.ByteToMessageDecoder.handlerRemoved(ByteToMessageDecoder.java:203)
    at io.netty.channel.DefaultChannelPipeline.callHandlerRemoved0(DefaultChannelPipeline.java:527)
    at io.netty.channel.DefaultChannelPipeline.callHandlerRemoved(DefaultChannelPipeline.java:521)
    at io.netty.channel.DefaultChannelPipeline.remove0(DefaultChannelPipeline.java:351)
    at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:322)
    at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:299)
    at net.md_5.bungee.protocol.LegacyDecoder.decode(LegacyDecoder.java:37)
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:327)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:230)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
    at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:152)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalAccessException: Class net.md_5.bungee.event.EventHandlerMethod can not access a member of class co.inferna.proxy.events.Join with modifiers ""
    at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:102)
    at java.lang.reflect.AccessibleObject.slowCheckMemberAccess(AccessibleObject.java:296)
    at java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:288)
    at java.lang.reflect.Method.invoke(Method.java:490)
    at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
    at net.md_5.bungee.event.EventBus.post(EventBus.java:46)
    ... 34 more

```

**Comment by ninja-** [comment]
you missed the 'public' before your method

**Comment by Fishy246** [comment]
@ninja- The public modifier makes no difference to the outcome

**Comment by kamcio96** [comment]
ProxiedPlayer p = (ProxiedPlayer) e.getConnection();
also will thrown an exception (ClassCastException)

**Comment by Black-Hole** [comment]
As stated in the Java error message, your class co.inferna.proxy.events.Join is not accessible from other packages. So use the public modifier for your class.

**Comment by Fishy246** [comment]
@Black-Hole Umm thats odd, because the Join class is most definitely public :/

**Comment by xxyy** [comment]
PreLoginEvent's getConnection() does not return ProxiedPlayer, but InitialHandler, as you can see in the stack trace. This is not the main issue. 

The error message clearly says that the event bus cannot access _some_ event handler method in your Join class - for test purposes, change all the things there to public and see if the error still occurs, especially check the part where it says "cannot access ... with modifiers". That one should say public then, or you might be facing an issue with your build system. If that works, change them back to the proper access modifiers one by one.

**Comment by szungy** [comment]
I have created a system for the very same goal recently so I'll try to explain my solution and point out a few things, hoping that it will be helpful. I used the LoginEvent for the main checks but I don't see any reason why PreLogin or PostLogin would not work.
As @xxyy stated, you don't have a ProxiedPlayer during the PreLoginEvent or LoginEvent because the connection is not fully ready just yet. Keep in mind though, that you can already get the IP address and the desired username for that connection:
For instance, if your LoginEvent object's name is a_Event you can do the following
```
InetAddress ConnectionAddress = a_Event.getConnection().getAddress().getAddress();
String IP = ConnectionAddress.getHostAddress();
```
or
```
String PlayerName = a_Event.getConnection().getName();
```
Then you can perform your checks on the data. Be a bit more careful with SQL queries, like the one that you have there because they might open up SQL injection vulnerabilities. It is no problem in that case because the UUID is not arbitrarily spoofable by the user (as far as I know) but concatenating strings into SQL queries is generally considered a bad practice. That is exactly why prepared statements are there, to protect you from SQL injection and to help with query building.
Here is an example for building a proper prepared statement:
```
PreparedStatement goldSql = connection.prepareStatement("UPDATE `coins` SET gold=? WHERE uuid=?;");
goldSql.setInt(1, gold);
goldSql.setString(2, player.getUniqueId().toString());
goldSql.executeUpdate();
goldSql.close();
```
You can use the same syntax for a select or any other query.

The second main problem that is worth addressing is that if you start mysql queries during events then that event will have to wait for the query to complete. This is not such a big problem if your server is stable and responds quickly but it can cause some lag as far as I understand it. Here is how I try to solve the problem in my plugin:
( I'm checking for open proxies and vpns and tor exit nodes in my plugin using a few public APIs and other methods. )
This code is right after the initial checks in the LoginEvent:

```
_Plugin.getProxy().getScheduler().runAsync(_Plugin, new Runnable()
{
    @Override
    public void run()
    {
        InspectionTask(a_Event, PlayerName, IP);
    }
});
```

and then in the InspectionTask function

```
if (IsProxyOrTorExitNode(a_IP))
{
    a_Event.setCancelReason(NoTorOrProxyMsg);
    a_Event.setCancelled(true);

    // The connection might have been made because the async task migh have took longer (HTTP Queries in the background)
    ProxiedPlayer PlayerObject = _Plugin.getProxy().getPlayer(a_Username);

    if (PlayerObject != null)
        PlayerObject.disconnect(NoTorOrProxyMsg);
}
```

You can do the very same thing but instead of calling IsProxyOrTorExitNode() just do your checks in the ban database.
Caching the ban entries and reloading them every once in a while (depending on your needs) is also a good idea because you don't stress your mysql server as much.

Just a last note: I don't think there is anything wrong with Bungee's event system so this is not a bungee issue. As you can see, the first line in the stack trace ( at net.md_5.bungee.event.EventBus.post(EventBus.java:49) ) indicates that the EventBus has a problem posting the event to your registered handler.
