### ISSUE TITLE
IndexOutOfBoundsException

### ISSUE THREAD

**Issue by mineyannik** [SpigotMC/BungeeCord#1714]
When I use the minecraft client 1.8.6 and connect to a server and start sprinting I get kicked.

This is the error:
```
08:45:17 [SEVERE] [TimPlayzUHC] -> UpstreamBridge - encountered exception
java.lang.IndexOutOfBoundsException: writerIndex(4) + minWritableBytes(2) exceeds maxCapacity(5): SlicedAbstractByteBuf(ridx: 1, widx: 4, cap: 5/5, unwrapped: PooledUnsafeDirectByteBuf(ridx: 7, widx: 43, cap: 43))
    at io.netty.buffer.AbstractByteBuf.ensureWritable0(AbstractByteBuf.java:259)
    at io.netty.buffer.AbstractByteBuf.ensureWritable(AbstractByteBuf.java:249)
    at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:866)
    at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:858)
    at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:848)
    at net.md_5.bungee.entitymap.EntityMap.rewriteVarInt(EntityMap.java:95)
    at net.md_5.bungee.entitymap.EntityMap.rewrite(EntityMap.java:112)
    at net.md_5.bungee.entitymap.EntityMap.rewriteServerbound(EntityMap.java:63)
    at net.md_5.bungee.entitymap.EntityMap_1_8.rewriteServerbound(EntityMap_1_8.java:160)
    at net.md_5.bungee.connection.UpstreamBridge.handle(UpstreamBridge.java:89)
    at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:84)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:276)
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:354)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:152)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:823)
    at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:339)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:255)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
    at java.lang.Thread.run(Thread.java:745)
08:45:17 [INFO] [TimPlayzUHC] disconnected with: IndexOutOfBoundsException : writerIndex(4) + minWritableBytes(2) exceeds maxCapacity(5): SlicedAbstractByteBuf(ridx: 1, widx: 4, cap: 5/5, unwrapped: PooledUnsafeDirectByteBuf(ridx: 7, widx: 43, cap: 43)) @ io.netty.buffer.AbstractByteBuf:259
08:45:17 [INFO] [TimPlayzUHC] -> UpstreamBridge has disconnected
08:45:17 [INFO] [TimPlayzUHC] disconnected with: [Proxy] Lost connection to server.
```

**Comment by mineyannik** [comment]
The bug is only in the last version from yesterday.

**Comment by md-5** [comment]
Reproduced
