### ISSUE TITLE
D/C Issue

### ISSUE THREAD

**Issue by NaomiTim** [SpigotMC/BungeeCord#1724]
Okay so I thought this issue was only when I had enchanted items in my inventory but it turns out I get kicked with the following message everytime I open my inventory. I also tried the other thing from #1717 But that didn't work for me

My start.sh file
```
while true; do
  java -Xms512m -Xmx512m -XX:MaxPermSize=128m -jar bungee.jar
  echo "#######################################################"
  echo "###         AmestrisRealms Management -NaomiTim     ###"
  echo "#######################################################"
  echo "###        Restarting the server in 5 seconds       ###"
  echo "#######################################################"
  sleep 5
  echo "#######################################################"
  echo "###         AmestrisRealms Management -NaomiTim     ###"
  echo "#######################################################"
  echo "###         Launching the server, please wait.      ###"
  echo "#######################################################"
done
```
```

06:36:07 [SEVERE] [YouthInRevolt] <-> DownstreamBridge <-> [Survival] - encountered exception
io.netty.handler.codec.EncoderException: java.lang.UnsupportedOperationException
    at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
    at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:643)
    at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:700)
    at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:636)
    at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
    at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:643)
    at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:700)
    at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:636)
    at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:944)
    at io.netty.channel.AbstractChannel.write(AbstractChannel.java:239)
    at net.md_5.bungee.netty.ChannelWrapper.write(ChannelWrapper.java:46)
    at net.md_5.bungee.connection.UpstreamBridge.handle(UpstreamBridge.java:92)
    at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:84)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:276)
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:354)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:152)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:823)
    at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:339)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:255)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.UnsupportedOperationException
    at io.netty.buffer.PooledHeapByteBuf.memoryAddress(PooledHeapByteBuf.java:262)
    at net.md_5.bungee.jni.zlib.NativeZlib.process(NativeZlib.java:43)
    at net.md_5.bungee.compress.PacketCompressor.encode(PacketCompressor.java:42)
    at net.md_5.bungee.compress.PacketCompressor.encode(PacketCompressor.java:11)
    at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
    ... 40 more
06:36:07 [INFO] [YouthInRevolt] disconnected with: EncoderException : java.lang.UnsupportedOperationException @ io.netty.handler.codec.MessageToByteEncoder:125
06:36:07 [INFO] [YouthInRevolt] disconnected with: [Proxy] Lost connection to server.
```

**Comment by md-5** [comment]
https://github.com/SpigotMC/BungeeCord/issues/1717
