### ISSUE TITLE
Problem with BungeeCord

### ISSUE THREAD

**Issue by ProMiner10000** [SpigotMC/BungeeCord#1737]
Everything is fine but when I connect to the server I get "Exception Connecting:RuntimeException : Server is online mode! @ net.md_5.bungee.ServerConnector:261" but if I change to online mode, it'll say that I'm already connected. What exactly do I put  to be online and offline? In the BungeeCord configuration I have it set as true I have everything else set as false. There are three worlds, Factions, SimplePVP and Spawn. When they connect to the server, they go to the Spawn Server, but with a compass they can go to Factions and SimplePVP.  What worlds do I set as what mode?

**Comment by Phoenix616** [comment]
You have to put your Spigot servers behind the BungeeCord proxy into offline mode for it to work. 

Enable ip-forward in your bungee's config.yml and bungeecord in your spigot.yml(s) if you want online-mode UUIDs and real IPs on your Minecraft servers.

**Comment by ProMiner10000** [comment]
Not sure what you mean by that but do you mind if I just post a pastebin with all the configurations? And you can just tell me what to change?

**Comment by ProMiner10000** [comment]
http://pastebin.com/gCLp3fNH - BungeeCord Configuration
http://pastebin.com/HmhQzcRs - Server properties for Spawn
http://pastebin.com/epDT00QP - Server properties for SimplePVP
http://pastebin.com/qF8vPgSk - Server properties for Factions

Basically all I want is when they log in, they go to the server called Spawn which contains the Spawn and from there they can use a compass to teleport to SimplePVP and Factions. Also I have enabled IP-forwarding in the bungeecord config.

**Comment by kamcio96** [comment]
Just set ```online-mode=true``` to false

**Comment by ProMiner10000** [comment]
Everything else is fine other than that?

**Comment by ProMiner10000** [comment]
16:30:16 [INFO] Using standard Java JCE cipher. To enable the OpenSSL based native cipher, please make sure you are using 64 bit Ubuntu or Debian with libssl installed.
16:30:16 [INFO] Using standard Java compressor. To enable zero copy compression, run on 64 bit Linux
16:30:16 [INFO] Enabled BungeeCord version git:BungeeCord-Bootstrap:1.8-SNAPSHOT:848cad2:1116
16:30:17 [INFO] Discovered module: ModuleSpec(name=cmd_alert, file=modules\cmd_alert.jar, provider=JenkinsModuleSource())
16:30:17 [INFO] Discovered module: ModuleSpec(name=cmd_find, file=modules\cmd_find.jar, provider=JenkinsModuleSource())
16:30:17 [INFO] Discovered module: ModuleSpec(name=cmd_list, file=modules\cmd_list.jar, provider=JenkinsModuleSource())
16:30:17 [INFO] Discovered module: ModuleSpec(name=cmd_send, file=modules\cmd_send.jar, provider=JenkinsModuleSource())
16:30:17 [INFO] Discovered module: ModuleSpec(name=cmd_server, file=modules\cmd_server.jar, provider=JenkinsModuleSource())
16:30:17 [INFO] Discovered module: ModuleSpec(name=reconnect_yaml, file=modules\reconnect_yaml.jar, provider=JenkinsModuleSource())
16:30:17 [INFO] Loaded plugin reconnect_yaml version git:reconnect_yaml:1.8-SNAPSHOT:848cad2:1116 by SpigotMC
16:30:17 [INFO] Loaded plugin cmd_find version git:cmd_find:1.8-SNAPSHOT:848cad2:1116 by SpigotMC
16:30:17 [INFO] Loaded plugin cmd_server version git:cmd_server:1.8-SNAPSHOT:848cad2:1116 by SpigotMC
16:30:17 [INFO] Loaded plugin cmd_alert version git:cmd_alert:1.8-SNAPSHOT:848cad2:1116 by SpigotMC
16:30:17 [INFO] Loaded plugin cmd_send version git:cmd_send:1.8-SNAPSHOT:848cad2:1116 by SpigotMC
16:30:17 [INFO] Loaded plugin cmd_list version git:cmd_list:1.8-SNAPSHOT:848cad2:1116 by SpigotMC
16:30:17 [INFO] Enabled plugin reconnect_yaml version git:reconnect_yaml:1.8-SNAPSHOT:848cad2:1116 by SpigotMC
16:30:17 [INFO] Enabled plugin cmd_find version git:cmd_find:1.8-SNAPSHOT:848cad2:1116 by SpigotMC
16:30:17 [INFO] Enabled plugin cmd_server version git:cmd_server:1.8-SNAPSHOT:848cad2:1116 by SpigotMC
16:30:17 [INFO] Enabled plugin cmd_alert version git:cmd_alert:1.8-SNAPSHOT:848cad2:1116 by SpigotMC
16:30:17 [INFO] Enabled plugin cmd_send version git:cmd_send:1.8-SNAPSHOT:848cad2:1116 by SpigotMC
16:30:17 [INFO] Enabled plugin cmd_list version git:cmd_list:1.8-SNAPSHOT:848cad2:1116 by SpigotMC
16:30:17 [INFO] Listening on /0.0.0.0:25565
16:30:20 [SEVERE] Netty is not using direct IO buffers.
16:30:20 [INFO] [ProMiner10000] <-> InitialHandler has connected
16:30:22 [INFO] [ProMiner10000] <-> ServerConnector [lobby] has connected
16:30:22 [INFO] [ProMiner10000] <-> InitialHandler has connected
16:30:22 [SEVERE] [ProMiner10000] <-> ServerConnector [lobby] - encountered exception
java.lang.RuntimeException: Server is online mode!
    at net.md_5.bungee.ServerConnector.handle(ServerConnector.java:261)
    at net.md_5.bungee.protocol.packet.EncryptionRequest.handle(EncryptionRequest.java:56)
    at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:76)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:276)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:263)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:152)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
    at java.lang.Thread.run(Unknown Source)
16:30:22 [INFO] [ProMiner10000] disconnected with: Exception Connecting:RuntimeException : Server is online mode! @ net.md_5.bungee.ServerConnector:261
16:30:22 [INFO] [ProMiner10000] <-> ServerConnector [lobby] has disconnected
16:30:22 [INFO] [ProMiner10000] -> UpstreamBridge has disconnected
>

When I set the online mode's to true I get that error above. Above is my entire console thing.

**Comment by minecrafter** [comment]
Set it to false.

**Comment by ProMiner10000** [comment]
When I do that it says that I'm already connected. And it just kicks me.

**Comment by BoomBoomLHack** [comment]
@ProMiner10000 
Set your Bungee to online mode and enable IP forwarding.
Set your backend servers (Lobby, etc.) to offline mode.

**Comment by ProMiner10000** [comment]
I tried that I enabled IP forwarding and I set the backend servers to offline mode. I get this error 18:41:25 [SEVERE] [ProMiner10000] <-> ServerConnector [lobby] - encountered exception
java.lang.RuntimeException: Server is online mode!
    at net.md_5.bungee.ServerConnector.handle(ServerConnector.java:261)
    at net.md_5.bungee.protocol.packet.EncryptionRequest.handle(EncryptionRequest.java:56)
    at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:76)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:276)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:263)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:152)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
    at java.lang.Thread.run(Unknown Source)
18:41:25 [INFO] [ProMiner10000] disconnected with: Exception Connecting:RuntimeException : Server is online mode! @ net.md_5.bungee.ServerConnector:261
18:41:25 [INFO] [ProMiner10000] <-> ServerConnector [lobby] has disconnected
18:41:25 [INFO] [ProMiner10000] -> UpstreamBridge has disconnected
>


And when I connect it says Exception Connecting:RuntimeException : Server is online mode! @ net.md_5.bungee.ServerConnector:261

**Comment by kamcio96** [comment]
You have loop in config, default minecraft port should be used only by BungeeCord

**Comment by ProMiner10000** [comment]
What about my Spawn? The default server they connect to? Offline or Online? Also, what do you mean don't host them in one box?

**Comment by ProMiner10000** [comment]
Oh, so what do I do?

**Comment by kamcio96** [comment]
All server have to have offline mode. Always!! 
BungeeCord has default mc port, and servers have other parts

**Comment by ProMiner10000** [comment]
Ok, sorry but I'm a bit confused. Do you mind using the bungeecord pastebin and posting another pastebin with an updated version of the config and edit it to your liking so it works?

**Comment by ProMiner10000** [comment]
Thanks to those that tried to help! I finally figured out a conclusion, I changed the port of my spawn and that worked. Thanks!

**Comment by Janmm14** [comment]
@BoomBoomLHack One box can handle multiple minecraft servers. It depends on the box. The general statement from you is wrong.
