### ISSUE TITLE
io.netty.handler.codec.CorruptedFrameException: Empty Packet!

### ISSUE THREAD

**Issue by L4BORG** [SpigotMC/BungeeCord#1739]
```
21:02:39 [SEVERE] [/xxx.xxx.xxx.xx:52552] <-> InitialHandler - encountered exception
io.netty.handler.codec.CorruptedFrameException: Empty Packet!
    at net.md_5.bungee.protocol.Varint21FrameDecoder.decode(Varint21FrameDecoder.java:36)
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:360)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.handler.codec.ByteToMessageDecoder.handlerRemoved(ByteToMessageDecoder.java:216)
    at io.netty.channel.DefaultChannelPipeline.callHandlerRemoved0(DefaultChannelPipeline.java:527)
    at io.netty.channel.DefaultChannelPipeline.callHandlerRemoved(DefaultChannelPipeline.java:521)
    at io.netty.channel.DefaultChannelPipeline.remove0(DefaultChannelPipeline.java:351)
    at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:322)
    at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:299)
    at net.md_5.bungee.protocol.LegacyDecoder.decode(LegacyDecoder.java:37)
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:360)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:152)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:823)
    at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:339)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:255)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
    at java.lang.Thread.run(Thread.java:745)
```

*always* followed by...

```
21:02:39 [WARNING] [/xxx.xxx.xxx.xx:52559] <-> InitialHandler - bad packet ID, are mods in use!? Did not read all bytes from packet class net.md_5.bungee.protocol.packet.Handshake 0 Protocol HANDSHAKE Direction net.md_5.bungee.protocol.Protocol$DirectionData@5102e112
```

```
>bungee
21:07:07 [INFO] CONSOLE executed command: /bungee
21:07:07 [INFO] This server is running BungeeCord version git:BungeeCord-Bootstrap:1.8-SNAPSHOT:848cad2:1116 by md_5
```

```
root@brick:~# java -version
java version "1.8.0_71"
Java(TM) SE Runtime Environment (build 1.8.0_71-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.71-b15, mixed mode)
```

**Comment by md-5** [comment]
You are using a broken server.
Please ensure you are running Spigot / Vanilla 1.8.8
