### ISSUE TITLE
Error on bot attack

### ISSUE THREAD

**Issue by Dimatert9** [SpigotMC/BungeeCord#1781]
about 40bots/sec

14:17:27 [SEVERE] [PlaysPlaysYT] -> UpstreamBridge - encountered exception
io.netty.handler.codec.DecoderException: net.md_5.bungee.jni.NativeCodeException: Unknown z_stream return code : -3
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:276)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:263)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:152)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:823)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:339)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:255)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at java.lang.Thread.run(Thread.java:745)
Caused by: net.md_5.bungee.jni.NativeCodeException: Unknown z_stream return code : -3
	at net.md_5.bungee.jni.zlib.NativeCompressImpl.process(Native Method)
	at net.md_5.bungee.jni.zlib.NativeZlib.process(NativeZlib.java:51)
	at net.md_5.bungee.compress.PacketDecompressor.decode(PacketDecompressor.java:42)
	at net.md_5.bungee.compress.PacketDecompressor.decode(PacketDecompressor.java:11)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89)
	... 15 more

**Comment by Master-chan** [comment]
Are you running with online_mode=true?

**Comment by Dimatert9** [comment]
=false

**Comment by i9hdkill** [comment]
Please open a new ticket if this issue still persists in the latest version.
