### ISSUE TITLE
Error while connecting to spigot server

### ISSUE THREAD

**Issue by JHXSMatthew** [SpigotMC/BungeeCord#1833]
Hi,
I got this kind of issue while connecting to one of my spigot server using 1.9 client.
I could directly connect to that server without BungeeCord , but I cannot while I using BungeeCord as proxy.

I believe this is an issue with Chunk packet.
The server is running 1.8.8 spigot using ViaVersion and my "Orebfuscator" plugins.

The player may connect to that server using BungeeCord proxy when I do not use the "Orebfuscator".
For Orebfuscator, It's just normal algorithm and normal way like Orebfuscator on bukkit, and ViaVersion translates that chunk packet to 1.9. 

Cheers.

Errors and ViaVersion

ViaVersion: https://www.spigotmc.org/resources/viaversion.19254/

Error:

[****] <-> DownstreamBridge <-> [THE_SERVER] - encountered exception
io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(0) + length(1) exceeds writerIndex(0): SlicedAbstractByteBuf(ridx: 0, widx: 0, cap: 0/0, unwrapped: PooledUnsafeDirectByteBuf(ridx: 8918, widx: 8924, cap: 16384))
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:99)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:276)
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:354)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:152)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:823)
    at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:339)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:255)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(0) + length(1) exceeds writerIndex(0): SlicedAbstractByteBuf(ridx: 0, widx: 0, cap: 0/0, unwrapped: PooledUnsafeDirectByteBuf(ridx: 8918, widx: 8924, cap: 16384))
    at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1178)
    at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:587)
    at net.md_5.bungee.protocol.DefinedPacket.readVarInt(DefinedPacket.java:89)
    at net.md_5.bungee.protocol.DefinedPacket.readVarInt(DefinedPacket.java:79)
    at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:28)
    at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:10)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89)
    ... 19 more

**Comment by ReaperAngels** [comment]
Had that problem. Close the terminal completely, start a new one. Problem goes away. I don't know how or why, but that's how I fixed the error. If that doesn't work, do a full reboot of the hosting server. Even if it's linux.

**Comment by Janmm14** [comment]
You do not need to use Orebfuscator with Spigot 1.8.8, as spigot has it built-in. Check options in spigot.yml

Closing and starting a new terminal CAN'T fix the issue. As a reboot can't.

Please show your max-chunk-bulk setting (I believe its in spigot.yml)

**Comment by JHXSMatthew** [comment]
@Janmm14 
You are right, close terminal/reboot does not work since I have tested this on a few system/machines.

Sadly,  spigot 1.8.8's build-in version does not work with ViaVersion, i.e. 1.9 version's player still could use X-ray.

max-chunk-bulk setting 
    max-bulk-chunks: 10

**Comment by JHXSMatthew** [comment]
bump

**Comment by Janmm14** [comment]
The issue occurrs here: https://github.com/SpigotMC/BungeeCord/blob/master/protocol/src/main/java/net/md_5/bungee/protocol/MinecraftDecoder.java#L28
That means that we could not read the packet id because the packet has no content.
That means we have to look earlier in the pipeline and ignore empty packets there.

**Comment by i9hdkill** [comment]
Still an issue with the latest Version of spigot, bungee and viaversion?
