### ISSUE TITLE
 Error authenticating

### ISSUE THREAD

**Issue by GoNotCougsWA** [SpigotMC/BungeeCord#1850]
When I join I get this:
Error authenticating <User> with minecraft.net
java.nio.channels.ClosedChannelException

I try see if the minecraft.net service is healthy. and is it
ERROR:
12:36:27 [INFO] [<IP>] <-> InitialHandler has connected
12:36:28 [SEVERE] May 01, 2016 12:36:28 PM io.netty.channel.ChannelInitializer exceptionCaught
WARNING: Failed to initialize a channel. Closing: [id: 0x11c51b6d]
java.lang.NoClassDefFoundError: Could not initialize class java.net.IDN
    at javax.net.ssl.SNIHostName.<init>(Unknown Source)
    at sun.security.ssl.Utilities.rawToSNIHostName(Unknown Source)
    at sun.security.ssl.Utilities.addToSNIServerNameList(Unknown Source)
    at sun.security.ssl.SSLEngineImpl.init(Unknown Source)
    at sun.security.ssl.SSLEngineImpl.<init>(Unknown Source)
    at sun.security.ssl.SSLContextImpl.engineCreateSSLEngine(Unknown Source)
    at javax.net.ssl.SSLContext.createSSLEngine(Unknown Source)
    at io.netty.handler.ssl.JdkSslContext.newEngine(JdkSslContext.java:192)
    at net.md_5.bungee.http.HttpInitializer.initChannel(HttpInitializer.java:29)
    at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:68)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:143)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:129)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRegistered(DefaultChannelPipeline.java:733)
    at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:450)
    at io.netty.channel.AbstractChannel$AbstractUnsafe.register(AbstractChannel.java:418)
    at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:60)
    at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:48)
    at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:315)
    at io.netty.bootstrap.Bootstrap.doConnect(Bootstrap.java:134)
    at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:90)
    at net.md_5.bungee.http.HttpClient.get(HttpClient.java:95)
    at net.md_5.bungee.connection.InitialHandler.handle(InitialHandler.java:427)
    at net.md_5.bungee.protocol.packet.EncryptionResponse.handle(EncryptionResponse.java:39)
    at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:76)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:276)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:263)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:152)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
    at java.lang.Thread.run(Unknown Source)

**Comment by Janmm14** [comment]
Sounds like a corrupt java installation. Try to reinstall java.

**Comment by GoNotCougsWA** [comment]
Thanks It wa

**Comment by GoNotCougsWA** [comment]
It was corrupt Java installation. Thanks!

How come the Java installation corrupt?

**Comment by i9hdkill** [comment]
Usually that's not possible.
Clsoing this as the issue is fixed.
