### ISSUE TITLE
ConnectionThrottle throws NullPointerException

### ISSUE THREAD

**Issue by scholzi100** [SpigotMC/BungeeCord#1866]
### Description

Since commit _d9a8311b8e40a0d390a993e409933f8ee737c12e_ every player gets kicked because of a _NullPointerException_ caused by _ConnectionThrottle.java:24_.
It is also not passing Unit test, so this is a stupid *fail* too (else I´m stupid, never mind).

### Solutions

- Use previous Implementation 
- Just check if _isThrottled_ is not null (need to be _Boolean_)

### Stacktrace
```
15.05.2016 07:31:40.617 [SEVERE] [/80.72.xxx.xxx:53250] <-> InitialHandler - encountered exception
java.lang.NullPointerException
	at net.md_5.bungee.ConnectionThrottle.throttle(ConnectionThrottle.java:24)
	at net.md_5.bungee.connection.InitialHandler.handle(InitialHandler.java:305)
	at net.md_5.bungee.protocol.packet.Handshake.handle(Handshake.java:44)
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:77)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:276)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:354)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
	at io.netty.handler.codec.ByteToMessageDecoder.handlerRemoved(ByteToMessageDecoder.java:216)
	at io.netty.channel.DefaultChannelPipeline.callHandlerRemoved0(DefaultChannelPipeline.java:527)
	at io.netty.channel.DefaultChannelPipeline.callHandlerRemoved(DefaultChannelPipeline.java:521)
	at io.netty.channel.DefaultChannelPipeline.remove0(DefaultChannelPipeline.java:351)
	at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:322)
	at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:299)
	at net.md_5.bungee.protocol.LegacyDecoder.decode(LegacyDecoder.java:37)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:360)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:152)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:823)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:339)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:255)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by scholzi100** [comment]
Thx!
