### ISSUE TITLE
Impossible de se connecter // Failed to connect ! 

### ISSUE THREAD

**Issue by Darkstream520** [SpigotMC/BungeeCord#1895]
Hello, when a player try to connect on my server he have this screen: 
![2016-06-22 2](https://cloud.githubusercontent.com/assets/20097618/16281755/0b32c4f8-38c6-11e6-81df-a2a1268c1fa2.png)
and this in the console of Bungee server : 
`21:55:51 [GRAVE] juin 22, 2016 9:55:51 PM io.netty.channel.ChannelInitializer exceptionCaught

AVERTISSEMENT: Failed to initialize a channel. Closing: [id: 0xc90c4912, /81.250.76.92:58395 => /5.39.71.211:25565]

java.lang.NoSuchMethodError: net.md_5.bungee.connection.InitialHandler.<init>(Lnet/md_5/bungee/api/ProxyServer;Lnet/md_5/bungee/api/config/ListenerInfo;)V

    at com.w67clement.advancedmotd.bungee.motd.ConnectionReplacement.initChannel(ConnectionReplacement.java:51)

    at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:68)

    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:143)

    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:129)

    at io.netty.channel.DefaultChannelPipeline.fireChannelRegistered(DefaultChannelPipeline.java:733)

    at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:450)

    at io.netty.channel.AbstractChannel$AbstractUnsafe.access$100(AbstractChannel.java:378)

    at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:424)

    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:358)

    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:259)

    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)

    at java.lang.Thread.run(Thread.java:745)

[m>[2K
21:55:51 [GRAVE] juin 22, 2016 9:55:51 PM io.netty.channel.ChannelInitializer exceptionCaught

AVERTISSEMENT: Failed to initialize a channel. Closing: [id: 0xd1fc2588, /81.250.76.92:58397 => /5.39.71.211:25565]

java.lang.NoSuchMethodError: net.md_5.bungee.connection.InitialHandler.<init>(Lnet/md_5/bungee/api/ProxyServer;Lnet/md_5/bungee/api/config/ListenerInfo;)V

    at com.w67clement.advancedmotd.bungee.motd.ConnectionReplacement.initChannel(ConnectionReplacement.java:51)

    at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:68)

    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:143)

    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:129)

    at io.netty.channel.DefaultChannelPipeline.fireChannelRegistered(DefaultChannelPipeline.java:733)

    at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:450)

    at io.netty.channel.AbstractChannel$AbstractUnsafe.access$100(AbstractChannel.java:378)

    at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:424)

    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:358)

    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:259)

    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)

    at java.lang.Thread.run(Thread.java:745)

[m>[2K
22:01:14 [GRAVE] juin 22, 2016 10:01:14 PM io.netty.channel.DefaultChannelPipeline$TailContext exceptionCaught

AVERTISSEMENT: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.

java.lang.IllegalStateException: No session!

    at net.md_5.bungee.query.QueryHandler.channelRead0(QueryHandler.java:82)

    at net.md_5.bungee.query.QueryHandler.channelRead0(QueryHandler.java:20)

    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)

    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)

    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)

    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)

    at io.netty.channel.epoll.EpollDatagramChannel$EpollDatagramChannelUnsafe.epollInReady(EpollDatagramChannel.java:594)

    at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:339)

    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:255)

    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)

    at java.lang.Thread.run(Thread.java:745)
`
I am verry embarrased with that, help me please. Sorry for errors , I am french

**Comment by kamcio96** [comment]
Plugin bug, report it to author

**Comment by Darkstream520** [comment]
which plugin kamcio?

**Comment by kamcio96** [comment]
advancedmotd

**Comment by Darkstream520** [comment]
ok :/

**Comment by Darkstream520** [comment]
and for that? : 
`[m>[2K
22:39:07 [AVERTISSEMENT] Error pinging remote server

java.net.ConnectException: finishConnect() failed: Connexion refusée: /0.0.0.0:25575

    at io.netty.channel.unix.Errors.newConnectException(Errors.java:95)

    at io.netty.channel.unix.Socket.finishConnect(Socket.java:175)

    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.doFinishConnect(AbstractEpollStreamChannel.java:758)

    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.finishConnect(AbstractEpollStreamChannel.java:725)

    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollOutReady(AbstractEpollStreamChannel.java:748)

    at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:329)

    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:255)

    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)

    at java.lang.Thread.run(Thread.java:745)

[m>`

**Comment by Janmm14** [comment]
@Darkstream520 There was no spigot server running on port 25575. The error is also likely by the same plugin.

**Comment by i9hdkill** [comment]
Not a bungee issue.
If you need further help, create a thread in the forums:
https://www.spigotmc.org/forums/bungeecord-help.70/
