### ISSUE TITLE
BungeeCord b#1158 - Ghost players, errors on shutdown...

### ISSUE THREAD

**Issue by L4BORG** [SpigotMC/BungeeCord#1897]
So, we were restarting our BungeeCord server again becuase we had issues with "ghost players" - players that were online only on BungeeCord server.

Those players had valid "ProxifiedPlayer" data (including server) but were not actually connected to the network and were not online on spigot instances. If one of those players actually tried to connect he would get disconnected with message: "you're already connected to this proxy".

We're running single BungeeCord, this happend on build 1158. The players also reported that they were unable to connected after "lagging out".

Tho there is one more thing, after executing /end on our BungeeCord server I saw a lot of these (killed Bungee after 2 minutes since it was just printing the same Ex again and again and we were offline...):

```
13:29:22 [SEVERE] Jun 23, 2016 1:29:22 PM io.netty.channel.AbstractChannel$AbstractUnsafe register
WARNING: Force-closing a channel whose registration task was not accepted by an event loop: [id: 0xbd7295ab]
java.util.concurrent.RejectedExecutionException: event executor terminated
    at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:715)
    at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:300)
    at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:691)
    at io.netty.channel.AbstractChannel$AbstractUnsafe.register(AbstractChannel.java:421)
    at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:60)
    at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:48)
    at io.netty.channel.MultithreadEventLoopGroup.register(MultithreadEventLoopGroup.java:64)
    at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:315)
    at io.netty.bootstrap.Bootstrap.doConnect(Bootstrap.java:134)
    at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:90)
    at net.md_5.bungee.BungeeServerInfo.ping(BungeeServerInfo.java:143)
    at net.md_5.bungee.BungeeServerInfo.ping(BungeeServerInfo.java:122)
    at usermanager.bungee.TaskServerChecker.run(TaskServerChecker.java:25)
    at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)


13:29:22 [SEVERE] Jun 23, 2016 1:29:22 PM io.netty.channel.AbstractChannel$AbstractUnsafe closeForcibly
WARNING: Failed to close a channel.
io.netty.channel.unix.Errors$NativeIoException: close() failed: Bad file descriptor
    at io.netty.channel.unix.Errors.newIOException(Errors.java:105)
    at io.netty.channel.unix.FileDescriptor.close(FileDescriptor.java:58)
    at io.netty.channel.epoll.AbstractEpollChannel.doClose(AbstractEpollChannel.java:112)
    at io.netty.channel.epoll.AbstractEpollStreamChannel.doClose(AbstractEpollStreamChannel.java:554)
    at io.netty.channel.AbstractChannel$AbstractUnsafe.closeForcibly(AbstractChannel.java:636)
    at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:320)
    at io.netty.bootstrap.Bootstrap.doConnect(Bootstrap.java:134)
    at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:90)
    at net.md_5.bungee.BungeeServerInfo.ping(BungeeServerInfo.java:143)
    at net.md_5.bungee.BungeeServerInfo.ping(BungeeServerInfo.java:122)
    at usermanager.bungee.TaskServerChecker.run(TaskServerChecker.java:25)
    at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)


13:29:22 [SEVERE] Jun 23, 2016 1:29:22 PM io.netty.util.concurrent.DefaultPromise execute
SEVERE: Failed to submit a listener notification task. Event loop shut down?
java.util.concurrent.RejectedExecutionException: event executor terminated
    at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:715)
    at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:300)
    at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:691)
    at io.netty.util.concurrent.DefaultPromise.execute(DefaultPromise.java:671)
    at io.netty.util.concurrent.DefaultPromise.notifyLateListener(DefaultPromise.java:641)
    at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:138)
    at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:93)
    at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:28)
    at net.md_5.bungee.BungeeServerInfo.ping(BungeeServerInfo.java:143)
    at net.md_5.bungee.BungeeServerInfo.ping(BungeeServerInfo.java:122)
    at usermanager.bungee.TaskServerChecker.run(TaskServerChecker.java:25)
    at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

We're running Java 8.

**Comment by Janmm14** [comment]
You might want to test it without plugins, especially without usermanager.
(`at usermanager.bungee.TaskServerChecker.run(TaskServerChecker.java:25)`)
Likely a plugin issue.

**Comment by L4BORG** [comment]
This is not an issue anymore.
