### ISSUE TITLE
IndexOutOfBoundsException: readerIndex(3) + length(68) exceeds writerIndex(18): PooledUnsafeDirectByteBuf(ridx: 3, widx: 18, cap: 18)

### ISSUE THREAD

**Issue by mibby** [SpigotMC/BungeeCord#1906]
BungeeCord dev 1167

```
04:01:18 [SEVERE] [/76.22.33.233:64306] <-> InitialHandler - encountered exception
io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(3) + length(68) exceeds writerIndex(18): PooledUnsafeDirectByteBuf(ridx: 3, widx: 18, cap: 18)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:276)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:263)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
	at io.netty.handler.codec.ByteToMessageDecoder.handlerRemoved(ByteToMessageDecoder.java:216)
	at io.netty.channel.DefaultChannelPipeline.callHandlerRemoved0(DefaultChannelPipeline.java:527)
	at io.netty.channel.DefaultChannelPipeline.callHandlerRemoved(DefaultChannelPipeline.java:521)
	at io.netty.channel.DefaultChannelPipeline.remove0(DefaultChannelPipeline.java:351)
	at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:322)
	at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:299)
	at net.md_5.bungee.protocol.LegacyDecoder.decode(LegacyDecoder.java:37)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:360)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:152)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:823)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:339)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:255)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(3) + length(68) exceeds writerIndex(18): PooledUnsafeDirectByteBuf(ridx: 3, widx: 18, cap: 18)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1178)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1172)
	at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:693)
	at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:701)
	at net.md_5.bungee.protocol.DefinedPacket.readString(DefinedPacket.java:36)
	at net.md_5.bungee.protocol.packet.Handshake.read(Handshake.java:27)
	at net.md_5.bungee.protocol.DefinedPacket.read(DefinedPacket.java:185)
	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:33)
	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:10)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89)
	... 26 more
```

**Comment by i9hdkill** [comment]
The usual thing: Make sure all your bungeee plugins are up to date (1.10). Same goes for your spigot plugins.
Bungee plugins + versions?

**Comment by mibby** [comment]
The only Bungee plugin I use is ServerListPlus (dev 401) and that is already up to date. Same goes for Spigot plugins. Everything is up to date as of their latest dev build / source change equivalent release.

**Comment by Janmm14** [comment]
This problem is about logging in or getting the motd. Does this error occurr periodically (indicating a strange server list pinging you) or did it just occurred once?

**Comment by mibby** [comment]
Going through my logs from the last day or two, it occurred twice. 

```
17:59:38 [SEVERE] [/51.254.217.248:40259] <-> InitialHandler - encountered exception
io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(1) + length(1) exceeds writerIndex(1): SlicedAbstractByteBuf(ridx: 1, widx: 1, cap: 1/1, unwrapped: PooledUnsafeDirectByteBuf(ridx: 2, widx: 2, cap: 2))
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:99)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:154)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:354)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:145)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:277)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:264)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:154)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:354)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:145)
	at io.netty.handler.codec.ByteToMessageDecoder.handlerRemoved(ByteToMessageDecoder.java:217)
	at io.netty.channel.DefaultChannelPipeline.callHandlerRemoved0(DefaultChannelPipeline.java:756)
	at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:577)
	at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:540)
	at net.md_5.bungee.protocol.LegacyDecoder.decode(LegacyDecoder.java:37)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:387)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:245)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:154)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:354)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:145)
	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:152)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:154)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:354)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:145)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:1078)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:872)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:359)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:275)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(1) + length(1) exceeds writerIndex(1): SlicedAbstractByteBuf(ridx: 1, widx: 1, cap: 1/1, unwrapped: PooledUnsafeDirectByteBuf(ridx: 2, widx: 2, cap: 2))
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1345)
	at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:648)
	at net.md_5.bungee.protocol.DefinedPacket.readVarInt(DefinedPacket.java:100)
	at net.md_5.bungee.protocol.DefinedPacket.readVarInt(DefinedPacket.java:90)
	at net.md_5.bungee.protocol.packet.Handshake.read(Handshake.java:26)
	at net.md_5.bungee.protocol.DefinedPacket.read(DefinedPacket.java:185)
	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:41)
	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:10)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89)
	... 32 more
```

**Comment by md-5** [comment]
We don't care about these sorts of things unless they actually cause issues for players connecting. Anyone can cause them trivially.

**Comment by mibby** [comment]
Well I figured I'd report it so the exception could be caught. But I guess it is too trivial to care about.

**Comment by md-5** [comment]
This is the exception being caught.
Uncaught exceptions crash a program.

**Comment by mibby** [comment]
Apologies. When I mean catch, not show up in the console if it isn't important to care about.

**Comment by md-5** [comment]
Problem with that is then when people do get actual issues they have limited info to help us with.

**Comment by mibby** [comment]
Can't you catch this type of exception specifically since it is a non-issue according to you? The two errors listed above are slightly different from each other though.

**Comment by GotoFinal** [comment]
@mibby some day, after some updates, it may throw similar error of this same type etc, and cause real problems, and then bungee team will be not able to see this error.

Other way it additional config for debug errors like that, but as long as this don't cause real problems, I don't see why this is important for you.

**Comment by mibby** [comment]
@GotoFinal Not asking for a catch-all for all errors, just a fix for the writerIndex being exceeded. Since this is a trivial type of error according to md-5, I doubt future errors of this 'type' would be considered a problem. 

Cleaning up the console output to avoid unnecessary / pointless exceptions from occurring keeps things consumer friendly and nice looking. Or at the very least, having an output to see what message was sent/received that exceeded the writerIndex. As it is my understanding that this is an error that 'can't be fixed' since it isn't a problem to begin with, no point in having the full stracktrace displayed when it doesn't provide any useful information.

**Comment by GotoFinal** [comment]
@mibby 
Like I said, some day, after some updates, this same error may provide useful information about some new bug, as it may be then related with this, so if md_5 will silent it - there will no way to simple check it.
Like mojang will add new broken packet, and sending some bytes will cause it to occupy all memory or crash server, it will probably throw this same error at some point, about writer/reader index, and you want silent this error, so this bug will be much harder to fix, as nobody will notice that error is thrown.

This is server, this isn't client side product, errors are normal here.

**Comment by STEAKISAWAKE** [comment]
THIS IS NOW IMPORTANT TO ME!!!

**Comment by STEAKISAWAKE** [comment]
ITS CLOSE TO THE SAME ERRROR

**Comment by Janmm14** [comment]
@STEAKISAWAKE 
Well an error is not always indicating malfunction in regarda to a player on the other end.

**Comment by accio-nox** [comment]
Hi guys any update on how to fix this. getting this error on a modpack we run and its stopping players joining the server completely?

**Comment by kxkl2077** [comment]
I have an error like this when transferring to other sub-servers:

IndexOutOfBoundsException : reader Index(160) + leng th(1) exceeds wr iterIndex(160): PooledUnsafeDirectByteBuf(ridx: 160, widx: 160, cap: 160) @

io.netty.buffer .Abs trac tByteBuf:1442

**Comment by kxkl2077** [comment]
Why do I get error: ource when I jump to other sub-servers?

08:57:35 [serious] at Java. Lang. Reflect. Method. Invoke (Unknown Source)

08:57:35 [serious] at net. Md_5. Bungee. Event. EventHandlerMethod. Invoke (EventHand

lerMethod.java:19)

08:57:35 [serious] at net. Md_5. Bungee. Event. The EventBus. Post (49) EventBus. Java:

08:57:35 [serious] at net. Md_5. Bungee. API. The plugin. The PluginManager. CallEvent (plugin

Manager.java:412)

08:57:35 [serious] at net. Md_5. Bungee. ServerConnector. Handle (ServerConnector. Ja

va:186)

08:57:35 [serious] at net. Md_5. Bungee. Protocol. The packet. The Login. The handle (Login. Java: 2

28)

08:57:35 [serious] at net.md_5.bungee.net ty. HandlerBoss. ChannelRead (HandlerBoss

.java:114)

08:57:35 [serious] at io.net ty. Channel. AbstractChannelHandlerContext. InvokeChan

nelRead(AbstractChannelHandlerContext.java:379)

08:57:35 [serious] at io.net ty. Channel. AbstractChannelHandlerContext. InvokeChan

nelRead(AbstractChannelHandlerContext.java:365)

08:57:35 [serious] at io.net ty. Channel. AbstractChannelHandlerContext. FireChanne

lRead(AbstractChannelHandlerContext.java:357)

08:57:35 ty [serious] at io.net. A handler. A timeout. IdleStateHandler. ChannelRead (Idl

eStateHandler.java:286)

08:57:35 [serious] at io.net ty. Channel. AbstractChannelHandlerContext. InvokeChan

nelRead(AbstractChannelHandlerContext.java:379)

08:57:35 [serious] at io.net ty. Channel. AbstractChannelHandlerContext. InvokeChan

nelRead(AbstractChannelHandlerContext.java:365)

08:57:35 [serious] at io.net ty. Channel. AbstractChannelHandlerContext. FireChanne

lRead(AbstractChannelHandlerContext.java:357)

08:57:35 [serious] at io.net ty. Handler. Codec. MessageToMessageDecoder. ChannelRea

d(MessageToMessageDecoder.java:103)

08:57:35 [serious] at io.net ty. Channel. AbstractChannelHandlerContext. InvokeChan

nelRead(AbstractChannelHandlerContext.java:379)

08:57:35 [serious] at io.net ty. Channel. AbstractChannelHandlerContext. InvokeChan

nelRead(AbstractChannelHandlerContext.java:365)

08:57:35 [serious] at io.net ty. Channel. AbstractChannelHandlerContext. FireChanne

lRead(AbstractChannelHandlerContext.java:357)

08:57:35 [serious] at io.net ty. Handler. Codec. MessageToMessageDecoder. ChannelRea

d(MessageToMessageDecoder.java:103)

08:57:35 [serious] at io.net ty. Channel. AbstractChannelHandlerContext. InvokeChan

nelRead(AbstractChannelHandlerContext.java:379)

08:57:35 [serious] at io.net ty. Channel. AbstractChannelHandlerContext. InvokeChan

nelRead(AbstractChannelHandlerContext.java:365)

08:57:35 [serious] at io.net ty. Channel. AbstractChannelHandlerContext. FireChanne

lRead(AbstractChannelHandlerContext.java:357)

08:57:35 [serious] at io.net ty. Handler. Codec. ByteToMessageDecoder. FireChannelRe

ad(ByteToMessageDecoder.java:327)

08:57:35 [serious] at io.net ty. Handler. Codec. ByteToMessageDecoder. FireChannelRe

ad(ByteToMessageDecoder.java:314)

08:57:35 [serious] at io.net ty. Handler. Codec. ByteToMessageDecoder. CallDecode (By

teToMessageDecoder.java:435)

08:57:35 [serious] at io.net ty. Handler. Codec. ByteToMessageDecoder. ChannelRead (B

yteToMessageDecoder.java:279)

08:57:35 [serious] at io.net ty. Channel. AbstractChannelHandlerContext. InvokeChan

nelRead(AbstractChannelHandlerContext.java:379)

08:57:35 [serious] at io.net ty. Channel. AbstractChannelHandlerContext. InvokeChan

nelRead(AbstractChannelHandlerContext.java:365)

08:57:35 [serious] at io.net ty. Channel. AbstractChannelHandlerContext. FireChanne

lRead(AbstractChannelHandlerContext.java:357)

08:57:35 [serious] at io.net ty. Channel. DefaultChannelPipeline $HeadContext. Chann

elRead(DefaultChannelPipeline.java:1410)

08:57:35 [serious] at io.net ty. Channel. AbstractChannelHandlerContext. InvokeChan

nelRead(AbstractChannelHandlerContext.java:379)

08:57:35 [serious] at io.net ty. Channel. AbstractChannelHandlerContext. InvokeChan

nelRead(AbstractChannelHandlerContext.java:365)

08:57:35 [serious] at io.net ty. Channel. DefaultChannelPipeline. FireChannelRead (D

efaultChannelPipeline.java:919)

08:57:35 [serious] at io.net ty. Channel. Nio. $NioByteUnsafe AbstractNioByteChannel

.read(AbstractNioByteChannel.java:166)

08:57:35 [serious] at io.net ty. Channel. Nio. NioEventLoop. ProcessSelectedKey (NioE

ventLoop.java:722)

08:57:35 [serious] at io.net ty. Channel. Nio. NioEventLoop. ProcessSelectedKeysOpti

mized(NioEventLoop.java:658)

08:57:35 [serious] at io.net ty. Channel. Nio. NioEventLoop. ProcessSelectedKeys (nio

EventLoop.java:584)

Ty 08:57:35 [serious] at io.net. Channel. Nio. NioEventLoop. Run (NioEventLoop. Java: 4

96).

08:57:35 [serious] at io.net ty. Util. Concurrent. SingleThreadEventExecutor $4. Run (

SingleThreadEventExecutor.java:995)

Ty 08:57:35 [serious] at io.net. Util. Internal. ThreadExecutorMap $2. Run (ThreadExec

utorMap.java:74)

08:57:35 [Critical] at java.lang.thread. run(Unknown Source)

08:57:35 [Message] [KXKL2077] <-> DownstreamBridge <-> [BedwarsXP-6] has disconnect

ed

08:57:40 [Message] [/111.60.192.91:8291] <-> InitialHandler has pinged

>end

08:59:00 [Message] Closing Listener [ID: 0xBfD55403, L:/ 0:0:0:0:0:0:0:25:565]

08:59:00 [Message] Closing pending Connections

08:59:00 [Information] Disconnecting 1 Connections

08:59:00 [Message] [kxKL2077] disconnected with: [Proxy] Proxy restarting.

08:59:00 [Info] [KXKL2077] -> UpstreamBridge has disconnected

0
