### ISSUE TITLE
startup freezing

### ISSUE THREAD

**Issue by random1167** [SpigotMC/BungeeCord#1923]
```
05:23:55 [SEVERE] Exception in thread "main"
05:23:55 [SEVERE] java.lang.ClassCastException: java.util.LinkedHashMap cannot be cast to java.lang.String
05:23:55 [SEVERE]     at net.md_5.bungee.util.CaseInsensitiveHashingStrategy.computeHashCode(CaseInsensitiveHashingStrategy.java:13)
05:23:55 [SEVERE]     at gnu.trove.impl.hash.TCustomObjectHash.hash(TCustomObjectHash.java:94)
05:23:55 [SEVERE]     at gnu.trove.impl.hash.TObjectHash.insertKey(TObjectHash.java:280)
05:23:55 [SEVERE]     at gnu.trove.set.hash.TCustomHashSet.add(TCustomHashSet.java:114)
05:23:55 [SEVERE]     at gnu.trove.set.hash.TCustomHashSet.addAll(TCustomHashSet.java:297)
05:23:55 [SEVERE]     at gnu.trove.set.hash.TCustomHashSet.<init>(TCustomHashSet.java:103)
05:23:55 [SEVERE]     at net.md_5.bungee.util.CaseInsensitiveSet.<init>(CaseInsensitiveSet.java:16)
05:23:55 [SEVERE]     at net.md_5.bungee.conf.Configuration.load(Configuration.java:88)
05:23:55 [SEVERE]     at net.md_5.bungee.BungeeCord.start(BungeeCord.java:259)
05:23:55 [SEVERE]     at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:55)
05:23:55 [SEVERE]     at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

```
just updated bungee and now my server wont start
`Enabled BungeeCord version git:BungeeCord-Bootstrap:1.10-SNAPSHOT:b374a69:1174
`

**Comment by Paulomart** [comment]
Do you have plugins?

**Comment by Janmm14** [comment]
Your `config.yml` seems to be invalid. Please double-check or save old config and regenerate and apply old config by hand.

**Comment by random1167** [comment]
config had a null :null ..removed and its ok now..

**Comment by Envici** [comment]
@random1167 I'd close this issue now if everything is resolved. If not, I am sure @md-5 can.
