### ISSUE TITLE
Can't join server

### ISSUE THREAD

**Issue by detig-iii** [SpigotMC/BungeeCord#1954]
I sometimes can't connect to my spigot server behind the bungeecord, spigot is on 1.10 and bungeecord is the build 1189. I don't use any bungee plugins. Any idea on how to solve this? When I try to join it first says Loggin in like usual but then throws this error. Weird thing is sometimes it works and some other times it won't, making me completely unable to join back in and thus making the experience very unreliable.
`io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(1040) + length(1) exceeds writerIndex(1040): PooledUnsafeDirectByteBuf(ridx: 1040, widx: 1040, cap: 8192)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:280)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:396)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:883)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:389)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:305)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(1040) + length(1) exceeds writerIndex(1040): PooledUnsafeDirectByteBuf(ridx: 1040, widx: 1040, cap: 8192)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1179)
	at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:589)
	at net.md_5.bungee.protocol.DefinedPacket.readVarInt(DefinedPacket.java:108)
	at net.md_5.bungee.protocol.DefinedPacket.readVarInt(DefinedPacket.java:98)
	at net.md_5.bungee.protocol.DefinedPacket.readString(DefinedPacket.java:29)
	at net.md_5.bungee.protocol.packet.PlayerListItem.read(PlayerListItem.java:38)
	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:33)
	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:10)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
	... 27 more`

**Comment by Fejm** [comment]
https://www.spigotmc.org/threads/mojang-added-a-new-ip-property.180864/

**Comment by detig-iii** [comment]
Would you mind elaborating a bit more on how this might solve the issue? From what I can tell the thread you linked doesn't provide all information necessary. But thanks anyways so far :+1:

**Comment by Black-Hole** [comment]
It looks like BungeeCord was handling the changed profile right, but the Spigot server didn't. So the Spigot server was sending an invalid PlayerListItem packet to the server.

**Comment by detig-iii** [comment]
The topic Fejm posted has grown larger now, apparently it was a vanilla issue after all.
