### ISSUE TITLE
Compression cannot be disabled

### ISSUE THREAD

**Issue by MylesIsCool** [SpigotMC/BungeeCord#1958]
**How to reproduce:**
Set network_compression_threshold to -1 in config.yml

It will then produce the following error on connect:
`14:50:59 [SEVERE] Sep 27, 2016 2:50:59 PM io.netty.util.concurrent.SingleThreadEventExecutor runAllTasks
WARNING: A task raised an exception.
java.util.NoSuchElementException: compress
    at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1040)
    at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:423)
    at net.md_5.bungee.netty.ChannelWrapper.setCompressionThreshold(ChannelWrapper.java:88)
    at net.md_5.bungee.UserConnection.setCompressionThreshold(UserConnection.java:629)
    at net.md_5.bungee.connection.InitialHandler$6$1.run(InitialHandler.java:494)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:408)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:402)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
    at java.lang.Thread.run(Unknown Source)`

**Relevant file:** https://github.com/SpigotMC/BungeeCord/blob/aaddc9fcfdcada8d19ab115f2dcc8aed413a9206/proxy/src/main/java/net/md_5/bungee/netty/ChannelWrapper.java#L88

Solution: Only remove if the element is part of the pipeline.

**Comment by md-5** [comment]
Why would you do this? Chunks would use an insane amount of bandwidth

**Comment by MylesIsCool** [comment]
@md-5 

Comparing the performance of using compression vs not?

It also makes debugging much easier at a packet level because it means I can just offline mode + disable compression and grab wireshark?

I understand there's no production use for it, but from a development standpoint it's really useful to have.
