### ISSUE TITLE
Disconnecting when picking up item.

### ISSUE THREAD

**Issue by ghacproductions** [SpigotMC/BungeeCord#1988]
When using the latest BungeeCord for 1.11 (#1200) and picking up an item , the client gets disconnected as soon as the client picks up the item.  Tested with the original minecraft 1.11 server (vanilla) and a clean BungeeCord without any plugins.

Client log:

`[20:01:46] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: readerIndex(1) + length(72) exceeds writerIndex(72): UnpooledHeapByteBuf(ridx: 1, widx: 72, cap: 72)
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_73]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_73]
	at h.a(SourceFile:47) [1.11.jar:?]
	at beq.av(SourceFile:959) [1.11.jar:?]
	at beq.a(SourceFile:395) [1.11.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [1.11.jar:?]
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(1) + length(72) exceeds writerIndex(72): UnpooledHeapByteBuf(ridx: 1, widx: 72, cap: 72)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1175) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
	at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:655) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
	at et.readBytes(SourceFile:759) ~[1.11.jar:?]
	at et.e(SourceFile:333) ~[1.11.jar:?]
	at bnm.a(SourceFile:1520) ~[1.11.jar:?]
	at go.a(SourceFile:54) ~[1.11.jar:?]
	at go.a(SourceFile:9) ~[1.11.jar:?]
	at fo$1.run(SourceFile:13) ~[1.11.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_73]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_73]
	at h.a(SourceFile:46) ~[1.11.jar:?]
	... 3 more`

**Comment by electronicboy** [comment]
fixed by #1992
