### ISSUE TITLE
Players get kicked randomly

### ISSUE THREAD

**Issue by JoeyHaalboom** [SpigotMC/BungeeCord#2000]
My players get kicked from a server randomly. 

This is the error it shows:

21:20:08 [SEVERE] [EpicDuck13] <-> DownstreamBridge <-> [Prison] - encountered exception
io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(1061) + length(1) exceeds writerIndex(1061): PooledUnsafeDirectByteBuf(ridx: 1061, widx: 1061, cap: 8192)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:1018)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:402)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:307)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(1061) + length(1) exceeds writerIndex(1061): PooledUnsafeDirectByteBuf(ridx: 1061, widx: 1061, cap: 8192)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1395)
	at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:687)
	at net.md_5.bungee.protocol.DefinedPacket.readVarInt(DefinedPacket.java:108)
	at net.md_5.bungee.protocol.DefinedPacket.readVarInt(DefinedPacket.java:98)
	at net.md_5.bungee.protocol.packet.PlayerListItem.read(PlayerListItem.java:54)
	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:33)
	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:10)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
	... 25 more

Bungee plugins: SkinsRestorer, ServerListPlus, Quietcord, NetworkManager
Bungee version: Build 1205 
Java version: 8

**Comment by JoeyHaalboom** [comment]
Pastebin link of the error: http://pastebin.com/N5tQJkkR

**Comment by i9hdkill** [comment]
Can you reproduce that without SkinsRestorer?

**Comment by JoeyHaalboom** [comment]
The problem is that I dont know how it happens or when, So like 15 minutes ago I restarted my bungee and no problems until now. (With Skinsrestorer  still in it)

**Comment by JoeyHaalboom** [comment]
Okey It happend again. I had 3 accounts online, 2 of them 1.11 and 1 1.10. 

The 1.10 account got kicked: http://pastebin.com/01ig2uj4

Will try now without SkinsRestorer.

**Comment by JoeyHaalboom** [comment]
The error still happends without SkinsRestorer: http://pastebin.com/4BqNP55g

This time only 1.11 clients were kicked. Its 1.10 or 1.11 never both of them.

**Comment by i9hdkill** [comment]
Any errors spigot side? Try to reproduce without bungeeplugins

**Comment by md-5** [comment]
Signs point to Bungee or Server running plugins interfering with skins | tab list.
Please reproduce on clean sserver and bungee

**Comment by JoeyHaalboom** [comment]
For people who have issues with it. I removed Skinsrestorer from every server exept the bungee and that seems to be fixing it.
