### ISSUE TITLE
Memory leak with build #1217

### ISSUE THREAD

**Issue by Scarsz** [SpigotMC/BungeeCord#2039]
Full `.jps` (JProfiler) snapshot of BungeeCord: http://play.narcowars.net/bungeecord-memory-leak.tar.gz

BungeeCord version: `git:BungeeCord-Bootstrap:1.11-SNAPSHOT:6104354:1217 by md_5`
Command line args: `java -Xmx2G -jar bungeecord.jar`
No plugins on BungeeCord aside from the default ones. Completely vanilla aside from changing config. Both servers under the BungeeCord instance are running `git-Spigot-de459a2-51263e9 (MC: 1.10.2)` with `bungeecord=true` & `online-mode=false`

Java version:
```
openjdk version "1.8.0_111"
OpenJDK Runtime Environment (build 1.8.0_111-8u111-b14-2ubuntu0.16.04.2-b14)
OpenJDK 64-Bit Server VM (build 25.111-b14, mixed mode)
```
BungeeCord config:
```
ip_forward: true
network_compression_threshold: 256
stats: STATSKEY
groups:
  Scarsz:
  - admin
servers:
  factions:
    motd: '&cNarcoWars Factions'
    address: localhost:SERVERPORT
    restricted: false
  outage:
    motd: '&4NarcoWars Outage Lobby'
    address: localhost:SERVERPORT
    restricted: false
timeout: 30000
player_limit: -1
listeners:
- query_port: 25565
  motd: '&1Under development'
  priorities:
  - factions
  - outage
  bind_local_address: true
  tab_list: GLOBAL_PING
  query_enabled: false
  host: 0.0.0.0:25565
  max_players: 1
  tab_size: 60
  ping_passthrough: true
  force_default_server: false
  forced_hosts:
    play.narcowars.net: factions
permissions:
  default:
  - bungeecord.command.server
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
online_mode: true
log_commands: true
disabled_commands:
- disabledcommandhere
connection_throttle: 4000
```
Stack trace:
```
17:59:30 [INFO] [PLAYERNAME] <-> ServerConnector [SERVERNAME] has connected
17:59:31 [SEVERE] [PLAYERNAME] <-> DownstreamBridge <-> [SERVERNAME] - encountered exception
io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 1895825415, max: 1908932608)
        at io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:624)
        at io.netty.util.internal.PlatformDependent.allocateDirectNoCleaner(PlatformDependent.java:578)
        at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:709)
        at io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:698)
        at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:237)
        at io.netty.buffer.PoolArena.allocate(PoolArena.java:213)
        at io.netty.buffer.PoolArena.allocate(PoolArena.java:141)
        at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:262)
        at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:179)
        at io.netty.buffer.UnsafeByteBufUtil.copy(UnsafeByteBufUtil.java:464)
        at io.netty.buffer.PooledUnsafeDirectByteBuf.copy(PooledUnsafeDirectByteBuf.java:309)
        at io.netty.buffer.AbstractUnpooledSlicedByteBuf.copy(AbstractUnpooledSlicedByteBuf.java:227)
        at io.netty.buffer.AbstractByteBuf.copy(AbstractByteBuf.java:1163)
        at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:24)
        at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:10)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:280)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:396)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:1018)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:402)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:307)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
        at java.lang.Thread.run(Thread.java:745)
17:59:31 [INFO] [PLAYERNAME] <-> DownstreamBridge <-> [SERVERNAME] has disconnected
```
Heap:
![Heap screenshot](http://i.imgur.com/Qb7SRaf.png)

**Comment by md-5** [comment]
That's not a memory snapshot we can read - please use the standard hprof format.

Additionally your heap is only 393MB big... that's hardly leaking in my book.
Direct memory is separate and configured via;
-XX:MaxDirectMemorySize=<size>

**Comment by Scarsz** [comment]
Yeah, perhaps memory ***leak*** wasn't the best word to describe the problem, moreso not being able to allocate memory that it should be able to. By what you said, I should be adding `-XX:MaxDirectMemorySize=2G` to the command line? When the issue happens next I'll be sure to post back with a hprof snapshot, wasn't aware that it was prefered.

**Comment by md-5** [comment]
Probably not 2G, more like 256-512mb

**Comment by Scarsz** [comment]
New command line is `java -XX:MaxDirectMemorySize=512M -Xmx512M -jar bungeecord.jar` then, plenty of memory to go around on the machine. Will post back when/if the memory issues occur again.

**Comment by Scarsz** [comment]
Nevermind, that was very quick.

New stacktrace (with the new 512MB max for netty now)
```
18:52:28 [SEVERE] [PLAYERNAME] <-> DownstreamBridge <-> [factions] - encountered exception
io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 520093703, max: 536870912)
    at io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:624)
    at io.netty.util.internal.PlatformDependent.allocateDirectNoCleaner(PlatformDependent.java:578)
    at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:709)
    at io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:698)
    at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:237)
    at io.netty.buffer.PoolArena.allocate(PoolArena.java:213)
    at io.netty.buffer.PoolArena.allocate(PoolArena.java:141)
    at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:262)
    at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:179)
    at io.netty.buffer.UnsafeByteBufUtil.copy(UnsafeByteBufUtil.java:464)
    at io.netty.buffer.PooledUnsafeDirectByteBuf.copy(PooledUnsafeDirectByteBuf.java:309)
    at io.netty.buffer.AbstractUnpooledSlicedByteBuf.copy(AbstractUnpooledSlicedByteBuf.java:227)
    at io.netty.buffer.AbstractByteBuf.copy(AbstractByteBuf.java:1163)
    at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:24)
    at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:10)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:280)
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:396)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
    at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:1018)
    at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:402)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:307)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
    at java.lang.Thread.run(Thread.java:745)
```
Mind linking a tutorial or anything of the sort to assist with getting a hprof dump?

**Comment by Scarsz** [comment]
Nevermind, seems like I got it. `.hprof` dump available at http://play.narcowars.net/bungeecord-heap-hprof.tar.gz

![Image](http://i.imgur.com/m2XmiYS.png)

**Comment by Janmm14** [comment]
@Scarsz which scoreboard/teams plugins are you using on your bukkit/spigot/whatever servers?

**Comment by Scarsz** [comment]
@Janmm14 just Featherboard to my knowledge.

Full list:
```
Plugins (178): EventDebug, SkullDropping, SimpleBroadcast, JoinEventsPro, MythicLib, Vehicles, 
EnchantsPlus, PlugMan, AboutPlayer, EnderVault, CommandTimer, ChatReplay, CustomGapple, 
RewardSign, YouTuber, SimpleAPI, DurabilityNotify, TigerReports, AsyncWorldEditInjector, MentionMe, 
FirstJoinPlus, SpyPlusPlus, AdvancedBan, VehiclesFlags, Reputation, SaveInvOnDeath, ServerForms, 
CraftedBy, SimplePets, Statscraft, TablistPrefix, Multiverse-Core, ProtocolLib, Vouchers, Calendar, dtlCore, 
HAC, OldPvP, TrollCommandsPlusPlus, PermissionsEx, TimeIsMoney, TabGroup, FeatherBoard, mcMMO, 
MyMenu, NoAfkFishing, SantaKiller, ColoredSigns, StaffMonitor, FancyShop, PickYourPic, 
PressureCommands, PlayTime, BungeeLobbyKick, FlyingMobs, FastCraftPlus, ForceField, TeleportSigns, 
HideAndCustomPlugins, EntityDetection, ChatReaction, TitleAPI, CustomNukes, VendingMachines, 
MOTD, ShutdownNotice, UltimateChristmas, TimeLock, BackToTheRoots, NotchApple, CoreProtect, 
Ridemycraft, Message, VoteRoulette, WorldEdit, AdminFun, CellPhone, OpenInv, WordGamesPlus, 
AltsRevealer, ClearLag, CrackShot, Duty, Emoji, Votifier, EndlessEnchant, BannerBoard, Notes, 
LibsDisguises, MineStatus-Universal, Realistic_fish, Applications, Auto_AirDrop, eZProtector, 
AsyncWorldEdit, CompassNavigator, ObsidianBreaker, DropParty, RankSigns, TabMenu, MineMention, 
PlayerInfo, Vault, CubeRunner, DrugMeUp, MassiveCore, Tablistplus, BlockParticles, CreativeParkour, 
HolographicDisplays, SignShop, WiiPay, ChatItem, WorldSchematics2, Newspaper, PlayerVaults, 
AddLight, MyCommand, EZRanksPro, RunesEnchant, mcMMOAction, Citizens, CloneMe, SimplePrefix, 
RedeemableMcMMO, ChatGames, MobArena, Trading, WorldGuard, Brewery, RecruitMe, AuctionHouse, 
WanderingNPC, EZPrestige, CratesPlus, Denizen, AreaShop, NPGuys, Essentials, CrackGame, FriskStick, 
CommandSign, KitAdder, DiscordSRV, AdvancedAchievements, RegionPerms, MineBackup, 
EssentialsExtras, EnjinMinecraftPlugin, RecordPlugin, MythicMobs, WeatherMan, StatusBlock, 
CheckMyInventory, ServerSigns, CustomEnchantments, Jobs, dtlTraders, Sentinel, EssentialsChat, Hotels, 
Disease, Builder, RankVouchers, Factions, LeaderHeads, EssentialsSpawn, PvPManager, FBasics, Magic, 
Signs, SuperVanish, FactionsTop, SilkSpawners, FactionMobs, FactionChat, MyPet, MobHunting
```

**Comment by md-5** [comment]
Yeah.... you probably have a buggy plugin on your server.

Good luck finding which.
