### ISSUE TITLE
WARNING: A task raised an exception. Task: net.md_5.bungee.connection.InitialHandler

### ISSUE THREAD

**Issue by L4BORG** [SpigotMC/BungeeCord#2043]
```
>bungee
22:51:56 [INFO] CONSOLE executed command: /bungee
22:51:56 [INFO] This server is running BungeeCord version git:BungeeCord-Bootstrap:1.11-SNAPSHOT:81de9d5:1221 by md_5
```

```
22:09:58 [SEVERE] Jan 16, 2017 10:09:58 PM io.netty.util.concurrent.AbstractEventExecutor safeExecute
WARNING: A task raised an exception. Task: net.md_5.bungee.connection.InitialHandler$6$1@7c0dfac1
java.util.NoSuchElementException: packet-encoder
	at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1080)
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:251)
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:240)
	at net.md_5.bungee.netty.ChannelWrapper.addBefore(ChannelWrapper.java:115)
	at net.md_5.bungee.netty.ChannelWrapper.setCompressionThreshold(ChannelWrapper.java:127)
	at net.md_5.bungee.UserConnection.setCompressionThreshold(UserConnection.java:613)
	at net.md_5.bungee.connection.InitialHandler$6$1.run(InitialHandler.java:497)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:418)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:312)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
	at java.lang.Thread.run(Thread.java:745)

```

Any idea what is causing this or why this is happening?

It would happen randomly but always after the user is trying to connect to the server (random user every now and then and if the user tries to reconnect it usually wouldn't happen again).

**Comment by L4BORG** [comment]
With:

```
ip_forward: true
network_compression_threshold: 256
```

**Comment by kamcio96** [comment]
plugins?

**Comment by L4BORG** [comment]
SkinsRestorer, ServerListPlus, NuVotifier, Ubuntu.

**Comment by md-5** [comment]
SkinsRestorer not supported

**Comment by L4BORG** [comment]
I understand, will try to replicate without SkinsRestorer. Also any idea how SkinsRestorer could have caused this?

**Comment by L4BORG** [comment]
Also considering https://github.com/SpigotMC/BungeeCord/blob/0581e49d49aa3622b1fea1623eb512ab95989e41/proxy/src/main/java/net/md_5/bungee/UserConnection.java#L613 could there be an issue with sending titles?

**Comment by Paulomart** [comment]
Are you using viaversion?

**Comment by L4BORG** [comment]
Yes, on lobbies (running ViaVersion on Spigot instances not on BungeeCord). You think this is ViaVersion issue? From what I saw the player wouldn't even come to the lobbies.

**Comment by i9hdkill** [comment]
Wrong place to get support. Please visit our BungeeCord forums.
https://www.spigotmc.org/forums/bungeecord-help.70/

**Comment by Paulomart** [comment]
Yeah was about viaversion on proxy.

**Comment by L4BORG** [comment]
We were NOT using ViaVersion on BungeeCord plugin (but we do use ViaVersion on Spigot instances).

Also I've already managed to solve the issue, it was not ViaVersion nor SkinsRestorer related.

Good day.

**Comment by Fluxty** [comment]
@L4BORG I am experiencing a similar issue if you could help spread some light on your fix?

**Comment by BSSI1** [comment]
@Fluxty BungeeCord plugins? 

If you're using SkinRestorer try removing it since BungeeCord will not work properly with SkinRestorer (see @md-5 's comment).

**Comment by pandaboy1942** [comment]
Ive found the solution while i have a research the config. Every single player pass the proxy, except the player defined in `group:` wont be pass (not SkinRestorer).  So set `group: root: -default`  make no one got hurt
