### ISSUE TITLE
Cannot start the server on a Raspberry Pi (UnsatisfiedLinkError)

### ISSUE THREAD

**Issue by lapin-b** [SpigotMC/BungeeCord#2050]
Hello,
Sorry if I'm just being stupid but I've got a beautiful error while booting a BungeeCord on my Raspberry Pi.
Anyways, I get the following error on the latest build (`#1223` at the time of writing):

```
$ java -jar BungeeCord.jar
Exception in thread "main" java.lang.UnsatisfiedLinkError: Could not load library. Reasons: [no jansi32-BungeeCord in java.library.path, no jansi-BungeeCord in java.library.path, no jansi in java.library.path, /tmp/libjansi-32-BungeeCord-3610616475677447539.so: /tmp/libjansi-32-BungeeCord-3610616475677447539.so: Ne peut ouvrir le fichier d'objet partagé: Aucun fichier ou dossier de ce type (Possible cause: can't load IA 32-bit .so on a ARM-bit platform)]
	at org.fusesource.hawtjni.runtime.Library.doLoad(Library.java:182)
	at org.fusesource.hawtjni.runtime.Library.load(Library.java:140)
	at org.fusesource.jansi.internal.CLibrary.<clinit>(CLibrary.java:42)
	at org.fusesource.jansi.AnsiConsole.wrapOutputStream(AnsiConsole.java:48)
	at org.fusesource.jansi.AnsiConsole.<clinit>(AnsiConsole.java:38)
	at net.md_5.bungee.BungeeCord.<init>(BungeeCord.java:210)
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:52)
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
```

I followed the installation guide by `wget`ing the file and running it.

For who is wondering what's my Java version, there it is:
```
openjdk version "1.8.0_40-internal"
OpenJDK Runtime Environment (build 1.8.0_40-internal-b04)
OpenJDK Zero VM (build 25.40-b08, interpreted mode)
```

Is there any workaround or I have to start it on another machine ?

**Comment by i9hdkill** [comment]
Use 64 bit on your Pi if possible

**Comment by lapin-b** [comment]
@i9hdkill Using a 64 bit on my Pi will implicate a complete reinstall of the system and I don't seem to be able to get my hands on a 64 bit build of Raspbian.

I could try a temporary solution but the main computer is most of the times down which is not very convenient for a 24/7 Bungeecord server with people wanting to be able to access a Minecraft server at any time.

**Comment by md-5** [comment]
Is build 1222 fine?

**Comment by md-5** [comment]
FYI the Raspberry Pi is woefully underpowered for anything Minecraft related and in general not supported

**Comment by lapin-b** [comment]
I tried build `#1222` and it works. At least, it starts ^^

Thanks for your help :smile:
