### ISSUE TITLE
Cancel server joining raised Exception

### ISSUE THREAD

**Issue by KleinCrafter** [SpigotMC/BungeeCord#2066]
Join the Server and click "Cancel" very fast raised this Exception:

19:13:51 [INFORMATION] [/87.157.20.6:33716] <-> InitialHandler has connected
19:13:52 [SCHWERWIEGEND] Feb 13, 2017 7:13:52 PM io.netty.util.concurrent.AbstractEventExecutor safeExecute
WARNUNG: A task raised an exception. Task: net.md_5.bungee.connection.InitialHandler$6$1@2c6bcd42
java.util.NoSuchElementException: packet-encoder
    at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1080)
    at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:251)
    at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:240)
    at net.md_5.bungee.netty.ChannelWrapper.addBefore(ChannelWrapper.java:115)
    at net.md_5.bungee.netty.ChannelWrapper.setCompressionThreshold(ChannelWrapper.java:127)
    at net.md_5.bungee.UserConnection.setCompressionThreshold(UserConnection.java:630)
    at net.md_5.bungee.connection.InitialHandler$6$1.run(InitialHandler.java:504)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
    at java.lang.Thread.run(Thread.java:745)

**Comment by md-5** [comment]
No version provided
