### ISSUE TITLE
Potential Memory Leak on Bungeecord

### ISSUE THREAD

**Issue by k-jiang** [SpigotMC/BungeeCord#2113]
(This issue occurs on Waterfall, but I am not sure if it is a BungeeCord issue or Waterfall. So I just put it here. https://github.com/WaterfallMC/Waterfall/issues/130)
Player could not join any server with error message "The server you were previously on went down, you have been connected to a fallback server". Noticed that all my backend servers (Spigot) are working fine and ppl join from the another BungeeCord instance have no issue.
This is what the log looks like when join (IP address wiped out):
```
02:12:11 [INFO] [REN6|/24.xx.xx.xx:56867] <-> ServerConnector [survival] has connected
02:12:11 [SEVERE] [/24.xx.xx.xx:56867|REN6] <-> DownstreamBridge <-> [survival] - encountered exception
io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 251658247, max: 261750784)
    at io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:585)
    at io.netty.util.internal.PlatformDependent.allocateDirectNoCleaner(PlatformDependent.java:539)
    at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:760)
    at io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:736)
    at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:244)
    at io.netty.buffer.PoolArena.allocate(PoolArena.java:226)
    at io.netty.buffer.PoolArena.reallocate(PoolArena.java:397)
    at io.netty.buffer.PooledByteBuf.capacity(PooledByteBuf.java:118)
    at io.netty.buffer.AbstractByteBuf.ensureWritable0(AbstractByteBuf.java:284)
    at io.netty.buffer.AbstractByteBuf.ensureWritable(AbstractByteBuf.java:265)
    at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1036)
    at net.md_5.bungee.jni.zlib.JavaZlib.process(JavaZlib.java:70)
    at net.md_5.bungee.compress.PacketDecompressor.decode(PacketDecompressor.java:47)
    at net.md_5.bungee.compress.PacketDecompressor.decode(PacketDecompressor.java:13)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:280)
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:396)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:624)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
    at java.lang.Thread.run(Thread.java:745)
02:12:11 [INFO] [REN6] disconnected with: The server you were previously on went down, you have been connected to a fallback server
02:12:11 [INFO] [/24.xx.xx.xx:56867|REN6] <-> DownstreamBridge <-> [survival] has disconnected
02:12:12 [INFO] [/24.xx.xx.xx:56867|REN6] -> UpstreamBridge has disconnected
```
My server still has 240MB free ram at that moment. I set the maximum memory Xmx to 512MB in a 750MB machine. this server runs BungeeCord only. One more thing I should mention is the latency between this BC and my Spigot is 130ms. It works fine until upgraded to build 1229 recently.

Version of BungeeCord: Waterfall build 105.
Server: Ubuntu 16.04 LTS x64
Plugins installed: BungeeAuthMeBridge, BungeeTabListPlus, FastLogin, fix-worldedit-cui, RedisBungee.

**Comment by k-jiang** [comment]
Also, this pops up when the first player join the network after BC restarted. DK if it is related:
```
02:27:49 [SEVERE] java.lang.Throwable: Using a io.netty.buffer.PooledUnsafeHeapByteBuf, not a direct byte buf!
02:27:49 [SEVERE]     at net.md_5.bungee.protocol.Varint21FrameDecoder.decode(Varint21FrameDecoder.java:54)
02:27:49 [SEVERE]     at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
02:27:49 [SEVERE]     at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
02:27:49 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
02:27:49 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
02:27:49 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
02:27:49 [SEVERE]     at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
02:27:49 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
02:27:49 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
02:27:49 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
02:27:49 [SEVERE]     at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287)
02:27:49 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
02:27:49 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
02:27:49 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
02:27:49 [SEVERE]     at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
02:27:49 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
02:27:49 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
02:27:49 [SEVERE]     at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
02:27:49 [SEVERE]     at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
02:27:49 [SEVERE]     at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:624)
02:27:49 [SEVERE]     at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559)
02:27:49 [SEVERE]     at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476)
02:27:49 [SEVERE]     at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)
02:27:49 [SEVERE]     at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
02:27:49 [SEVERE]     at java.lang.Thread.run(Thread.java:745)
```

**Comment by MClausz** [comment]
same issue

**Comment by MClausz** [comment]
Wait this is a Waterfall's issue (latest development build), it seems fine after switching to BungeeCord.

**Comment by k-jiang** [comment]
Ops... It looks like I posted it on the wrong resource... Let me copy it to the Waterfall...
Sorry guys.

**Comment by k-jiang** [comment]
Will closed this if it is confirmed to be a Waterfall issue.

**Comment by md-5** [comment]
Please don't open bungeecord issues if you are not using bungeecord
