### ISSUE TITLE
Player disconnect : java.lang.IndexOutOfBoundsException: readerIndex(39) + length(1) exceeds writerIndex(39)

### ISSUE THREAD

**Issue by txgs888** [SpigotMC/BungeeCord#2128]
My server recently appeared on this issue, the player was kicked out by the server.
My BungeeCord is the latest version
The number of online players dropped from 2000 to 1500.
Players are cursing me.
please help me!

[config.yml](http://i1.piimg.com/519918/06e3f3fafb23caba.png)
[plugins](http://i4.buimg.com/519918/bfe70b6dad2ba1ae.png)

`14:24:36 [严重] [yetongshuo] <-> DownstreamBridge <-> [lobby1] - encountered exception
io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(39) + length(1) exceeds writerIndex(39): UnpooledSlicedByteBuf(ridx: 39, widx: 39, cap: 39/39, unwrapped: PooledUnsafeDirectByteBuf(ridx: 40, widx: 40, cap: 240))
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:1017)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:394)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:299)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(39) + length(1) exceeds writerIndex(39): UnpooledSlicedByteBuf(ridx: 39, widx: 39, cap: 39/39, unwrapped: PooledUnsafeDirectByteBuf(ridx: 40, widx: 40, cap: 240))
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1396)
	at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:687)
	at net.md_5.bungee.protocol.DefinedPacket.readVarInt(DefinedPacket.java:108)
	at net.md_5.bungee.protocol.DefinedPacket.readVarInt(DefinedPacket.java:98)
	at net.md_5.bungee.protocol.DefinedPacket.readString(DefinedPacket.java:29)
	at net.md_5.bungee.protocol.packet.PlayerListItem.read(PlayerListItem.java:39)
	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:33)
	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:10)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
	... 21 more`

**Comment by md-5** [comment]
This generally occurs with broken tab list plugins. Please ensure you are not running any tab list plugins on the servers.

**Comment by txgs888** [comment]
@md-5 
I have removed the tab list plugins plugin, but still have an error.
[https://i4.buimg.com/504241/70e164437427412e.png](https://i4.buimg.com/504241/70e164437427412e.png)

**Comment by txgs888** [comment]
The player client displays the content:
[https://i2.muimg.com/504241/ffbd85b93ebe3988.png](https://i2.muimg.com/504241/ffbd85b93ebe3988.png)

**Comment by md-5** [comment]
I really can't help unless the issue occurs with no plugins at all. I do believe this is a server plugin sending invalid data. Possibly an issue with specifically your lobby2 server

**Comment by txgs888** [comment]
Well, I found the reason, and I wrote a skin plugin that led to this error. Thank you.

**Comment by josecuervo2019** [comment]
Hi, how did you do to fix that error? Thank you

o.netty.handler.codec.DecoderException: Error decoding packet class Handshake with contents:
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 00 0e 79 46 69 68 5f 54 47 57 61 6c 6b 65 72 5f |..yFih_TGWalker_|
+--------+-------------------------------------------------+----------------+
	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:68) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:12) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.handler.codec.ByteToMessageDecoder.handlerRemoved(ByteToMessageDecoder.java:236) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:494) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1414) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:945) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:404) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(3) + length(121) exceeds writerIndex(16): UnpooledSlicedByteBuf(ridx: 3, widx: 16, cap: 16/16, unwrapped: PooledUnsafeDirectByteBuf(ridx: 17, widx: 17, cap: 17))

**Comment by Black-Hole** [comment]
That is no error and it needs no fixing. You're using Waterfall, a fork of BungeeCord that logs the contents of packets that don't conform to the protocol. As Minecraft is using TCP sockets, any device can connect to that socket and send whatever data it likes. 

For help configuring your server and your plugin please use the community support of the Spigot forums, as this issue tracker is not for support.
