### ISSUE TITLE
[GRAVE] java.io.EOFException

### ISSUE THREAD

**Issue by Lemrigue** [SpigotMC/BungeeCord#2161]
Everything seems to work but this error keep appearing quite often on the bungee console (I'm using the latest build)

```
23:32:08 [GRAVE] java.io.EOFException
23:32:08 [GRAVE] 	at java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:2601)
23:32:08 [GRAVE] 	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1319)
23:32:08 [GRAVE] 	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
23:32:08 [GRAVE] 	at com.gmail.thelimeglass.BungeeEventRunner.send(BungeeEventRunner.java:21)
23:32:08 [GRAVE] 	at com.gmail.thelimeglass.BungeeEventListener.onChat(BungeeEventListener.java:63)
23:32:08 [GRAVE] 	at sun.reflect.GeneratedMethodAccessor30.invoke(Unknown Source)
23:32:08 [GRAVE] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
23:32:08 [GRAVE] 	at java.lang.reflect.Method.invoke(Method.java:497)
23:32:08 [GRAVE] 	at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
23:32:08 [GRAVE] 	at net.md_5.bungee.event.EventBus.post(EventBus.java:46)
23:32:08 [GRAVE] 	at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:377)
23:32:08 [GRAVE] 	at net.md_5.bungee.connection.UpstreamBridge.handle(UpstreamBridge.java:117)
23:32:08 [GRAVE] 	at net.md_5.bungee.protocol.packet.Chat.handle(Chat.java:50)
23:32:08 [GRAVE] 	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:78)
23:32:08 [GRAVE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
23:32:08 [GRAVE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
23:32:08 [GRAVE] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
23:32:08 [GRAVE] 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
23:32:08 [GRAVE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
23:32:08 [GRAVE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
23:32:08 [GRAVE] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
23:32:08 [GRAVE] 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
23:32:08 [GRAVE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
23:32:08 [GRAVE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
23:32:08 [GRAVE] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
23:32:08 [GRAVE] 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
23:32:08 [GRAVE] 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
23:32:08 [GRAVE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
23:32:08 [GRAVE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
23:32:08 [GRAVE] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
23:32:08 [GRAVE] 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287)
23:32:08 [GRAVE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
23:32:08 [GRAVE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
23:32:08 [GRAVE] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
23:32:08 [GRAVE] 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
23:32:08 [GRAVE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
23:32:08 [GRAVE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
23:32:08 [GRAVE] 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
23:32:08 [GRAVE] 	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:1017)
23:32:08 [GRAVE] 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:394)
23:32:08 [GRAVE] 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:299)
23:32:08 [GRAVE] 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
23:32:08 [GRAVE] 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by i9hdkill** [comment]
`at com.gmail.thelimeglass.BungeeEventRunner.send(BungeeEventRunner.java:21)`

Keeep your plugins up to date. Try without that plugin.
