### ISSUE TITLE
Outdated Server when 1.12 connection

### ISSUE THREAD

**Issue by anthonyhou04** [SpigotMC/BungeeCord#2176]
Hi, I am updating my bungeecord server from 1.11 to 1.12.But when I connect to my server, a 'Outdated Server!' error will show in my Minecraft Client.
I can connect to my server individually when Bungeecord mode is disabled.
Minecraft server version: 1.12
Bungeecord build: #1243 
Bungeecord config
```
player_limit: -1
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
timeout: 30000
log_commands: false
online_mode: false
disabled_commands:
- disabledcommandhere
servers:
  hub:
    motd: '&d7B &9Server'
    address: 192.168.99.213:25500
    restricted: false
  old:
    motd: '&d7B &9Server'
    address: 192.168.99.213:24400
    restricted: false
  survival:
    motd: '&d7B &9Server'
    address: 192.168.99.213:23300
    restricted: false
  minigames:
    motd: '&d7B &9Server'
    address: 192.168.99.213:22200
    restricted: false
  map1:
    motd: '&d7B &9Server'
    address: 192.168.99.213:21100
    restricted: false
  plot:
    motd: '&d7B &9Server'
    address: 192.168.99.213:20000
    restricted: false
listeners:
- query_port: 25577
  motd: '&d7B &9Server'
  priorities:
  - hub
  bind_local_address: true
  tab_list: GLOBAL_PING
  query_enabled: false
  host: 0.0.0.0:25565
  forced_hosts:
    mc.6p4ever.website: hub
  max_players: 20
  tab_size: 60
  ping_passthrough: false
  force_default_server: false
ip_forward: true
network_compression_threshold: 256
groups:
  TestingPlayer:
  - admin
connection_throttle: 4000
stats: 2073eaf8-9510-4a6c-92ac-34db860512cc
prevent_proxy_connections: false
```
log
```
05:33:53 [INFO] Using OpenSSL based native cipher.
05:33:53 [INFO] Using native code compressor
05:33:53 [INFO] Enabled BungeeCord version git:BungeeCord-Bootstrap:1.12-SNAPSHOT:e26b937:1236
05:33:53 [INFO] Not on Windows, attempting to use enhanced EpollEventLoop
05:33:53 [INFO] Epoll is working, utilising it!
05:33:54 [INFO] Discovered module: ModuleSpec(name=cmd_alert, file=modules/cmd_alert.jar, provider=JenkinsModuleSource())
05:33:54 [INFO] Discovered module: ModuleSpec(name=cmd_find, file=modules/cmd_find.jar, provider=JenkinsModuleSource())
05:33:54 [INFO] Discovered module: ModuleSpec(name=cmd_list, file=modules/cmd_list.jar, provider=JenkinsModuleSource())
05:33:54 [INFO] Discovered module: ModuleSpec(name=cmd_send, file=modules/cmd_send.jar, provider=JenkinsModuleSource())
05:33:54 [INFO] Discovered module: ModuleSpec(name=cmd_server, file=modules/cmd_server.jar, provider=JenkinsModuleSource())
05:33:54 [INFO] Discovered module: ModuleSpec(name=reconnect_yaml, file=modules/reconnect_yaml.jar, provider=JenkinsModuleSource())
05:33:54 [INFO] Loaded plugin reconnect_yaml version git:reconnect_yaml:1.12-SNAPSHOT:e26b937:1236 by SpigotMC
05:33:54 [INFO] §f§7§l[§bL§3P§7§l] §3Identified the following dependencies: [CAFFEINE]
05:33:54 [INFO] Loaded plugin LuckPerms version 3.2.12 by Luck
05:33:54 [INFO] Loaded plugin SkinsRestorer version 13.0.2 by Th3Tr0LLeR
05:33:54 [INFO] Loaded plugin DeluxeChatBungee version 1.12.2 by extended_clip
05:33:54 [INFO] Loaded plugin cmd_list version git:cmd_list:1.12-SNAPSHOT:e26b937:1236 by SpigotMC
05:33:54 [INFO] Loaded plugin cmd_find version git:cmd_find:1.12-SNAPSHOT:e26b937:1236 by SpigotMC
05:33:54 [INFO] Loaded plugin CommandSync version 2.3 by YoFuzzy3
05:33:54 [INFO] Loaded plugin cmd_server version git:cmd_server:1.12-SNAPSHOT:e26b937:1236 by SpigotMC
05:33:54 [INFO] Loaded plugin LiteBans version 2.2.3 by Ruan
05:33:54 [INFO] Loaded plugin cmd_alert version git:cmd_alert:1.12-SNAPSHOT:e26b937:1236 by SpigotMC
05:33:54 [INFO] Loaded plugin cmd_send version git:cmd_send:1.12-SNAPSHOT:e26b937:1236 by SpigotMC
05:33:54 [INFO] Loaded plugin BungeeWideChat version 1.0.1 by L_Lolipop
05:33:54 [INFO] Loaded plugin BungeeTabListPlus version 2.7.4 by CodeCrafter47
05:33:54 [INFO] Enabled plugin reconnect_yaml version git:reconnect_yaml:1.12-SNAPSHOT:e26b937:1236 by SpigotMC
05:33:54 [INFO] §f§b               __       §3 __   ___  __         __  
05:33:54 [INFO] §f§b    |    |  | /  ` |__/ §3|__) |__  |__)  |\/| /__` 
05:33:54 [INFO] §f§b    |___ \__/ \__, |  \ §3|    |___ |  \  |  | .__/ 
05:33:54 [INFO] §f 
05:33:54 [INFO] §f§2  Loading version §bv3.2.12§2 on Bungee - BungeeCord
05:33:54 [INFO] §f§8  Running on server version git:BungeeCord-Bootstrap:1.12-SNAPSHOT:e26b937:1236
05:33:54 [INFO] §f 
05:33:54 [INFO] §f§7§l[§bL§3P§7§l] §3Loading configuration...
05:33:54 [INFO] §f§7§l[§bL§3P§7§l] §3Identified the following dependencies: [MARIADB_DRIVER, SLF4J_API, SLF4J_SIMPLE, HIKARI]
05:33:54 [INFO] §f§7§l[§bL§3P§7§l] §3Loading storage provider... [MARIADB]
05:33:54 [SEVERE] [main] INFO com.zaxxer.hikari.HikariDataSource - luckperms - Starting...
05:33:54 [SEVERE] [main] INFO com.zaxxer.hikari.HikariDataSource - luckperms - Start completed.
05:33:55 [INFO] §f§7§l[§bL§3P§7§l] §3Loading internal permission managers...
05:33:55 [INFO] §f§7§l[§bL§3P§7§l] §3Performing initial data load...
05:33:55 [INFO] §f§7§l[§bL§3P§7§l] §3Successfully enabled.
05:33:55 [INFO] Enabled plugin LuckPerms version 3.2.12 by Luck
05:33:55 [INFO] Enabled plugin SkinsRestorer version 13.0.2 by Th3Tr0LLeR
05:33:55 [INFO] Enabled plugin DeluxeChatBungee version 1.12.2 by extended_clip
05:33:55 [INFO] Enabled plugin cmd_list version git:cmd_list:1.12-SNAPSHOT:e26b937:1236 by SpigotMC
05:33:55 [INFO] Enabled plugin cmd_find version git:cmd_find:1.12-SNAPSHOT:e26b937:1236 by SpigotMC
05:33:55 [INFO] [CommandSync] Configuration file loaded.
05:33:55 [INFO] [CommandSync] !!! THE CONFIG FILE CONTAINS UNSET VALUES - YOU MUST FIX THEM BEFORE THE PLUGIN WILL WORK !!! 
05:33:55 [INFO] Enabled plugin CommandSync version 2.3 by YoFuzzy3
05:33:55 [INFO] Enabled plugin cmd_server version git:cmd_server:1.12-SNAPSHOT:e26b937:1236 by SpigotMC
05:33:56 [INFO] 
05:33:56 [INFO] §a    +===============+
05:33:56 [INFO] §a    | SkinsRestorer |
05:33:56 [INFO] §a    +===============+
05:33:56 [INFO] 
05:33:56 [INFO] §b    Current version: §c13.0.2
05:33:56 [INFO] §c    A new version is available! Download it at:
05:33:56 [INFO] §e    https://www.spigotmc.org/resources/skinsrestorer.2124
05:33:56 [INFO] 
05:33:57 [INFO] [LiteBans] Loading SQL driver: mysql (com.mysql.jdbc.Driver)
05:33:57 [INFO] [LiteBans] Connecting to database...
05:33:58 [INFO] [LiteBans] Connected to [jdbc:mysql://localhost:3306/mcglobal?useSSL=false] (671.7 ms).
05:33:58 [INFO] [LiteBans] [Sync] Server name: litebans
05:33:58 [INFO] [LiteBans] [Sync] Server UUID: 5336a903752e40aaaa42115d9698b581
05:33:58 [INFO] [LiteBans] Database connection fully initialized (723.4 ms).
05:33:58 [INFO] [LiteBans] v2.2.3 enabled. Startup took 2290 ms.
05:33:58 [INFO] Enabled plugin LiteBans version 2.2.3 by Ruan
05:33:58 [INFO] Enabled plugin cmd_alert version git:cmd_alert:1.12-SNAPSHOT:e26b937:1236 by SpigotMC
05:33:58 [INFO] Enabled plugin cmd_send version git:cmd_send:1.12-SNAPSHOT:e26b937:1236 by SpigotMC
05:33:58 [INFO] Enabled plugin BungeeWideChat version 1.0.1 by L_Lolipop
05:33:58 [INFO] [BungeeTabListPlus] Starting UpdateChecker Task
05:33:58 [INFO] [BungeeTabListPlus] Loading default.yml
05:33:59 [WARNING] [BungeeTabListPlus] Failed to load default.yml
Cannot create property=components for JavaBean=codecrafter47.bungeetablistplus.config.FixedSizeConfig@1f387978
 in 'reader', line 16, column 1:
    showTo: "all"
    ^
Failed to validate config
 in 'reader', line 167, column 3:
    - !animated # 19th row, 1st column
      ^
com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;Ljava/lang/Object;)V

 in 'reader', line 131, column 1:
    - {text: "&cServer: &6${viewer s ... 
    ^

	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:307)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:189)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182)
	at codecrafter47.bungeetablistplus.yamlconfig.YamlConfig$MyConstructor.constructObject(YamlConfig.java:239)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:141)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:127)
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:481)
	at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:441)
	at codecrafter47.bungeetablistplus.yamlconfig.YamlConfig.read(YamlConfig.java:100)
	at codecrafter47.bungeetablistplus.yamlconfig.YamlConfig.read(YamlConfig.java:96)
	at codecrafter47.bungeetablistplus.managers.TabListManager.loadTabLists(TabListManager.java:80)
	at codecrafter47.bungeetablistplus.BungeeTabListPlus.onEnable(BungeeTabListPlus.java:368)
	at codecrafter47.bungeetablistplus.BungeePlugin.onEnable(BungeePlugin.java:40)
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:227)
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:273)
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:55)
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: Failed to validate config
 in 'reader', line 167, column 3:
    - !animated # 19th row, 1st column
      ^
com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;Ljava/lang/Object;)V

	at codecrafter47.bungeetablistplus.yamlconfig.YamlConfig$MyConstructor.constructObject(YamlConfig.java:244)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructSequenceStep2(BaseConstructor.java:275)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructSequence(BaseConstructor.java:246)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructSequence.construct(Constructor.java:523)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182)
	at codecrafter47.bungeetablistplus.yamlconfig.YamlConfig$MyConstructor.constructObject(YamlConfig.java:239)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:297)
	... 16 more
Caused by: java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;Ljava/lang/Object;)V
	at codecrafter47.bungeetablistplus.config.components.AnimatedComponent.validate(AnimatedComponent.java:70)
	at codecrafter47.bungeetablistplus.yamlconfig.YamlConfig$MyConstructor.constructObject(YamlConfig.java:242)
	... 22 more
05:33:59 [INFO] Enabled plugin BungeeTabListPlus version 2.7.4 by CodeCrafter47
05:33:59 [INFO] Listening on /0.0.0.0:25565
05:34:36 [INFO] [/183.240.202.30:34841] <-> InitialHandler has connected
05:34:36 [INFO] [/183.240.202.30:34840] <-> InitialHandler has connected
05:34:39 [INFO] [/183.240.202.30:34842] <-> InitialHandler has connected

```
Bungeecord plugin that I am using
-BungeeTabListPlus
-CommandSync
-LiteBans
-LuckPerms
-SkinsRestorer
-BungeeWideChat

**Comment by anthonyhou04** [comment]
What can be wrong in this config?

**Comment by Janmm14** [comment]
-> spigotmc.org forum for help

**Comment by anthonyhou04** [comment]
FIXED, thanks
