### ISSUE TITLE
how to link 2 or more bungeeCord server

### ISSUE THREAD

**Issue by friishon** [SpigotMC/BungeeCord#2181]
i have 2 bungeeCord servers, but when i try to link le frist, with the seccond, i have an error, and i can't connect because the console tell than this server is in online mode and i have this error

20:30:32 [GRAVE] [friishon] <-> ServerConnector [eggwars] - encountered exception
java.lang.RuntimeException: Server is online mode!
    at net.md_5.bungee.ServerConnector.handle(ServerConnector.java:270)
    at net.md_5.bungee.protocol.packet.EncryptionRequest.handle(EncryptionRequest.java:42)
    at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:78)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:1017)
    at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:394)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:299)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
    at java.lang.Thread.run(Thread.java:748)

i would like to have a bungee server with lobby, survival, skyblock, and then create another bungee server for eggwars, and link the eggwars bungeecord to the frist bungeecord, can someone help me?

**Comment by ApocalypsjeNL** [comment]
You can't link 2 bungeecord servers tot each other

**Comment by friishon** [comment]
O_O so, i only can have one bungeeCord server?

**Comment by EmanYm** [comment]
You have a bungeecord server and a play server.
You can not run a map on bungeecord and connect to it.  This is only for the proxy
You need to have spigot/bukkit/sponge server to run the game on and set it so players are sent to the play server.

[Read the documentation](https://www.spigotmc.org/wiki/bungeecord/)

**Comment by friishon** [comment]
no no, i have different spigot server linked to one bungeecord, but i would like to make a eggwars (bungee mode) and i need to make a bungee server for the eggwars, then, i have to link the eggwars to the principal bungee server, but i can't

**Comment by ninja-** [comment]
![](http://e.lvme.me/pzv5j7l.jpg)

**Comment by friishon** [comment]
How hypixel or cubecraft doing that, they have more than one proxy connect i think

**Comment by ApocalypsjeNL** [comment]
They have custom bungeecord builds and they hide the servers for the players

**Comment by friishon** [comment]
I think bungee need this thing for making better server

**Comment by Black-Hole** [comment]
Just use one BungeeCord server. Ask the plugin author of the eggwars plugin how to specify which servers to use and which not.

**Comment by friishon** [comment]
I found this: https://www.spigotmc.org/resources/redisbungee.13494/
I will try to make redis bungee
