### ISSUE TITLE
Events aren't working at all

### ISSUE THREAD

**Issue by funniray** [SpigotMC/BungeeCord#2291]
Whenever I try to listen for any events I get this error in my console
Bungeecord version: `git:BungeeCord-Bootstrap:1.12-SNAPSHOT:cccbb3c:1282`
```
WARNING: A task raised an exception. Task: net.md_5.bungee.connection.InitialHandler$6$1@221016f0
java.lang.Error: Method became inaccessible: PostLoginEvent(player=SolerNewSky)
    at net.md_5.bungee.event.EventBus.post(EventBus.java:49)
    at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:377)
    at net.md_5.bungee.connection.InitialHandler$6$1.run(InitialHandler.java:507)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalAccessException: Class net.md_5.bungee.event.EventHandlerMethod can not access a member of class pro.kdray.splashbot.ChatHandler with modifiers "public"
    at sun.reflect.Reflection.ensureMemberAccess(Unknown Source)
    at java.lang.reflect.AccessibleObject.slowCheckMemberAccess(Unknown Source)
    at java.lang.reflect.AccessibleObject.checkAccess(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
    at net.md_5.bungee.event.EventBus.post(EventBus.java:46)
    ... 7 more
```

My code is just

OnEnable:
```Java
getProxy().getPluginManager().registerListener(this, new ChatHandler());
```

And 
ChatHandler:
```Java
@EventHandler
public void onPostLogin(PostLoginEvent event) {
    for (ProxiedPlayer player : ProxyServer.getInstance().getPlayers()) {
        player.sendMessage(new TextComponent(event.getPlayer().getName() + " has joined the network."));
    }
}
```

I'm not sure if this is because of my coding issue or an issue on Bungeecord's side. It does this when the handler is both public and private on both Bungeecord and Waterfall. I'm not sure if this issue is in older versions of Bungeecord but this is my first time experimenting with the API and I can't get it to work at all.

Thanks for your help and making this amazing proxy for Minecraft!

**Comment by Janmm14** [comment]
The class ChatHandler needs to be public.

**Comment by funniray** [comment]
Oh, that would make sense, didn’t think of that... It is weird because I’m used to Bukkit and it doesn’t care if it  is private or public..
