### ISSUE TITLE
other error how fix this?

### ISSUE THREAD

**Issue by josecuervo2016** [SpigotMC/BungeeCord#2308]
12:20:30 [SEVERE] Dec 21, 2017 12:20:30 PM io.netty.util.concurrent.DefaultPromise notifyListener0
WARNING: An exception was thrown by eu.the5zig.reconnect.ReconnectTask$1.operationComplete()
java.lang.NoSuchMethodError: net.md_5.bungee.protocol.packet.KeepAlive.<init>(I)V
	at eu.the5zig.reconnect.ReconnectTask$1.operationComplete(ReconnectTask.java:123)
	at eu.the5zig.reconnect.ReconnectTask$1.operationComplete(ReconnectTask.java:102)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:500)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:479)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:122)
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.fulfillConnectPromise(AbstractEpollChannel.java:633)
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:652)
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:526)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:394)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:748)

**Comment by i9hdkill** [comment]
Not a bungee issue. Update or remove "the5zig.reconnect"
