### ISSUE TITLE
how fix this error thank you

### ISSUE THREAD

**Issue by josecuervo2016** [SpigotMC/BungeeCord#2330]
02:23:23 [SEVERE]  <-> DownstreamBridge <-> [lobby-1] - encountered exception
java.lang.IllegalArgumentException: Team 0GHFEOPD already exists in this scoreboard
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191)
	at net.md_5.bungee.api.score.Scoreboard.addTeam(Scoreboard.java:68)
	at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:188)
	at net.md_5.bungee.protocol.packet.Team.handle(Team.java:102)
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:404)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at java.lang.Thread.run(Thread.java:748)

There is a plugin that hits me with its bungeecord, could you tell me what can be thanks. I give you the list of my lobby plugins

Plugins :JumpSlime, AnimationLib, WorldEdit, NoRain, Languages, PlayerSettings, Essentials, LobbyProtection, SonezSpawnJoin, SpigotUpdater, IPWhitelist, EssentialsChat, PermissionsEx, FeatherBoard, MicroJump, ViaVersion, NetworkLevels, SuperDeliveryMan, CustomJoinItems, Vault, AnimatedMenu, MysqlEcoBridge, PlayTimeRewards, ProtocolLib, NoCheatPlus, LibsDisguises, Citizens, React, CommandNPC, BossShop, CustomPayloadFixer, CrashFix, GadgetsMenu, HolographicDisplays

**Comment by Mystiflow** [comment]
Probably FeatherBoard. You should remove plugins a few at a time to find the culprit.

**Comment by josecuervo2016** [comment]
Hi, I deleted it to the feather board plugin, and the damn fault keeps coming up ... I do not know what to do anymore

**Comment by ApocalypsjeNL** [comment]
Clear your scoreboards

**Comment by josecuervo2016** [comment]
delete the scoreboard.dat, delete the feather board, and follow the blessed error :(

**Comment by josecuervo2016** [comment]
hello it was nothing of that I went crazy .. the error was given by the super delivey man plugin that I already made my complaint .. now for sure he will tell me that it is the bungee's fault

**Comment by uniqueusernamelol** [comment]
similar problem
java.lang.IllegalArgumentException: Objective §4Deaths already exists in this scoreboard

**Comment by uniqueusernamelol** [comment]
people get randomly kicked and it is so annoying
