### ISSUE TITLE
io.netty.handler.codec.MessageToMessageDecoder:98

### ISSUE THREAD

**Issue by andfont** [SpigotMC/BungeeCord#2337]
help please, this error is coming out and only happens to me when the player enters by bungeecord, but if it does not work perfectly, it is a 1.12.2 server but with 1.9.2 it works perfectly, so it only happens with 1.12.2, please help the bungee cord disconnect players when rendering according to which error objects:
DecoderException: java.lang.IndexOutOfBoundsException: readerIndex (0) + length (1) exceeds writerIndex (0): UnpooledSlicedByteBuf (ridx: 0, widx: 0, chap: 0/0, unwrapped: PooledUnsafeDirectByteBuf (ridx: 2, widx: 2 , cap: 384)) @ io.netty.handler.codec.MessageToMessageDecoder: 98
More information:
io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(0) + length(1) exceeds writerIndex(0): UnpooledSlicedByteBuf(ridx: 0, widx: 0, cap: 0/0, unwrapped: PooledUnsafeDirectByteBuf(ridx: 2, widx: 2, cap: 192))
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:141)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(0) + length(1) exceeds writerIndex(0): UnpooledSlicedByteBuf(ridx: 0, widx: 0, cap: 0/0, unwrapped: PooledUnsafeDirectByteBuf(ridx: 2, widx: 2, cap: 192))
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1403)
	at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:707)
	at net.md_5.bungee.protocol.DefinedPacket.readVarInt(DefinedPacket.java:108)
	at net.md_5.bungee.protocol.DefinedPacket.readVarInt(DefinedPacket.java:98)
	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:28)
	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:10)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
	... 27 more

**Comment by md-5** [comment]
Please reproduce without plugins

**Comment by Fejm** [comment]
It happends randomly on 1.12.2
Server is sending packet with corrupted packet id, with or without plugins, just create scoreboard, spawn some entities and start switching servers. 

It's a pain to reproduce but it should occur.

I used this: https://github.com/WaterfallMC/Waterfall/pull/187 and it works.

**Comment by md-5** [comment]
It doesn’t occurr. Nothing in the vanilla server sends an empty packet which is what this is, it’s historically always been dodgy protocol compat software.

Ignoring rubbish data from the server is not a fix, you find and remove what is causing that bad data

**Comment by Fejm** [comment]
Well, it does not happen on 1.11 and previous, upgraded to 1.12.2 and boom. I'm not using any part of viaversion or other shit stuff. Only 1.12.2 protocol. Ofc im sending some entities via ProtocolLib on lobbies but it was working on 1.11 and 1.10

Maybe it's a bug on protocollib but somehow it also occurr on our Auth (offline mode) lobby where is only one plugin who is not touching protocol.

I spend hours looking into this issue and found nothing..

**Comment by Fejm** [comment]
EnumProtocol change can cause this? I looked into this and sometimes spigot changes EnumProtocol from LOGIN -> PLAY -> LOGIN -> PLAY -> PLAY (race condition?), 

PLAY -> LOGIN is caused by ProtocolLib and some packets sent too early, but client seems to ignore those stuff, what about bungee?

I managed to get SetCompression sent in PLAY state.

**Comment by md-5** [comment]
>LOGIN -> PLAY -> LOGIN -> PLAY -> PLAY 

If this is happening on a clean Spigot server, file a bug report there.
I doubt it though, sounds like an issue with protocollib. Just because the client tolerates some plugin generated garbage, doesn't mean bungee should.

**Comment by Fejm** [comment]
Found issue causing Bungee to throw this exception: async call to player.playSound(); especially when using ProtocolLib and canceling some packet's (eg. USE_ENTITY)
After changing it to sync it's working.

However when i downgraded packet decoder by reverting this commit: https://github.com/SpigotMC/BungeeCord/commit/ddfd76ebdab50212affff2fe1ed4532be8fa8b3c it's working. I'm not sure how this is related.

I did this becouse our old server was 1.7/1.8 and we used old Bungee fork where everything was working fine.

**Comment by kiritoKazuto242** [comment]
I'm sorry but I don't understand why I can't join a server. the error it tells me is this:
 Exception Connecting: DecoderExecption: Java.lang.UnsupportedOperationException: 
Packet must implement read method@
io.netty.handler.codec.MessageToMessageDecoder:98

**Comment by Janmm14** [comment]
@kiritoKazuto242
What made you think this unrelated issue from 2018 is the correct place for your problem? Create a new issue, provide the neccessary details and console log, etc etc.

**Comment by kiritoKazuto242** [comment]
ok thanks

**Comment by kiritoKazuto242** [comment]
![Screenshot_20240113_150313](https://github.com/SpigotMC/BungeeCord/assets/156519261/4519e637-09fd-49d8-8fef-125d14f2c1a7)

**Comment by Fejm** [comment]
Do not write here. Man..

**Comment by Janmm14** [comment]
![grafik](https://github.com/SpigotMC/BungeeCord/assets/3533175/0e08f671-a129-40e3-8654-8e25d54a13a6)
