### ISSUE TITLE
Parrot Sound causes client crash when connecting to bungeecord servers.

### ISSUE THREAD

**Issue by KyleCG8094** [SpigotMC/BungeeCord#2350]
Players can connect to my Hub just fine, when they attempt to join any of the backend servers, they will sometimes crash. Its more of a 50/50 than anything. This is the stacktrace from the most recent crash log i received. I should also mention my server.properties has animal-spawning=false
Stacktrace:
    at net.minecraft.entity.player.EntityPlayer.playShoulderEntityAmbientSound(EntityPlayer.java:591)
    at net.minecraft.entity.player.EntityPlayer.onLivingUpdate(EntityPlayer.java:576)
    at net.minecraft.client.entity.EntityPlayerSP.onLivingUpdate(EntityPlayerSP.java:1011)
    at net.minecraft.entity.EntityLivingBase.onUpdate(EntityLivingBase.java:2167)
    at net.minecraft.entity.player.EntityPlayer.onUpdate(EntityPlayer.java:234)
    at net.minecraft.client.entity.EntityPlayerSP.onUpdate(EntityPlayerSP.java:181)
    at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1986)
    at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1948)

**Comment by md-5** [comment]
You appear to be using a modded client of some description. Please reproduce on an unmodified client.

**Comment by KyleCG8094** [comment]
the backend servers themselves are pixelmon. so players connect with that modded client. However the hub is normal spigot. Is there no support for modded clients/servers?

**Comment by md-5** [comment]
Non command interfaces function exactly the same unless something is weird.
Modded client support is on a best effort basis, as there are thousands of Mods which could all cause hugs like this.

BungeeCord doesn't touch sounds in any way which is what makes this more suspicious.

**Comment by KyleCG8094** [comment]
Well. I dont have the resources necessary to create a clean vanilla instance of this. Ill talk to the modpack devs again, They've heard of this issue before and have no idea what causes it nor how to fix it.
