### ISSUE TITLE
Could not bind to host /0.0.0.0:25577

### ISSUE THREAD

**Issue by TechnoCreeper2** [SpigotMC/BungeeCord#2412]
I can't fix this problem. Please help!
F:\Servers\Alive\NemerCraft\NemerBungee>title NemerBungee
20:56:08 [INFO] Using standard Java JCE cipher.
20:56:08 [INFO] Using standard Java compressor.
20:56:08 [INFO] Enabled BungeeCord version git:BungeeCord-Bootstrap:1.12-SNAPSHOT:fde2c3f:1310
20:56:08 [INFO] Discovered module: ModuleSpec(name=cmd_alert, file=modules\cmd_alert.jar, provider=JenkinsModuleSource())
20:56:08 [INFO] Discovered module: ModuleSpec(name=cmd_find, file=modules\cmd_find.jar, provider=JenkinsModuleSource())
20:56:08 [INFO] Discovered module: ModuleSpec(name=cmd_list, file=modules\cmd_list.jar, provider=JenkinsModuleSource())
20:56:08 [INFO] Discovered module: ModuleSpec(name=cmd_send, file=modules\cmd_send.jar, provider=JenkinsModuleSource())
20:56:08 [INFO] Discovered module: ModuleSpec(name=cmd_server, file=modules\cmd_server.jar, provider=JenkinsModuleSource())
20:56:08 [INFO] Discovered module: ModuleSpec(name=reconnect_yaml, file=modules\reconnect_yaml.jar, provider=JenkinsModuleSource())
20:56:08 [INFO] Loaded plugin reconnect_yaml version git:reconnect_yaml:1.12-SNAPSHOT:fde2c3f:1310 by SpigotMC
20:56:08 [INFO] Loaded plugin cmd_find version git:cmd_find:1.12-SNAPSHOT:fde2c3f:1310 by SpigotMC
20:56:08 [INFO] Loaded plugin cmd_server version git:cmd_server:1.12-SNAPSHOT:fde2c3f:1310 by SpigotMC
20:56:08 [INFO] Loaded plugin cmd_alert version git:cmd_alert:1.12-SNAPSHOT:fde2c3f:1310 by SpigotMC
20:56:08 [INFO] Loaded plugin cmd_send version git:cmd_send:1.12-SNAPSHOT:fde2c3f:1310 by SpigotMC
20:56:08 [INFO] Loaded plugin cmd_list version git:cmd_list:1.12-SNAPSHOT:fde2c3f:1310 by SpigotMC
20:56:08 [WARNING] Forced host server pvp is not defined
20:56:08 [INFO] Enabled plugin reconnect_yaml version git:reconnect_yaml:1.12-SNAPSHOT:fde2c3f:1310 by SpigotMC
20:56:08 [INFO] Enabled plugin cmd_find version git:cmd_find:1.12-SNAPSHOT:fde2c3f:1310 by SpigotMC
20:56:08 [INFO] Enabled plugin cmd_server version git:cmd_server:1.12-SNAPSHOT:fde2c3f:1310 by SpigotMC
20:56:08 [INFO] Enabled plugin cmd_alert version git:cmd_alert:1.12-SNAPSHOT:fde2c3f:1310 by SpigotMC
20:56:08 [INFO] Enabled plugin cmd_send version git:cmd_send:1.12-SNAPSHOT:fde2c3f:1310 by SpigotMC
20:56:08 [INFO] Enabled plugin cmd_list version git:cmd_list:1.12-SNAPSHOT:fde2c3f:1310 by SpigotMC
20:56:09 [WARNING] Could not bind to host /0.0.0.0:25577
java.net.BindException: Address already in use: bind
    at sun.nio.ch.Net.bind0(Native Method)
    at sun.nio.ch.Net.bind(Unknown Source)
    at sun.nio.ch.Net.bind(Unknown Source)
    at sun.nio.ch.ServerSocketChannelImpl.bind(Unknown Source)
    at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:128)
    at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:558)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1358)
    at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:501)
    at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:486)
    at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:1019)
    at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:254)
    at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:366)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
    at java.lang.Thread.run(Unknown Source)

**Comment by Black-Hole** [comment]
"20:56:09 [WARNING] Could not bind to host /0.0.0.0:25577
java.net.BindException: Address already in use: bind"

So the port is used already by another process. For help finding the process that is using that port please use the community support of the Spigot forums.
