### ISSUE TITLE
 The Ip Of My Server Is Existing But It Does Not Connect Me To The BungeeCord Help Only I Have 26 Days Of Hosting!

### ISSUE THREAD

**Issue by GameDankNetwork** [SpigotMC/BungeeCord#2429]
>01:57:18 [WARNING] Could not bind to host /158.69.116.80:40841
io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Cannot assign requested address
    at io.netty.channel.unix.Errors.newIOException(Errors.java:117)
    at io.netty.channel.unix.Socket.bind(Socket.java:234)
    at io.netty.channel.epoll.EpollDatagramChannel.doBind(EpollDatagramChannel.java:283)
    at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:554)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1258)
    at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:501)
    at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:486)
    at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:980)
    at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:250)
    at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:365)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
    at java.lang.Thread.run(Thread.java:748)

**Comment by md-5** [comment]
The ip you have configured is not available on your server, please use the forums for support.
