### ISSUE TITLE
Can someone help please?

### ISSUE THREAD

**Issue by Y3ko** [SpigotMC/BungeeCord#2467]
Anyone know this error? How can i fix it. It's spamming and no one join my server.

`13:04:10 [SEVERE] Jul 15, 2018 1:04:10 PM io.netty.util.concurrent.DefaultPromise notifyListener0
WARNING: An exception was thrown by net.md_5.bungee.UserConnection$3.operationComplete()
java.lang.IllegalStateException: channel not registered to an event loop
	at io.netty.channel.AbstractChannel.eventLoop(AbstractChannel.java:162)
	at io.netty.channel.AbstractChannelHandlerContext.executor(AbstractChannelHandlerContext.java:115)
	at io.netty.channel.AbstractChannelHandlerContext.newPromise(AbstractChannelHandlerContext.java:875)
	at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:465)
	at io.netty.channel.DefaultChannelPipeline.close(DefaultChannelPipeline.java:1003)
	at io.netty.channel.AbstractChannel.close(AbstractChannel.java:238)
	at net.md_5.bungee.UserConnection$3.operationComplete(UserConnection.java:320)
	at net.md_5.bungee.UserConnection$3.operationComplete(UserConnection.java:308)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:485)
	at io.netty.util.concurrent.DefaultPromise.access$000(DefaultPromise.java:33)
	at io.netty.util.concurrent.DefaultPromise$1.run(DefaultPromise.java:435)
	at io.netty.util.concurrent.GlobalEventExecutor$TaskRunner.run(GlobalEventExecutor.java:248)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by Y3ko** [comment]
`20:05:30 [SEVERE] Jul 15, 2018 8:05:30 PM io.netty.channel.DefaultChannelPipeline onUnhandledInboundException
WARNING: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.channel.unix.Errors$NativeIoException: accept(..) failed: Too many open files
    at io.netty.channel.unix.Errors.newIOException(Errors.java:122)
    at io.netty.channel.unix.Socket.accept(Socket.java:316)
    at io.netty.channel.epoll.AbstractEpollServerChannel$EpollServerSocketUnsafe.epollInReady(AbstractEpollServerChannel.java:112)
    at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$1.run(AbstractEpollChannel.java:387)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:313)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
    at java.lang.Thread.run(Thread.java:748)
`

**Comment by Janmm14** [comment]
Second error looks like too many connections.

**Comment by Y3ko** [comment]
No one??

**Comment by kamcio96** [comment]
bungee version? minecraft version? bungee status? plugins?
rly, man...
