### ISSUE TITLE
Error whilst handling query packet from null java.lang.IllegalStateException: No session!

### ISSUE THREAD

**Issue by RM5559** [SpigotMC/BungeeCord#2469]
Hi, several days ago the console sends this error and I do not know what it is:

`05:40:44 [WARNING] Error whilst handling query packet from null
java.lang.IllegalStateException: No session!
	at net.md_5.bungee.query.QueryHandler.channelRead0(QueryHandler.java:84)
	at net.md_5.bungee.query.QueryHandler.channelRead0(QueryHandler.java:22)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.epoll.EpollDatagramChannel$EpollDatagramChannelUnsafe.epollInReady(EpollDatagramChannel.java:483)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:408)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:308)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by RM5559** [comment]
Solved, change the query port to 25565

**Comment by md-5** [comment]
Its when someone sends invalid query data (if you looked at the 2000 other tickets that look like this).
Changing the port only "solved" it because now that person isnt sending data to you.
As always disable query if its not in use
