### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by Mgazul** [SpigotMC/BungeeCord#2476]
BungeeCore -1337
java8-171

 ???? 22, 2018 6:01:22 ???? io.netty.util.concurrent.DefaultPromise notifyListener0
????: An exception was thrown by net.md_5.bungee.UserConnection$3.operationComplete()
java.lang.NullPointerException
	at net.md_5.bungee.api.ServerConnectRequest$ServerConnectRequestBuilder$1.done(ServerConnectRequest.java:13)
	at net.md_5.bungee.api.ServerConnectRequest$ServerConnectRequestBuilder$1.done(ServerConnectRequest.java:13)
	at net.md_5.bungee.UserConnection$3.operationComplete(UserConnection.java:325)
	at net.md_5.bungee.UserConnection$3.operationComplete(UserConnection.java:318)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:504)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:483)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:103)
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:306)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:341)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:635)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:582)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:461)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at java.lang.Thread.run(Thread.java:748)

**Comment by md-5** [comment]
Sorry, resolved
