### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by Mgazul** [SpigotMC/BungeeCord#2482]
java.lang.RuntimeException: java.io.EOFException
	at com.google.common.base.Throwables.propagate(Throwables.java:240)
	at net.md_5.bungee.entitymap.EntityMap.readSkipSlot(EntityMap.java:257)
	at net.md_5.bungee.entitymap.EntityMap.rewriteMetaVarInt(EntityMap.java:195)
	at net.md_5.bungee.entitymap.EntityMap_1_13.rewriteClientbound(EntityMap_1_13.java:152)
	at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:104)
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:111)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:647)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:582)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:461)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.EOFException
	at java.io.DataInputStream.readFully(DataInputStream.java:197)
	at java.io.DataInputStream.readFully(DataInputStream.java:169)
	at com.flowpowered.nbt.stream.EndianSwitchableInputStream.readFully(EndianSwitchableInputStream.java:53)
	at com.flowpowered.nbt.stream.NBTInputStream.readTag(NBTInputStream.java:121)
	at com.flowpowered.nbt.stream.NBTInputStream.readTag(NBTInputStream.java:103)
	at net.md_5.bungee.entitymap.EntityMap.readSkipSlot(EntityMap.java:254)
	... 37 more

**Comment by md-5** [comment]
Need more information

**Comment by Mgazul** [comment]
java.lang.IllegalArgumentException: Tag type id 65 is unknown!
	at com.flowpowered.nbt.TagType.getById(TagType.java:103)

Probably I entered the subserver and then generated a custom horse and then disconnected the link.

**Comment by md-5** [comment]
Might've fixed it, but if its still an issue I need FULL DETAILS.
Like exactly HOW you made a "custom horse"

**Comment by Mgazul** [comment]
public static void spawnhorse(Player p, Location getto, String color, String style, int age, int heal, double speed, int jump){
	    Horse h = (Horse)p.getWorld().spawn(getto, Horse.class);
	    h.setTamed(true);
	    h.setOwner(p);	    
	    h.setColor(Horse.Color.valueOf(color));
	    h.setStyle(Horse.Style.valueOf(style));
	    h.getInventory().setSaddle(new ItemStack(Material.SADDLE));
	    h.getInventory().setArmor(new ItemStack(Material.IRON_HORSE_ARMOR));
	    h.setAdult();
	    h.setAge(age);
	    h.setAgeLock(true);
	    h.setJumpStrength(jump);
  	  	h.setCustomName(p.getName()+"horse‘s");
  	  	h.setCustomNameVisible(true);	
  	  	h.setInvulnerable(true);
  	  	AttributeInstance MaxHealth = h.getAttribute(Attribute.GENERIC_MAX_HEALTH);
  	  	MaxHealth.setBaseValue(heal);
  	  	Double getMaxhealth = MaxHealth.getBaseValue();
  	  	h.setHealth(getMaxhealth);
  	    h.setMetadata("RPG_Mounts", new FixedMetadataValue(Main.plugin, Boolean.valueOf(true)));
	    h.getAttribute(Attribute.GENERIC_MOVEMENT_SPEED).setBaseValue(speed);
	    String name = h.getCustomName().replace("horse‘s’", "");
		ceshi.lenque.put(name, System.currentTimeMillis() + 30000L);
		h.addPassenger(p);
	  }

**Comment by md-5** [comment]
That horse works for me in 1341

**Comment by Mgazul** [comment]
Perfect operation, thank you for your hard work
