### ISSUE TITLE
Cannot Join (1.13)

### ISSUE THREAD

**Issue by Swedz** [SpigotMC/BungeeCord#2484]
Whenever I connect I get this error in my bungeecord console:
```
03:11:49 [SEVERE] [Swedz] <-> ServerConnector [test] - encountered exception
io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(62) + length(1) exceeds writerIndex(62): UnpooledSlicedByteBuf(ridx: 62, widx: 62, cap: 62/62, unwrapped: PooledUnsafeDirectByteBuf(ridx: 63, widx: 63, cap: 1024))
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808)
    at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:408)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:308)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
    at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(62) + length(1) exceeds writerIndex(62): UnpooledSlicedByteBuf(ridx: 62, widx: 62, cap: 62/62, unwrapped: PooledUnsafeDirectByteBuf(ridx: 63, widx: 63, cap: 1024))
    at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1405)
    at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:707)
    at net.md_5.bungee.protocol.DefinedPacket.readVarInt(DefinedPacket.java:108)
    at net.md_5.bungee.protocol.DefinedPacket.readVarInt(DefinedPacket.java:98)
    at net.md_5.bungee.protocol.DefinedPacket.readArray(DefinedPacket.java:66)
    at net.md_5.bungee.protocol.DefinedPacket.readArray(DefinedPacket.java:61)
    at net.md_5.bungee.protocol.packet.EncryptionRequest.read(EncryptionRequest.java:27)
    at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:33)
    at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:10)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
    ... 21 more
```

**Comment by md-5** [comment]
No version provided

**Comment by md-5** [comment]
You are using an incompatible client

**Comment by md-5** [comment]
That error is exactly what occurs when you have a mismatched version.

Someone/something is still on pre7

**Comment by Swedz** [comment]
My client is not on pre7, and I don't think build 1340 is pre7?

**Comment by md-5** [comment]
Maybe your server is

**Comment by Swedz** [comment]
I updated the spigot version (which was on pre7 apparently), but now the bungeecord has a different error:
```
03:39:38 [SEVERE] [Swedz] <-> DownstreamBridge <-> [test] - encountered exception
java.lang.RuntimeException: java.io.EOFException
    at com.google.common.base.Throwables.propagate(Throwables.java:240)
    at net.md_5.bungee.entitymap.EntityMap.readSkipSlot(EntityMap.java:257)
    at net.md_5.bungee.entitymap.EntityMap.rewriteMetaVarInt(EntityMap.java:195)
    at net.md_5.bungee.entitymap.EntityMap_1_13.rewriteClientbound(EntityMap_1_13.java:152)
    at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:104)
    at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:111)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297)
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808)
    at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:408)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:308)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
    at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.EOFException
    at java.io.DataInputStream.readFully(DataInputStream.java:197)
    at java.io.DataInputStream.readFully(DataInputStream.java:169)
    at com.flowpowered.nbt.stream.EndianSwitchableInputStream.readFully(EndianSwitchableInputStream.java:53)
    at com.flowpowered.nbt.stream.NBTInputStream.readTag(NBTInputStream.java:121)
    at com.flowpowered.nbt.stream.NBTInputStream.readTag(NBTInputStream.java:103)
    at net.md_5.bungee.entitymap.EntityMap.readSkipSlot(EntityMap.java:254)
    ... 35 more
```

**Comment by md-5** [comment]
Your Bungee is outdated
