### ISSUE TITLE
java.lang.NullpointerException: owner error 

### ISSUE THREAD

**Issue by Kici33** [SpigotMC/BungeeCord#2489]
error:

java.lang.NullPointerException: owner
    at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:787)
    at net.md_5.bungee.scheduler.BungeeScheduler.schedule(BungeeScheduler.java:91)
    at net.md_5.bungee.scheduler.BungeeScheduler.schedule(BungeeScheduler.java:85)
    at me.bahu.ltd.listeners.LoginListener.onJoin(LoginListener.java:38)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.base/java.lang.reflect.Method.invoke(Unknown Source)
    at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
    at net.md_5.bungee.event.EventBus.post(EventBus.java:46)

code:

      ProxyServer.getInstance().getScheduler().schedule(Main.getInstance(), new Runnable()
      {
        public void run()
        {
          p.connect(ProxyServer.getInstance().getServerInfo(cfg.config.getString("lobby")));
        }
      }, 1L, TimeUnit.SECONDS);

**Comment by caoli5288** [comment]
Your `Main.getInstance()` may return `null`
