### ISSUE TITLE
new error

### ISSUE THREAD

**Issue by SlookHD** [SpigotMC/BungeeCord#2511]
[14:52:57 ERROR]: [/82.211.189.18:52444] <-> InitialHandler - encountered exception
java.lang.IllegalArgumentException: Unexpected packet received during login process!
616e676f20446f776e202120202d202053637269707420446566656e6465727354616e676f20446f776e202120202d202053637269707420446566656e646572
at net.md_5.bungee.connection.InitialHandler.handle(InitialHandler.java:139) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:45f9076:215]
at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:111) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:45f9076:215]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:45f9076:215]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:45f9076:215]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:45f9076:215]
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:45f9076:215]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:45f9076:215]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:45f9076:215]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:45f9076:215]
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:45f9076:215]
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:45f9076:215]
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:45f9076:215]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:45f9076:215]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:45f9076:215]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:45f9076:215]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:45f9076:215]
at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:45f9076:215]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:45f9076:215]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:45f9076:215]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:45f9076:215]
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:45f9076:215]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:45f9076:215]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:45f9076:215]
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:45f9076:215]
at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:45f9076:215]
at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:408) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:45f9076:215]
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:308) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:45f9076:215]
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:45f9076:215]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]

**Comment by Janmm14** [comment]
Someone sending wrong data to your bungeecord.

**Comment by Leymooo** [comment]
A TCP application(not mc) sends a packet.
https://codebeautify.org/hex-string-converter/cb767014

**Comment by SlookHD** [comment]
i know i need to know how to fix it

**Comment by Janmm14** [comment]
@SlookHD There is no way to fix it.

**Comment by md-5** [comment]
You’re not even using bungee

**Comment by pjorun** [comment]
I have this same error, but i use latest BC version:

java.lang.IllegalArgumentException: Unexpected packet received during server login process!
0d01
	at net.md_5.bungee.ServerConnector.handle(ServerConnector.java:130)
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:111)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:408)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:308)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at java.lang.Thread.run(Thread.java:748)

**Comment by Janmm14** [comment]
@pjorun
Please if you look for others having your issue. Please also look into the comments.

There is no way to solve it. Someone is sending wrong data to your bugeecord.

**Comment by ahmettrPro** [comment]
Apparently, this error is connected to "ip-forward" for some reason, happens to me too.
