### ISSUE TITLE
Cant switch to other servers (Solved)

### ISSUE THREAD

**Issue by honttv** [SpigotMC/BungeeCord#2550]
I am connected to the HUB server and everything seems to be working fine, however i cant connect to my factions server using /server factions because i get this error.

I now added another server and i get the same problem, I've tried everything imaginable. I need help please.

`20:06:34 [SEVERE] [hontiris1] <-> ServerConnector [factions] - encountered exception
java.lang.IllegalArgumentException: Unexpected packet received during server login process!
1ba6017b226578747261223a5b7b2274657874223a22227d2c7b2274657874223a22496e7465726e616c20457863657074696f6e3a206a6176612e6c616e672e
    at net.md_5.bungee.ServerConnector.handle(ServerConnector.java:130)
    at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:111)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:799)
    at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:421)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:321)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
    at java.lang.Thread.run(Thread.java:748)`

**Comment by Janmm14** [comment]
Please check console of your factions server. There should be an error.

**Comment by honttv** [comment]
> Please check console of your factions server. There should be an error.

There actually is none, which is even weirder.

**Comment by honttv** [comment]
I just added another server and none wants to work, only HUB is working.

**Comment by md-5** [comment]
Remove all plugins.
Your factions server is not sending correct packets.

**Comment by Janmm14** [comment]
Looks like its sending some disconnect message wrong, the ascii of the hex is `Ã{"extra":[{"text":""},{"text":"Internal Exception: java.lang.`
