### ISSUE TITLE
No client connected for pending server! Player cannot join for the first time

### ISSUE THREAD

**Issue by TomasGeilo5** [SpigotMC/BungeeCord#2573]
Please Help me :(

My Server GeiloCrew.DE

 17:21:22 [WARNING] [/37.59.63.9:34730] <-> InitialHandler - bad packet ID, are mods in use!? Did not read all bytes from packet class net.md_5.bungee.protocol.packet.StatusRequest 0 Protocol STATUS Direction TO_SERVER
> 17:21:22 [INFO] [SagIchNicht] <-> ServerConnector [Lobby-1] has connected
> 17:21:22 [WARNING] No client connected for pending server!
> 17:21:22 [SEVERE] [SagIchNicht] <-> ServerConnector [Lobby-1] - encountered exception: net.md_5.bungee.util.QuietException: Unexpected packet received during server login process! 4101
> 17:21:22 [INFO] [SagIchNicht] <-> ServerConnector [Lobby-1] has disconnected

**Comment by i9hdkill** [comment]
You are very likely using ProtocolSupport and/or ViaVersion. Remove it or update it.
As I see, you already opened a forum thread which is a better solution than opening a ticket here.
https://www.spigotmc.org/threads/no-client-connected-for-pending-server-player-cannot-join-for-the-first-time.354134/

**Comment by TomasGeilo5** [comment]
I checked the Console from the Lobby and found this

[20:31:32] [Thread-13/INFO]: UUID of player TheIronKneecap is 6cfd8136-2e1e-30c2-b54d-8c1d3616ab22
[20:31:32] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to Skellett v1.9.6b
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[Spigot.jar:git-PaperSpigot-"8b18730"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[Spigot.jar:git-PaperSpigot-"8b18730"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Spigot.jar:git-PaperSpigot-"8b18730"]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [Spigot.jar:git-PaperSpigot-"8b18730"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [Spigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.PlayerList.onPlayerJoin(PlayerList.java:314) [Spigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.java:173) [Spigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:144) [Spigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:54) [Spigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:231) [Spigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:148) [Spigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:875) [Spigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [Spigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [Spigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [Spigot.jar:git-PaperSpigot-"8b18730"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.util.NoSuchElementException: packet_handler
	at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:907) ~[Spigot.jar:git-PaperSpigot-"8b18730"]
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:157) ~[Spigot.jar:git-PaperSpigot-"8b18730"]
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:150) ~[Spigot.jar:git-PaperSpigot-"8b18730"]
	at com.gmail.thelimeglass.Utils.Packets.PacketListener.create(PacketListener.java:70) ~[?:?]
	at com.gmail.thelimeglass.Utils.Packets.PacketListener.onJoin(PacketListener.java:22) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[Spigot.jar:git-PaperSpigot-"8b18730"]
	... 15 more

**Comment by md-5** [comment]
Not running spigot, plugin bugs
