### ISSUE TITLE
Error console : NoClassDeFoundError

### ISSUE THREAD

**Issue by Guest1131** [SpigotMC/BungeeCord#2580]
Hey, I noticed there's a problem with Bungeecord's latest Build.

You don't enable the SkinRestorer plugin, the developer told me, that everything works perfectly from him, maybe because I think, that he uses an older version of Bungeecord.

And a problem with Bungeecord?

This error :

14:03:13 [WARNING] Exception encountered when loading plugin: SkinsRestorer
java.lang.NoClassDefFoundError: org/bstats/bungeecord/MetricsLite
    at skinsrestorer.bungee.SkinsRestorer.onEnable(SkinsRestorer.java:69)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:226)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:280)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:56)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: java.lang.ClassNotFoundException: org.bstats.bungeecord.MetricsLite
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:53)
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:27)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 5 more

**Comment by Black-Hole** [comment]
BungeeCord didn't change anything related to classloader recently. Please use the community support of the Spigot forum for help configuting your server and your plugins.
