### ISSUE TITLE
TabComplete Null Pointer

### ISSUE THREAD

**Issue by muehre** [SpigotMC/BungeeCord#2592]
Hey,

I do get the following Exception every time a client types. "/" in Chat.

```
io.netty.handler.codec.EncoderException: java.lang.NullPointerException
    at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
    at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
    at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
    at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
    at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
    at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1066)
    at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:309)
    at net.md_5.bungee.netty.ChannelWrapper.write(ChannelWrapper.java:60)
    at net.md_5.bungee.UserConnection$1.sendPacket(UserConnection.java:146)
    at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:545)
    at net.md_5.bungee.protocol.packet.TabCompleteResponse.handle(TabCompleteResponse.java:98)
    at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:104)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:799)
    at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:433)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:330)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909)
    at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
    at net.md_5.bungee.protocol.DefinedPacket.writeString(DefinedPacket.java:17)
    at net.md_5.bungee.protocol.packet.TabCompleteResponse.write(TabCompleteResponse.java:84)
    at net.md_5.bungee.protocol.MinecraftEncoder.encode(MinecraftEncoder.java:24)
    at net.md_5.bungee.protocol.MinecraftEncoder.encode(MinecraftEncoder.java:9)
    at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
    ... 40 more
[INFO] [Muehre] disconnected with: EncoderException : java.lang.NullPointerException @ io.netty.handler.codec.MessageToByteEncoder:125
```  

Strange thing. I did just rebuild my docker images with some minor changes.
I was not able to break it down to a single plugin as it happens on all instances (0.12.x/0.13.x).

Any idea? :)

**Comment by md-5** [comment]
Resolved

**Comment by muehre** [comment]
Seems like there is a follow up bug.

Happens since Build 1394 (#2592)
0.12.x & 0.13.x

![image](https://user-images.githubusercontent.com/9722525/51959072-1eda0180-2453-11e9-9d39-50acb6b7bce0.png)

**Comment by GunacP40** [comment]
I'm having this issue too. Happens randomly though. https://hastebin.com/ozeradagoz.properties

**Comment by Janmm14** [comment]
> I'm having this issue too. Happens randomly though. https://hastebin.com/ozeradagoz.properties

Your issue is different, yours is about titles. And 99% caused by a plugin. If you can reproduce without plugins, open a new issue.

**Comment by GunacP40** [comment]
You edited your post but thanks to that I was able to fix it. Sorry for reopening a fixed issue.
