### ISSUE TITLE
Error whilst handling query packet from null

### ISSUE THREAD

**Issue by x1p** [SpigotMC/BungeeCord#2594]
On a test bungee I have a bit of a spam problem. This appears every 5-30 sec.
```
11:39:36 [WARNING] Error whilst handling query packet from null
java.lang.IllegalStateException: No session!
	at net.md_5.bungee.query.QueryHandler.channelRead0(QueryHandler.java:84)
	at net.md_5.bungee.query.QueryHandler.channelRead0(QueryHandler.java:22)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.epoll.EpollDatagramChannel$EpollDatagramChannelUnsafe.epollInReady(EpollDatagramChannel.java:484)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:433)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:330)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909)
	at java.lang.Thread.run(Thread.java:748)
```
Even when all servers behind this Bungee are down and all plugins on Bungee are wiped, this happens.

In case this is an empty packet from somewhere out of space, it would certainly help if empty packets would log the IP-address and/or port. This would help a lot to determine the possible source.

**Comment by md-5** [comment]
Really strange that ctx.channel().remoteAddress() would be null, the address should be logged.


PS: If you don't need query, just disable it..

**Comment by x1p** [comment]
I'm afraid I need the query. The shared hosting uses it to monitor the number of players.
I'm changing ports to see if it reduces

**Comment by md-5** [comment]
IP should now be logged correctly.

**Comment by x1p** [comment]
I'm afraid it didn't help much in my case.
```
12:13:36 [WARNING] Error whilst handling query packet from null
java.lang.IllegalStateException: No session!
	at net.md_5.bungee.query.QueryHandler.channelRead0(QueryHandler.java:84)
	at net.md_5.bungee.query.QueryHandler.channelRead0(QueryHandler.java:22)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.epoll.EpollDatagramChannel$EpollDatagramChannelUnsafe.epollInReady(EpollDatagramChannel.java:484)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:433)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:330)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909)
	at java.lang.Thread.run(Thread.java:748)
```
