### ISSUE TITLE
Remove default group

### ISSUE THREAD

**Issue by Guest1131** [SpigotMC/BungeeCord#2611]
Hello, I would like to know you can not remove the default admin group? I mean this :

groups:
  md_5:
  - admin

I don't want to add another account, but I want to remove the group altogether. I tried to remove it, and after I restart the bungeecord, it creates itself again.

**Comment by ApocalypsjeNL** [comment]
`groups: []` should do the trick for you

**Comment by Guest1131** [comment]
I tried to do: 

groups: []

And from this error in the console :

16:05:47 [SEVERE] Exception in thread "main"
16:05:47 [SEVERE] java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.util.Map
16:05:47 [SEVERE]     at net.md_5.bungee.conf.YamlConfig.load(YamlConfig.java:99)
16:05:47 [SEVERE]     at net.md_5.bungee.conf.Configuration.load(Configuration.java:68)
16:05:47 [SEVERE]     at net.md_5.bungee.BungeeCord.start(BungeeCord.java:267)
16:05:47 [SEVERE]     at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:56)
16:05:47 [SEVERE]     at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

**Comment by ApocalypsjeNL** [comment]
oh whoeps, I meant `groups: {}`
