### ISSUE TITLE
How can I find which mod triggers an "Unknown meta type 14" error?

### ISSUE THREAD

**Issue by JoshuaWalsh** [SpigotMC/BungeeCord#2652]
I've run a few SpongeForge servers behind BungeeCord, and each time I run into an issue where at seemingly random intervals I'll get disconnected, with a message in the BungeeCord server console:

```
java.lang.IllegalArgumentException: Unknown meta type 14
at net.md_5.bungee.entitymap.EntityMap.rewriteMetaVarInt(EntityMap.java:275)
at net.md_5.bungee.entitymap.EntityMap.rewriteMetaVarInt(EntityMap.java:132)
at net.md_5.bungee.entitymap.EntityMap_1_12_1.rewriteClientbound(EntityMap_1_12_1.java:151)
at net.md_5.bungee.entitymap.EntityMap.rewriteClientbound(EntityMap.java:98)
at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:118)
at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:112)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:426)
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:796)
at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:427)
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:328)
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
at java.lang.Thread.run(Thread.java:748)
```

I understand that this is caused by a mod modifying the Minecraft protocol in an illegal way, and is not a bug with BungeeCord. What I'm wondering is, how can I work out which mod is responsible?

I have encountered this error in both the Feed The Beast: Builders Paradise modpack and the All The Mods 3: Remixed modpack. It seems to be more frequent in ATM3:R. I can't find any in-game event that causes it, and there's no error logged in the Forge server console at the time.

One interesting thing is that when I get disconnected with this error, if I reconnect I will almost certainly get immediately disconnected with the same error. Reconnecting again, it generally works. So there's a bit of a pattern there.

Also, would it be possible for BungeeCord to handle the error more gracefully? Maybe not dropping the connection?

Thanks for any help, really appreciate what BungeeCord does!

**Comment by Janmm14** [comment]
For the stuff bungeecord does, there is NO more graceful solution possible.

There is a pr ongoing which replaces a whole subsystem inside bungeecord, but its taking more time until its finished.

There is however a derivated work of bungeecord made by others, which already implemented this.
That so-called fork is named "Waterfall".

**Comment by 123Kappa** [comment]
Jushus it is probably astra sorcery's shooting stars
