### ISSUE TITLE
Can't connect to a server

### ISSUE THREAD

**Issue by Ratibus11** [SpigotMC/BungeeCord#2679]
I've install the last build of Bungeecord (#1418) and some 1.14.4 servers. When I connect to a server, I've this error : 

> 13:55:37 [GRAVE] août 01, 2019 1:55:37 PM io.netty.util.concurrent.AbstractEventExecutor safeExecute
AVERTISSEMENT: A task raised an exception. Task: net.md_5.bungee.connection.InitialHandler$6$1@6c903cb1
java.lang.ClassCastException: class java.util.ArrayList cannot be cast to class java.lang.String (java.util.ArrayList and java.lang.String are in module java.base of loader 'bootstrap')
    at net.md_5.bungee.UserConnection.addGroups(UserConnection.java:505)
    at net.md_5.bungee.UserConnection.init(UserConnection.java:162)
    at net.md_5.bungee.connection.InitialHandler$6$1.run(InitialHandler.java:517)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:333)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
    at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by Janmm14** [comment]
Configuration (format) issue likely.
