### ISSUE TITLE
Bungeecord drops player because of already existing objective while it is unregisterd

### ISSUE THREAD

**Issue by DeStilleGast** [SpigotMC/BungeeCord#2700]
So title might be wrong. but I was making my own plugin on spigot side, no problem works fine and bungeecord crashed and dropped my player.

the spigot console shows no errors but the bungee console does: 
```22:57:26 [SEVERE] [DeStilleGast] <-> DownstreamBridge <-> [lobby] - encountered exception
java.lang.IllegalArgumentException: Objective GlobalKillScore already exists in this scoreboard
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191)
    at net.md_5.bungee.api.score.Scoreboard.addObjective(Scoreboard.java:55)
    at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:143)
    at net.md_5.bungee.protocol.packet.ScoreboardObjective.handle(ScoreboardObjective.java:67)
    at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:104)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:426)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
    at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:677)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
    at java.lang.Thread.run(Unknown Source)
22:57:26 [INFO] [DeStilleGast] <-> DownstreamBridge <-> [lobby] has disconnected
22:57:31 [INFO] [DeStilleGast] disconnected with: Could not connect to a default or fallback server, please try again later: io.netty.channel.ConnectTimeoutException
22:57:31 [INFO] [DeStilleGast] -> UpstreamBridge has disconnected
```

as I can see is that objective `GlobalKillScore` already is register, but it was unregistered by the following code before it get re-registered on spigot plugin (basicly, cleaning all the entities on that objective):
```java
Objective old = p.getScoreboard().getObjective("GlobalKillScore");
if(old != null)
     old.unregister();
```
also tried ```java
p.getScoreboard().resetScores("GlobalKillScore");```
but that doesn't seem to solve my issue.

might be usefull, when a player joins, it gets assigned its own scoreboard:
p is the Player object that joined, this is also the only location where the objective is been created
```java
Scoreboard playerScoreboard = Bukkit.getScoreboardManager().getNewScoreboard();
Objective sidebarObjective = playerScoreboard.registerNewObjective("GlobalKillScore", "dummy", "KitPVP - Global kills");
sidebarObjective.setDisplaySlot(DisplaySlot.SIDEBAR);

p.setScoreboard(playerScoreboard);
```

Is there a fault in my plugin or a bug here?

**Comment by Drc-DEV** [comment]
Happened to me with a different plugin

**Comment by RobotoRaccoon** [comment]
Started happening for me recently on a plugin that has not changed since 2018
