### ISSUE TITLE
Scheduler#cancel(Plugin) does not always cancel all of the scheduled tasks

### ISSUE THREAD

**Issue by Rsl1122** [SpigotMC/BungeeCord#2765]
## Describe the issue

I've been having an issue where `Scheduler#cancel(Plugin)` does not always cancel all of the scheduled tasks.

Looking into the code further, I noticed that [Plugin.java](https://github.com/SpigotMC/BungeeCord/blob/master/api/src/main/java/net/md_5/bungee/api/plugin/Plugin.java) has no `hashCode` or `equals`, but it is [used in a HashMultimap](https://github.com/SpigotMC/BungeeCord/blob/master/proxy/src/main/java/net/md_5/bungee/scheduler/BungeeScheduler.java#L25). Could this lead to the issue?

I tried to find any suggestions in the documentation to override these when implementing a plugin, but could not find them

**Comment by Janmm14** [comment]
hashCode defaults to hashCode of memeory address and equals defaults to identiy equality. As only one instance of each plugin class should ever exist, this should not be a problem

**Comment by md-5** [comment]
You are using the same plugin instance right? Bungee doesn't atm have explicit protection against making more ones like Bukkit does, but what @Janmm14 said is correct.

Can you show the issue in a sample plugin?

**Comment by Rsl1122** [comment]
Yep, using the same instance.

I'll have to try writing a plugin that reproduces my issue - I'll get back to you when I have done so.

**Comment by Rsl1122** [comment]
Reproduced using this plugin:
- Plugin [reproduce-issue-2765.zip](https://github.com/SpigotMC/BungeeCord/files/4138239/reproduce-issue-2765.zip)
- Sources [sources.zip](https://github.com/SpigotMC/BungeeCord/files/4138242/sources.zip)
- [Gist of the Java files in the sources](https://gist.github.com/Rsl1122/5b6893f689dd5902228ab2fb8487473e)

**Comment by md-5** [comment]
Thanks

**Comment by md-5** [comment]
@Rsl1122 your code is flawed.

Because you schedule your tasks within an async task .cancel(plugin) is running before some of your tasks have been scheduled.

In progress executions are not cancelled (Java does not support arbitrarily killing a thread).

**Comment by md-5** [comment]
Stack trace showing the issue, as you can see the cancel is running while you are still scheduling subsequent tasks.
```
"main"
	at net.md_5.bungee.scheduler.BungeeScheduler.cancel0(BungeeScheduler.java:50)
	at net.md_5.bungee.scheduler.BungeeTask.cancel(BungeeTask.java:41)
	at net.md_5.bungee.scheduler.BungeeScheduler.cancel(BungeeScheduler.java:58)
	at net.md_5.bungee.scheduler.BungeeScheduler.cancel(BungeeScheduler.java:74)
	at com.djrapitops.bungee.Plugin.onDisable(Plugin.java:31)
	at com.djrapitops.bungee.Plugin.onEnable(Plugin.java:25)
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:250)
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:280)
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
"Issue-2765 Pool Thread #0"
	at net.md_5.bungee.scheduler.BungeeScheduler.schedule(BungeeScheduler.java:96)
	at net.md_5.bungee.scheduler.BungeeScheduler.schedule(BungeeScheduler.java:88)
	at com.djrapitops.bungee.Plugin.lambda$onEnable$0(Plugin.java:22)
	at com.djrapitops.bungee.Plugin$$Lambda$88.2099802038.run
	at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:834)
```
