### ISSUE TITLE
Antiproxy error?

### ISSUE THREAD

**Issue by Tomigames** [SpigotMC/BungeeCord#2795]
```
03:07:52 [SEVERE] java.lang.NullPointerException
> 03:07:52 [SEVERE] at me.defiancecoding.antiproxy.bungeecord.api.PCDetection.parseResults(PCDetection.java:245)
> 03:07:52 [SEVERE] at me.defiancecoding.antiproxy.bungeecord.listeners.BungeeLoginListener.onLogin(BungeeLoginListener.java:60)
> 03:07:52 [SEVERE] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 03:07:52 [SEVERE] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 03:07:52 [SEVERE] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 03:07:52 [SEVERE] at java.lang.reflect.Method.invoke(Method.java:498)
> 03:07:52 [SEVERE] at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
> 03:07:52 [SEVERE] at net.md_5.bungee.event.EventBus.post(EventBus.java:46)
> 03:07:52 [SEVERE] at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:399)
> 03:07:52 [SEVERE] at net.md_5.bungee.connection.InitialHandler.handle(InitialHandler.java:411)
> 03:07:52 [SEVERE] at net.md_5.bungee.protocol.packet.LoginRequest.handle(LoginRequest.java:39)
> 03:07:52 [SEVERE] at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:105)
> 03:07:52 [SEVERE] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
> 03:07:52 [SEVERE] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
> 03:07:52 [SEVERE] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
> 03:07:52 [SEVERE] at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
> 03:07:52 [SEVERE] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
> 03:07:52 [SEVERE] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
> 03:07:52 [SEVERE] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
> 03:07:52 [SEVERE] at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321)
> 03:07:52 [SEVERE] at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:295)
> 03:07:52 [SEVERE] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
> 03:07:52 [SEVERE] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
> 03:07:52 [SEVERE] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
> 03:07:52 [SEVERE] at io.netty.handler.codec.ByteToMessageDecoder.handlerRemoved(ByteToMessageDecoder.java:253)
> 03:07:52 [SEVERE] at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:505)
> 03:07:52 [SEVERE] at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:437)
> 03:07:52 [SEVERE] at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
> 03:07:52 [SEVERE] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
> 03:07:52 [SEVERE] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
> 03:07:52 [SEVERE] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
> 03:07:52 [SEVERE] at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
> 03:07:52 [SEVERE] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
> 03:07:52 [SEVERE] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
> 03:07:52 [SEVERE] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
> 03:07:52 [SEVERE] at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
> 03:07:52 [SEVERE] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
> 03:07:52 [SEVERE] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
> 03:07:52 [SEVERE] at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
> 03:07:52 [SEVERE] at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792)
> 03:07:52 [SEVERE] at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475)
> 03:07:52 [SEVERE] at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
> 03:07:52 [SEVERE] at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
> 03:07:52 [SEVERE] at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
```

Hi there this is the error I have been running into if someone could help me it would be greatly apreciated.

**Comment by ninja-** [comment]
Contact plugin author this is not bungeecord issue
