### ISSUE TITLE
Invalid Configuration

### ISSUE THREAD

**Issue by PiquelChips** [SpigotMC/BungeeCord#2814]
Mu bungeecord wont start and here is the issue:

15:32:37 [GRAVE] Exception in thread "main"
15:32:37 [GRAVE] java.lang.RuntimeException: Invalid configuration encountered - this is a configuration error and NOT a bug! Please attempt to fix the error or see https://www.spigotmc.org/ for help.
15:32:37 [GRAVE]     at net.md_5.bungee.conf.YamlConfig.load(YamlConfig.java:73)
15:32:37 [GRAVE]     at net.md_5.bungee.conf.Configuration.load(Configuration.java:71)
15:32:37 [GRAVE]     at net.md_5.bungee.BungeeCord.start(BungeeCord.java:273)
15:32:37 [GRAVE]     at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
15:32:37 [GRAVE]     at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
15:32:37 [GRAVE] Caused by: org.yaml.snakeyaml.error.YAMLException: java.nio.charset.MalformedInputException: Input length = 1
15:32:37 [GRAVE]     at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:218)
15:32:37 [GRAVE]     at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:176)
15:32:37 [GRAVE]     at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:171)
15:32:37 [GRAVE]     at org.yaml.snakeyaml.reader.StreamReader.peek(StreamReader.java:126)
15:32:37 [GRAVE]     at org.yaml.snakeyaml.scanner.ScannerImpl.scanToNextToken(ScannerImpl.java:1177)
15:32:37 [GRAVE]     at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:287)
15:32:37 [GRAVE]     at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:227)
15:32:37 [GRAVE]     at org.yaml.snakeyaml.parser.ParserImpl$ParseImplicitDocumentStart.produce(ParserImpl.java:195)
15:32:37 [GRAVE]     at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
15:32:37 [GRAVE]     at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148)
15:32:37 [GRAVE]     at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:107)
15:32:37 [GRAVE]     at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:141)
15:32:37 [GRAVE]     at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:525)
15:32:37 [GRAVE]     at org.yaml.snakeyaml.Yaml.load(Yaml.java:453)
15:32:37 [GRAVE]     at net.md_5.bungee.conf.YamlConfig.load(YamlConfig.java:70)
15:32:37 [GRAVE]     ... 4 more
15:32:37 [GRAVE] Caused by: java.nio.charset.MalformedInputException: Input length = 1
15:32:37 [GRAVE]     at java.nio.charset.CoderResult.throwException(Unknown Source)
15:32:37 [GRAVE]     at sun.nio.cs.StreamDecoder.implRead(Unknown Source)
15:32:37 [GRAVE]     at sun.nio.cs.StreamDecoder.read(Unknown Source)
15:32:37 [GRAVE]     at java.io.InputStreamReader.read(Unknown Source)
15:32:37 [GRAVE]     at org.yaml.snakeyaml.reader.UnicodeReader.read(UnicodeReader.java:125)
15:32:37 [GRAVE]     at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:183)
15:32:37 [GRAVE]     ... 18 more

And here is my config file:
connection_throttle_limit: 3
online_mode: true
log_commands: false
network_compression_threshold: 256
listeners:
- query_port: 25577
  motd: '&1Another Bungee server'
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  forced_hosts:
    pvp.md-5.net: pvp
  ping_passthrough: false
  priorities:
  - lobby01
  - lobby02
  - lobby03
  - lobby04
  bind_local_address: true
  host: 0.0.0.0:25577
  max_players: 1000
  tab_size: 60
  force_default_server: true
connection_throttle: 4000
groups:
  JCG68:
  - Modérateur
  Modérateur:
  - JCG68
  RG68:
  - Administrateur
  Administrateur:
  - RG68
  md_5:
  - Administrateur
  - Modérateur
log_pings: true
ip_forward: true
prevent_proxy_connections: false
forge_support: false
stats: a623835b-f876-4660-8769-3e12359e9f20
disabled_commands:
- disabledcommandhere
timeout: 30000
permissions:
  default:
  - dkbans.report
  - perfectbunge
  Modérateur:
  - bungeecord.command.server
  - bungeecord.command.list
  - bungeecord.command.alert
  - bungeecord.command.ip
  - bungeecord.command.send
  - bungeecord.command.find
  - staffchat.access
  - dkbans.*
  - dkbans.ban
  - dkbans.ban
  - dkbans.ban
  - dkbans.ban
  - dkbans.ban
  - dkbans.ban
  - dkbans.ban
  - dkbans.ban
  - dkbans.ban
  - dkbans.ban
  - dkbans.ban
  - dkbans.ban
  - dkbans.ban
  - dkbans.ban
  - dkbans.ban
  - dkbans.ban.temp.ban
  - dkbans.ban.temp.mute
  - dkbans.kick
  - dkbans.unban
  - dkbans.warn
  - dkbans.editban
  - dkbans.baninfo
  - dkbans.playerinfo
  - dkbans.history
  - dkbans.history.reset
  - dkbans.report
  - dkbans.report.receive
  - dkbans.ipban
  - dkbans.ipunban
  - dkbans.teamchat.send
  - dkbans.jumpto
  - dkbans.broadcast
  - dkbans.filter
  - dkbans.ipinfo
  - dkbans.chatlog
  - dkbans.joinme
  - dkbans.networkstats
  - dkbans.staffstats
  - dkbans.ping.other
  - dkbans.onlinetime
  Administrateur:
  - '*'
  - bungeecord.command.server
  - bungeecord.command.list
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
  - bungeecord.command.send
  - bungeecord.*
  - bungeecord.command.find
  - staffchat.access
  - staffchat.*
  - maintenance.*
  - dkbans.*
  - dkbans.ban
  - dkbans.ban
  - dkbans.ban
  - dkbans.ban
  - dkbans.ban
  - dkbans.ban
  - dkbans.ban
  - dkbans.ban
  - dkbans.ban
  - dkbans.ban
  - dkbans.ban
  - dkbans.ban
  - dkbans.ban
  - dkbans.ban
  - dkbans.ban
  - dkbans.ban.temp.ban
  - dkbans.ban.temp.mute
  - dkbans.kick
  - dkbans.unban
  - dkbans.warn
  - dkbans.editban
  - dkbans.baninfo
  - dkbans.playerinfo
  - dkbans.history
  - dkbans.history.reset
  - dkbans.report
  - dkbans.report.receive
  - dkbans.ipban
  - dkbans.ipunban
  - dkbans.teamchat.send
  - dkbans.jumpto
  - dkbans.broadcast
  - dkbans.filter
  - dkbans.ipinfo
  - dkbans.chatlog
  - dkbans.joinme
  - dkbans.networkstats
  - dkbans.staffstats
  - dkbans.ping.other
  - dkbans.onlinetime
  - bungeepexbridge.reload
  - maintenance.admin
  - bungeeserveradmin.*
  - perfectbungee.ac
  - perfectbungee
  - perfectbungee
  - perfectbungee
  - perfectbungee
  - perfectbungee
  - perfectbungee
  - perfectbungee
  - perfectbungee
  - perfectbungee
  - perfectbungee
  - perfectbungee
  - perfectbungee
  - perfectbungee
  - perfectbungee
  - perfectbungee
  - perfectbungee
servers:
  lobby01:
    motd: '&1Just another BungeeCord - Forced Host'
    address: localhost:12001
    restricted: false
  lobby02:
    motd: '&1Just another BungeeCord - Forced Host'
    address: localhost:12002
    restricted: false
  lobby03:
    motd: '&1Just another BungeeCord - Forced Host'
    address: localhost:12003
    restricted: false
  lobby04:
    motd: '&1Just another BungeeCord - Forced Host'
    address: localhost:12004
    restricted: false
  test:
    motd: '&1Just another BungeeCord - Forced Host'
    address: localhost:20001
    restricted: false
  build:
    motd: '&1Just another BungeeCord - Forced Host'
    address: localhost:20002
    restricted: false
  skyblock:
    motd: '&1Just another BungeeCord - Forced Host'
    address: localhost:19001
    restricted: false
player_limit: -1

**Comment by Janmm14** [comment]
> this is a configuration error and NOT a bug! Please attempt to fix the error or see https://www.spigotmc.org/ for help.

Please do **not** use this bug tracker for this problem.
