### ISSUE TITLE
NullPointerException when sending TextComponents without HoverEvent

### ISSUE THREAD

**Issue by derrop** [SpigotMC/BungeeCord#2878]
BungeeCord Version: `git:BungeeCord-Bootstrap:1.16-R0.2-SNAPSHOT:a64c34d:1517`

This exception gets thrown when you try to set the tab header/footer to a BaseComponent that has no HoverEvent:
```
java.lang.NullPointerException
	at net.md_5.bungee.util.ChatComponentTransformer.legacyHoverTransform(ChatComponentTransformer.java:44)
	at net.md_5.bungee.util.ChatComponentTransformer.transform(ChatComponentTransformer.java:111)
	at net.md_5.bungee.UserConnection.setTabHeader(UserConnection.java:666)
```

The same occurs when sending a message to a player without a HoverEvent:
```
java.lang.NullPointerException
	at net.md_5.bungee.util.ChatComponentTransformer.legacyHoverTransform(ChatComponentTransformer.java:44)
	at net.md_5.bungee.util.ChatComponentTransformer.transform(ChatComponentTransformer.java:111)
	at net.md_5.bungee.UserConnection.sendMessage(UserConnection.java:453)
	at net.md_5.bungee.UserConnection.sendMessage(UserConnection.java:435)
	at net.md_5.bungee.UserConnection.sendMessage(UserConnection.java:420)
	at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:175)
	at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:142)
	at net.md_5.bungee.connection.UpstreamBridge.handle(UpstreamBridge.java:149)
	at net.md_5.bungee.protocol.packet.Chat.handle(Chat.java:66)
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
```

**Comment by SystemUpdate** [comment]
To add, this applies when you attempt to send a message to a user.

I believe commit https://github.com/SpigotMC/BungeeCord/commit/1d40b8a88a3b62a1c1a58fa47e8e3fbaeb383de9 breaks it, as https://github.com/SpigotMC/BungeeCord/blob/1d40b8a88a3b62a1c1a58fa47e8e3fbaeb383de9/proxy/src/main/java/net/md_5/bungee/util/ChatComponentTransformer.java#L109 does not check if there is a hover, https://github.com/SpigotMC/BungeeCord/blob/1d40b8a88a3b62a1c1a58fa47e8e3fbaeb383de9/proxy/src/main/java/net/md_5/bungee/util/ChatComponentTransformer.java#L44 throws an NPE.

**Comment by Alexre** [comment]
Also having this issue with versions up to 1515

**Comment by Alv5ro** [comment]
Is this the same when you do /glist ?

**Comment by ZNChano** [comment]
Anybody got an answer?

**Comment by derrop** [comment]
It has been fixed 7 days ago, just update your bungee.
