### ISSUE TITLE
BaseComponent is not compatible

### ISSUE THREAD

**Issue by lintx** [SpigotMC/BungeeCord#2884]
I use BungeCord to show items to all players. I put the items into BaseComponent by hoverevent.action.show_item in spigot, and then deserialize the BaseComponent to json, and then send it to BungeCord through a plugin message, which has no problems before. .
However, since BungeeCord was updated to version 1516 and above, the BungeeCord side could not parse due to changes in the ComponentSerializer class:
`com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Not a JSON Object: [{"text":"{id:\"minecraft:dirt\",Count:1b}"}]`
I tried to use the new API to build the BaseComponent on the spigot side, and then deserialize it into json, and then send it to BungeCord, so that it can be parsed normally, but the player (client version 1.16.1) will receive a message because of `Internal Exception: io.netty.handler.codec.DecoderException: com.google.gson.JsonSyntaxException: Expected item to be a JsonObject, was an array ([{"i...1}])` and lost connection.
I don’t know what I should do to modify my plugin so that it can correctly display an item in both 1516 and 1515 versions of BungeeCord

**Comment by Mystiflow** [comment]
Do you have source code or JSON that you can share that doesn't work? I tried ```ComponentSerializer.parse( "[{\"text\":\"{id:\\\"minecraft:dirt\\\",Count:1b}\"}]" );``` which works

**Comment by md-5** [comment]
@lintx please can you respond to this promptly, it's basically holding up release of the new version

**Comment by lintx** [comment]
I have a plugin whose open source address is at `https://github.com/lintx/Minecraft-Plugin-YinwuChat`, its installation method is to install in spigot and BungeCord at the same time, one of its functions is when the player sends When the message contains `[i]`, the spigot end will get the player’s hand, convert it to BaseComponent and deserialize it into json, then send it to BungeCord, and finally send the message to all players in BungeCord.
In the latest version of BungeeCord, the items cannot be displayed. I tried to track down the problem and found that the json text sent by spigot could not be serialized. The code I used for debugging:
```
        System.out.println("test show item start");
        try {
            String json = "{\"extra\":[{\"text\":\"§r§7[§r\"},{\"extra\":[{\"translate\":\"block .minecraft.dirt\"}],\"text\":\"\"},{\"text\":\"§r§7]§r\"}],\"hoverEvent\":{\ "action\":\"show_item\",\"value\":[{\"text\":\"{id:\\\"minecraft:dirt\\\",Count:1b}\"}] },\"text\":\"\"}";
            System.out.println(json);
            BaseComponent[] component = ComponentSerializer.parse(json);
            if (component.length>0){
                System.out.println(component[0].toLegacyText());
            }
        }catch (Exception e){
            e.printStackTrace();
        }
        System.out.println("test show item end");
```
The error is reported as follows:
```
09:36:08 [Information] {"extra":[{"text":"??r??7[??r"},{"extra":[{"translate":"block.minecraft.dirt "}],"text":""},{"text":"??r??7]??r"}],"hoverEvent":{"action":"show_item","value":[ {"text":"{id:\"minecraft:dirt\",Count:1b}"}]},"text":""}
09:36:08 [Warning] Exception encountered when loading plugin: YinwuChat
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Not a JSON Object: [{"text":"{id:\"minecraft:dirt\",Count:1b}"}]
at com.google.gson.Gson.fromJson(Gson.java:899)
at com.google.gson.Gson.fromJson(Gson.java:952)
at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162)
at extra.net.md_5.bungee.chat.BaseComponentSerializer.deserialize(BaseComponentSerializer.java:78)
at extra.net.md_5.bungee.chat.TextComponentSerializer.deserialize(TextComponentSerializer.java:23)
at extra.net.md_5.bungee.chat.TextComponentSerializer.deserialize(TextComponentSerializer.java:15)
at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
at com.google.gson.Gson.fromJson(Gson.java:887)
at com.google.gson.Gson.fromJson(Gson.java:952)
at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162)
at extra.net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:97)
at extra.net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:22)
at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
at com.google.gson.Gson.fromJson(Gson.java:887)
at com.google.gson.Gson.fromJson(Gson.java:952)
at com.google.gson.Gson.fromJson(Gson.java:925)
at extra.net.md_5.bungee.chat.ComponentSerializer.parse(ComponentSerializer.java:52)
at org.lintx.plugins.yinwuchat.bungee.YinwuChat.onEnable(YinwuChat.java:76)
at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:250)
at net.md_5.bungee.BungeeCord.start(BungeeCord.java:285)
at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: java.lang.IllegalStateException: Not a JSON Object: [{"text":"{id:\"minecraft:dirt\",Count:1b}"}]
at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:90)
at extra.net.md_5.bungee.api.chat.HoverEvent$ContentItem$Serializer.deserialize(HoverEvent.java:298)
at extra.net.md_5.bungee.api.chat.HoverEvent$ContentItem$Serializer.deserialize(HoverEvent.java:292)
at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
at com.google.gson.Gson.fromJson(Gson.java:887)
... 21 more
```
When using the 1515 version of BungeeCord, no error is reported:
```
10:06:49 [Information] test show item start
10:06:49 [Information] {"extra":[{"text":"??r??7[??r"},{"extra":[{"translate":"block.minecraft.dirt "}],"text":""},{"text":"??r??7]??r"}],"hoverEvent":{"action":"show_item","value":[ {"text":"{id:\"minecraft:dirt\",Count:1b}"}]},"text":""}
10:06:49 [Information] ??f??f??r??7[??r??f??fDirt??f??r??7]??r
10:06:49 [Information] test show item end
```
