### ISSUE TITLE
WF crosses BC problem

### ISSUE THREAD

**Issue by SheerHuangJin** [SpigotMC/BungeeCord#2911]
Or BC across WF
This problem will occur if you use 1.16+ cross-server
And versions below 1.15.2 will not
WF will not cause this problem when ip forwarding is turned off

[07:13:16 ERROR]: [/0.0.0.0:14849|Yin] <-> DownstreamBridge <-> [sur] - encountered exception
java.lang.IllegalArgumentException: Team 0010yinA already exists in this scoreboard
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.3-SNAPSHOT:9eb5b42:364]
	at net.md_5.bungee.api.score.Scoreboard.addTeam(Scoreboard.java:73) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.3-SNAPSHOT:9eb5b42:364]
	at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:232) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.3-SNAPSHOT:9eb5b42:364]
	at net.md_5.bungee.protocol.packet.Team.handle(Team.java:124) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.3-SNAPSHOT:9eb5b42:364]
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:105) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.3-SNAPSHOT:9eb5b42:364]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.3-SNAPSHOT:9eb5b42:364]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.3-SNAPSHOT:9eb5b42:364]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.3-SNAPSHOT:9eb5b42:364]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.3-SNAPSHOT:9eb5b42:364]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.3-SNAPSHOT:9eb5b42:364]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.3-SNAPSHOT:9eb5b42:364]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.3-SNAPSHOT:9eb5b42:364]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.3-SNAPSHOT:9eb5b42:364]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.3-SNAPSHOT:9eb5b42:364]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.3-SNAPSHOT:9eb5b42:364]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.3-SNAPSHOT:9eb5b42:364]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.3-SNAPSHOT:9eb5b42:364]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.3-SNAPSHOT:9eb5b42:364]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.3-SNAPSHOT:9eb5b42:364]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.3-SNAPSHOT:9eb5b42:364]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.3-SNAPSHOT:9eb5b42:364]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.3-SNAPSHOT:9eb5b42:364]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.3-SNAPSHOT:9eb5b42:364]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.3-SNAPSHOT:9eb5b42:364]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.3-SNAPSHOT:9eb5b42:364]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.3-SNAPSHOT:9eb5b42:364]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.3-SNAPSHOT:9eb5b42:364]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.3-SNAPSHOT:9eb5b42:364]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.3-SNAPSHOT:9eb5b42:364]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.3-SNAPSHOT:9eb5b42:364]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.3-SNAPSHOT:9eb5b42:364]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.3-SNAPSHOT:9eb5b42:364]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.3-SNAPSHOT:9eb5b42:364]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.3-SNAPSHOT:9eb5b42:364]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.3-SNAPSHOT:9eb5b42:364]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.3-SNAPSHOT:9eb5b42:364]
	at java.lang.Thread.run(Thread.java:819) [?:1.8.0_222]
[07:13:16 INFO]: [Yin] disconnected with: The server you were previously on went down, you have been connected to a fallback server

**Comment by md-5** [comment]
Not running bungeecord
