### ISSUE TITLE
Players above 1.16 will be kicked out of bungeecord if they try to switch servers.

### ISSUE THREAD

**Issue by Score2** [SpigotMC/BungeeCord#2916]
Players above 1.16 will be kicked out of bungeecord if they try to switch servers.

### This is bungeecord's error throughout the process:
```
08:26:38 [严重] [Yin] <-> DownstreamBridge <-> [th] - encountered exception
java.lang.IllegalArgumentException: Team CMICol already exists in this scoreboard
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191)
	at net.md_5.bungee.api.score.Scoreboard.addTeam(Scoreboard.java:73)
	at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:211)
	at net.md_5.bungee.protocol.packet.Team.handle(Team.java:124)
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:425)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.lang.Thread.run(Unknown Source)
08:26:38 [信息] [Yin] <-> DownstreamBridge <-> [th] has disconnected
```

### The kick message of the player who was kicked out is:
```
The server you were previously on went down , you have been connected to a fallback server
```

### At the same time, during the process of being kicked out when switching servers, the client also made an error:
```
[09:02:20] [Render thread/FATAL]: Error executing task on Client
java.lang.NullPointerException: null
[09:02:20] [Render thread/WARN]: Unknown custom packed identifier: minecraft:register
[09:02:20]Render thread/FATAL]: Error executing task on Client
java.lang.IllegalA [rgumentException: A team with the name '0010yinA' already exists!
	at dfm.g(SourceFile:188) ~[1.16.1.jar:?]
	at dyn.a(SourceFile:2141) ~[1.16.1.jar:?]
	at qh.a(SourceFile:122) ~[1.16.1.jar:?]
	at qh.a(SourceFile:16) ~[1.16.1.jar:?]
	at nk.a(SourceFile:21) ~[1.16.1.jar:?]
	at amn.c(SourceFile:144) [1.16.1.jar:?]
	at amr.c(SourceFile:23) [1.16.1.jar:?]
	at amn.x(SourceFile:118) [1.16.1.jar:?]
	at amn.bj(SourceFile:103) [1.16.1.jar:?]
	at dlx.e(SourceFile:988) [1.16.1.jar:?]
	at dlx.e(SourceFile:654) [1.16.1.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:215) [1.16.1.jar:?]
[09:02:21] [Render thread/INFO]: Loaded 356 advancements
```
According to the client's error, it seems to be "Username already exists"

In the same operation, 1.15 players will not have these problems.

**Comment by md-5** [comment]
Make sure you are using the latest version

**Comment by Score2** [comment]
> Make sure you are using the latest version

Yes, I use the latest version.

**Comment by md-5** [comment]
Which is?

**Comment by Score2** [comment]
> Which is?

Build #1529
