### ISSUE TITLE
Not expecting FORGE LOGIN

### ISSUE THREAD

**Issue by Kewilleen** [SpigotMC/BungeeCord#2925]
Hello,

Recently i am getting this constant error from my bungee server, somebody can help me please?

17:41:24 [SEVERE] [/177.188.71.71:56315] <-> InitialHandler - encountered exception
java.lang.IllegalStateException: Not expecting FORGE LOGIN
	at com.google.common.base.Preconditions.checkState(Preconditions.java:149)
	at net.md_5.bungee.connection.InitialHandler.handle(InitialHandler.java:132)
	at net.md_5.bungee.protocol.packet.Packet1Login.handle(Packet1Login.java:71)
	at net.md_5.bungee.netty.HandlerBoss.messageReceived(HandlerBoss.java:73)
	at io.netty.channel.DefaultChannelHandlerContext.invokeMessageReceived(DefaultChannelHandlerContext.java:379)
	at io.netty.channel.DefaultChannelHandlerContext.fireMessageReceived(DefaultChannelHandlerContext.java:364)
	at io.netty.handler.codec.ByteToMessageDecoder.messageReceived(ByteToMessageDecoder.java:187)
	at io.netty.channel.DefaultChannelHandlerContext.invokeMessageReceived(DefaultChannelHandlerContext.java:379)
	at io.netty.channel.DefaultChannelHandlerContext.fireMessageReceived(DefaultChannelHandlerContext.java:364)
	at io.netty.handler.timeout.ReadTimeoutHandler.messageReceived(ReadTimeoutHandler.java:150)
	at io.netty.channel.DefaultChannelHandlerContext.invokeMessageReceived(DefaultChannelHandlerContext.java:379)
	at io.netty.channel.DefaultChannelHandlerContext.fireMessageReceived(DefaultChannelHandlerContext.java:364)
	at io.netty.channel.DefaultChannelPipeline.fireMessageReceived(DefaultChannelPipeline.java:786)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:120)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:489)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:464)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:358)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101)
	at java.lang.Thread.run(Thread.java:748)

**Comment by MrIvanPlays** [comment]
This is either a:

1. really outdated version of bungeecord
2. modified version of bungeecord

whatever it is, you wouldn't get support for it here.

**Comment by Kewilleen** [comment]
@MrIvanPlays it's a outdated version, but i can make something to fix? Create a extension with ProxyPingEvent?

**Comment by MrIvanPlays** [comment]
> @MrIvanPlays it's a outdated version, but i can make something to fix? Create a extension with ProxyPingEvent?

update to latest version of bungeecord

**Comment by Kewilleen** [comment]
@MrIvanPlays i have players in 1.5.2 version, i can't update

**Comment by md-5** [comment]
We don't support the 1.5.2 version
