### ISSUE TITLE
Bungeecord 1.16 Server Error

### ISSUE THREAD

**Issue by r-manisthebest** [SpigotMC/BungeeCord#2930]
Hi there, I'm having an issue on the server I'm an admin on where some players, not all, would occasionally get kicked back to the fallback server, in this case the **Hub**. 

Players are getting this message: "The server you were previously on went down, you have been connected to a fallback server".

The server hasn't gone down as most players are still connected and continuing whatever they are doing with no issues at all.

**Season3** is the name of the server we're having this error on, and the fallback server is the **Hub**.
Below is what the console for the bungeecord server gives out, there are no other errors on the Season3 or Hub servers. They just show the player joining and leaving as normal.

[INFO] [r_manisthebest] <-> ServerConnector [Hub] has connected
[INFO] r_manisthebest executed command: /server Season3
[INFO] [r_manisthebest] <-> ServerConnector [Season3] has connected
[INFO] [r_manisthebest] <-> DownstreamBridge <-> [Hub] has disconnected
[SEVERE] [r_manisthebest] <-> DownstreamBridge <-> [Season3] - encountered exception
java.lang.IndexOutOfBoundsException: readerIndex(41) + length(1) exceeds writerIndex(41): PooledUnsafeDirectByteBuf(ridx: 41, widx: 41, cap: 41)
at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1477)
at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:731)
at io.netty.buffer.AbstractByteBuf.readUnsignedByte(AbstractByteBuf.java:745)
at net.md_5.bungee.entitymap.EntityMap.rewriteMetaVarInt(EntityMap.java:150)
at net.md_5.bungee.entitymap.EntityMap_1_16.rewriteClientbound(EntityMap_1_16.java:150)
at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:122)
at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:113)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311)
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:425)
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792)
at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475)
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at java.lang.Thread.run(Thread.java:748)
23:08:56 [INFO] [r_manisthebest] <-> DownstreamBridge <-> [Season3] has disconnected
23:08:56 [INFO] [r_manisthebest] <-> ServerConnector [Hub] has connected

**BUNGEECORD VERSION: 1529
MINECRAFT VERSION: 1.16.1**

I have no idea what any of this means and the only way I have been able to fix it is taking the Season3 server offline and disconnecting it from Bungeecord and turning it on as its own online server, then reconnecting it, this seems to reoccur every now and again and I'm not sure what the issue is.

Any help is greatly appreciated. Thanks! :)

**Comment by Sch1nken** [comment]
Can maybe chime in with some info. Got a similiar error on my server. I tried both Spigot and PaperMC 1.16.2 and 1.16.3 as well as BungeeCord and Waterfall.

For me the problem started once I installed a datapack (Vanillatweaks -> Villager Workstation Highlight) which does some magic in the background to show you the current workstation of a villager.
(Get all villager entities in range, place armorstand for datastorage, save xyz of workstation block, run area_effect_cloud at location, remove armorstand, send chat message to player).

The person using the command got kicked from the server with the message, that the server stopped/closed(?) (I'll recheck as soon as possible).

The thing is, that everybody who entered the same chunk also got disconnected (there were like 40 villagers there).

Looking at the code (at net.md_5.bungee.entitymap.EntityMap.rewriteMetaVarInt(EntityMap.java:150) there are quite some references to particleIds.

I'll try removing the particle effect from the datapack and see if it still kicks people. But I hope that this might help someone to further identify the problem. I'll keep you updated.

**Comment by TheBeast0253-Codes** [comment]
i have this issue. Same issue. please help me github

**Comment by Janmm14** [comment]
> i have this issue. Same issue. please help me github

The issue ou commented below is more than 2 years old. In general there is no help to this issue - i have seen that asynchronous packet sending on spigot (async chat messages and/or async protocollib usage) can lead to such problems
