### ISSUE TITLE
Base name

### ISSUE THREAD

**Issue by AlbertPallardo** [SpigotMC/BungeeCord#2939]
I translated the messages.properties and it gives me this error:

Exception in thread "main" java.util.MissingResourceException: Can't find bundle for base name messages, locale en
at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1581)
at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1396)
at java.util.ResourceBundle.getBundle(ResourceBundle.java:854)
at net.md_5.bungee.BungeeCord.<init>(BungeeCord.java:198)
at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:59)
at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

**Comment by Foxiseminger** [comment]
> I translated the messages.properties and it gives me this error:
> 
> 
> 
> Exception in thread "main" java.util.MissingResourceException: Can't find bundle for base name messages, locale en
> 
> at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1581)
> 
> at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1396)
> 
> at java.util.ResourceBundle.getBundle(ResourceBundle.java:854)
> 
> at net.md_5.bungee.BungeeCord.<init>(BungeeCord.java:198)
> 
> at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:59)
> 
> at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

sorry for late reply buddy but hate to break it to ya but i dont speak java sooo
