### ISSUE TITLE
NullPointerException bug

### ISSUE THREAD

**Issue by Ardno123** [SpigotMC/BungeeCord#2943]
On use PreLoginEvent#setCancelled(boolean cancelled); without PreLoginEvent#setCancelReason(BaseComponent... components); throws me a NullPointerException in console.

error:
```
18:27:53 [SEVERE] [nickname,/78.45.134.59:55038] <-> InitialHandler - encountered exception
java.lang.NullPointerException
    at net.md_5.bungee.chat.ComponentSerializer.toString(ComponentSerializer.java:74)
    at net.md_5.bungee.connection.InitialHandler.disconnect(InitialHandler.java:586)
    at net.md_5.bungee.connection.InitialHandler$4.done(InitialHandler.java:392)
    at net.md_5.bungee.connection.InitialHandler$4.done(InitialHandler.java:385)
    at net.md_5.bungee.api.event.AsyncEvent.postCall(AsyncEvent.java:40)
    at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:400)
    at net.md_5.bungee.connection.InitialHandler.handle(InitialHandler.java:411)
    at net.md_5.bungee.protocol.packet.LoginRequest.handle(LoginRequest.java:39)
    at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:105)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContex
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContex
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContex
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContex
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
```

**Comment by Mystiflow** [comment]
Essentially we can either disconnect them with an arbitrary kick message or throw an explicit exception stating that the event was cancelled without a cancel reason.

**Comment by Janmm14** [comment]
I think a default kick message (maybe editable in messages.properties) is the better option.

**Comment by Ardno123** [comment]
> I think a default kick message (maybe editable in messages.properties) is the better option.

Not really, because if I cancel the event without reason, bungeecord throws me error, but it (bungeecord) still disconnect the player.

**Comment by Janmm14** [comment]
> > I think a default kick message (maybe editable in messages.properties) is the better option.
> 
> Not really, because if I cancel the event without reason, bungeecord throws me error, but it (bungeecord) still disconnect the player.

I think the player will however see a NullPointerException as reason for their kick, which is anything but intended.
