### ISSUE TITLE
Players getting kicked after a few seconds (please help asap)

### ISSUE THREAD

**Issue by DuckyBlender** [SpigotMC/BungeeCord#2956]
When I join the bungeecord server that I have properly configurated, it kicks me from my Survival server for the reason: 
The server you were previously on went down, you have been connected to a fallback server

It isn't lag, I can type in chat, nothing is happening with the server from the preformance side. I get this huge error in the console (bungeecord server):

`[22:33:55 INFO]: [DuckyBlender|/89.64.91.57:52896] <-> ServerConnector [survival] has connected
[22:34:10 ERROR]: [/89.64.91.57:52896|DuckyBlender] <-> DownstreamBridge <-> [survival] - encountered exception
java.lang.IllegalArgumentException: Team tm-sb-0 already exists in this scoreboard
at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at net.md_5.bungee.api.score.Scoreboard.addTeam(Scoreboard.java:73) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:232) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at net.md_5.bungee.protocol.packet.Team.handle(Team.java:124) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:105) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:425) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
[22:34:10 INFO]: [DuckyBlender] disconnected with: The server you were previously on went down, you have been connected to a fallback server
[22:34:10 INFO]: [/89.64.91.57:52896|DuckyBlender] -> UpstreamBridge has disconnected
[22:34:10 INFO]: [/89.64.91.57:52896|DuckyBlender] <-> DownstreamBridge <-> [survival] has disconnected`

I have got these plugins on my Survival Server:
`Plugins (29): AdvancedBan*, AuthMe, BuycraftX, ChatControl, Chunky, ColorCodes*, CoordinatesHud, CoreProtect, DiscordSRV, DiscordSRV-Staff-Chat, dynmap*, Essentials, EssentialsChat, Graves, GSit, Harbor, Holograms, InteractiveChat, LuckPerms, PlaceholderAPI, ProtocolLib, SkinsRestorer, TAB, TitleManager, TradeSystem, TrollBoss, Vault, ViaVersion, WorldBorder`

I really need help. Any ideas will be greatly appreciated.

**Comment by DuckyBlender** [comment]
Nevermind, I was using Waterfall how did I not notice this.
