### ISSUE TITLE
hello i am getting this error 

### ISSUE THREAD

**Issue by mangotango69202** [SpigotMC/BungeeCord#2975]
08:07:43 [INFO] Using mbed TLS based native cipher.
08:07:43 [INFO] Using zlib based native compressor.
08:07:43 [INFO] Enabled BungeeCord version git:BungeeCord-Bootstrap:1.16-R0.4-SNAPSHOT:c987ee1:1536
08:07:43 [INFO] Not on Windows, attempting to use enhanced EpollEventLoop
08:07:44 [INFO] Epoll is working, utilising it!
08:07:44 [INFO] Discovered module: ModuleSpec(name=cmd_alert, file=modules/cmd_alert.jar, provider=JenkinsModuleSource())
08:07:44 [INFO] Discovered module: ModuleSpec(name=cmd_find, file=modules/cmd_find.jar, provider=JenkinsModuleSource())
08:07:44 [INFO] Discovered module: ModuleSpec(name=cmd_list, file=modules/cmd_list.jar, provider=JenkinsModuleSource())
08:07:44 [INFO] Discovered module: ModuleSpec(name=cmd_send, file=modules/cmd_send.jar, provider=JenkinsModuleSource())
08:07:44 [INFO] Discovered module: ModuleSpec(name=cmd_server, file=modules/cmd_server.jar, provider=JenkinsModuleSource())
08:07:44 [INFO] Discovered module: ModuleSpec(name=reconnect_yaml, file=modules/reconnect_yaml.jar, provider=JenkinsModuleSource())
08:07:44 [INFO] Loaded plugin reconnect_yaml version git:reconnect_yaml:1.16-R0.4-SNAPSHOT:c987ee1:1536 by SpigotMC
08:07:44 [INFO] Loaded plugin cmd_find version git:cmd_find:1.16-R0.4-SNAPSHOT:c987ee1:1536 by SpigotMC
08:07:44 [INFO] Loaded plugin cmd_server version git:cmd_server:1.16-R0.4-SNAPSHOT:c987ee1:1536 by SpigotMC
08:07:44 [INFO] Loaded plugin cmd_alert version git:cmd_alert:1.16-R0.4-SNAPSHOT:c987ee1:1536 by SpigotMC
08:07:44 [INFO] Loaded plugin cmd_send version git:cmd_send:1.16-R0.4-SNAPSHOT:c987ee1:1536 by SpigotMC
08:07:44 [INFO] Loaded plugin cmd_list version git:cmd_list:1.16-R0.4-SNAPSHOT:c987ee1:1536 by SpigotMC
08:07:44 [SEVERE] Exception in thread "main" 
08:07:44 [SEVERE] java.lang.ClassCastException: java.lang.String incompatible with java.util.Map
08:07:44 [SEVERE]     at net.md_5.bungee.conf.YamlConfig.load(YamlConfig.java:102)
08:07:44 [SEVERE]     at net.md_5.bungee.conf.Configuration.load(Configuration.java:71)
08:07:44 [SEVERE]     at net.md_5.bungee.BungeeCord.start(BungeeCord.java:272)
08:07:44 [SEVERE]     at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
08:07:44 [SEVERE]     at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

[config.zip](https://github.com/SpigotMC/BungeeCord/files/5363841/config.zip)
this contains both the yml and the server.properties i cant upload them bec they are not supported so i zipped this

**Comment by Janmm14** [comment]
Please use spigotmc.org forums next time for configurafion help.
These github issues are meant for errors in the software, not for errors in its usage.

You are missing `:` after your minecraft name in the groups section.
