### ISSUE TITLE
io.netty.util.concurrent.AbstractEventExecutor safeExecute

### ISSUE THREAD

**Issue by NekoFathari** [SpigotMC/BungeeCord#3005]
Can't you help me fix this problem? 

io.netty.util.concurrent.AbstractEventExecutor safeExecute
WARNING: A task raised an exception. Task: net.md_5.bungee.connection.InitialHandler$6$1@262cbe8b
java.lang.NullPointerException: info
at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:787)
at net.md_5.bungee.UserConnection.connect(UserConnection.java:252)
at net.md_5.bungee.connection.InitialHandler$6$1.run(InitialHandler.java:550)
at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at java.lang.Thread.run(Unknown Source)

**Comment by terrarier2111** [comment]
I have the same problem.

**Comment by Janmm14** [comment]
My first guesses: Invalid config or some plugin error of a plugin which decides where to send players joining bungee.

**Comment by terrarier2111** [comment]
First of all in my case i don't have such a plugin and i can provide the config so that you can check if it's correct: server_connect_timeout: 5000
listeners:
- query_port: 25577
  motd: '&1Another Bungee server'
  priorities:
  - Lobby-1
  bind_local_address: true
  tab_list: SERVER
  query_enabled: false
  host: 0.0.0.0:25565
  forced_hosts:
    pvp.md-5.net: pvp
  max_players: 100
  tab_size: 60
  ping_passthrough: false
  force_default_server: true
  proxy_protocol: false
remote_ping_cache: -1
network_compression_threshold: 256
permissions:
  default:
  - system.msg
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
log_pings: true
connection_throttle_limit: 3
prevent_proxy_connections: false
timeout: 30000
inject_commands: false
player_limit: -1
ip_forward: true
groups:
  terrarier2111:
  - admin
remote_ping_timeout: 5000
connection_throttle: 4000
log_commands: false
stats: A_RANDOM_UUID
online_mode: true
forge_support: false
disabled_commands:
- disabledcommandhere
servers:
  Lobby-1:
    motd: '&1Lobby-1'
    address: localhost:A_PORT
    restricted: false
