### ISSUE TITLE
Bungeecord error

### ISSUE THREAD

**Issue by mintsoda2020** [SpigotMC/BungeeCord#3024]
23:48:28 [정보] Using standard Java JCE cipher.
23:48:28 [정보] Using standard Java compressor.
23:48:28 [정보] Enabled BungeeCord version git:BungeeCord-Bootstrap:1.16-R0.5-SNAPSHOT:9f6a798:1543
23:48:28 [정보] Discovered module: ModuleSpec(name=cmd_alert, file=modules\cmd_alert.jar, provider=JenkinsModuleSource())
23:48:28 [정보] Discovered module: ModuleSpec(name=cmd_find, file=modules\cmd_find.jar, provider=JenkinsModuleSource())
23:48:28 [정보] Discovered module: ModuleSpec(name=cmd_list, file=modules\cmd_list.jar, provider=JenkinsModuleSource())
23:48:28 [정보] Discovered module: ModuleSpec(name=cmd_send, file=modules\cmd_send.jar, provider=JenkinsModuleSource())
23:48:28 [정보] Discovered module: ModuleSpec(name=cmd_server, file=modules\cmd_server.jar, provider=JenkinsModuleSource())
23:48:28 [정보] Discovered module: ModuleSpec(name=reconnect_yaml, file=modules\reconnect_yaml.jar, provider=JenkinsModuleSource())
23:48:28 [정보] Loaded plugin reconnect_yaml version git:reconnect_yaml:1.16-R0.5-SNAPSHOT:9f6a798:1543 by SpigotMC
23:48:28 [정보] Loaded plugin cmd_find version git:cmd_find:1.16-R0.5-SNAPSHOT:9f6a798:1543 by SpigotMC
23:48:28 [정보] Loaded plugin BungeeMotd version 1.2 by Falistos
23:48:28 [정보] Loaded plugin cmd_server version git:cmd_server:1.16-R0.5-SNAPSHOT:9f6a798:1543 by SpigotMC
23:48:28 [정보] Loaded plugin cmd_alert version git:cmd_alert:1.16-R0.5-SNAPSHOT:9f6a798:1543 by SpigotMC
23:48:28 [정보] Loaded plugin cmd_send version git:cmd_send:1.16-R0.5-SNAPSHOT:9f6a798:1543 by SpigotMC
23:48:28 [정보] Loaded plugin cmd_list version git:cmd_list:1.16-R0.5-SNAPSHOT:9f6a798:1543 by SpigotMC
23:48:28 [경고] Forced host server pvp is not defined
23:48:28 [정보] Enabled plugin reconnect_yaml version git:reconnect_yaml:1.16-R0.5-SNAPSHOT:9f6a798:1543 by SpigotMC
23:48:28 [정보] Enabled plugin cmd_find version git:cmd_find:1.16-R0.5-SNAPSHOT:9f6a798:1543 by SpigotMC
23:48:28 [정보] Enabled plugin BungeeMotd version 1.2 by Falistos
23:48:28 [정보] Enabled plugin cmd_server version git:cmd_server:1.16-R0.5-SNAPSHOT:9f6a798:1543 by SpigotMC
23:48:28 [정보] Enabled plugin cmd_alert version git:cmd_alert:1.16-R0.5-SNAPSHOT:9f6a798:1543 by SpigotMC
23:48:28 [정보] Enabled plugin cmd_send version git:cmd_send:1.16-R0.5-SNAPSHOT:9f6a798:1543 by SpigotMC
23:48:28 [정보] Enabled plugin cmd_list version git:cmd_list:1.16-R0.5-SNAPSHOT:9f6a798:1543 by SpigotMC
23:48:29 [경고] Could not bind to host snetwork.kro.kr/118.32.98.169:25565
java.net.BindException: Cannot assign requested address: bind
    at sun.nio.ch.Net.bind0(Native Method)
    at sun.nio.ch.Net.bind(Unknown Source)
    at sun.nio.ch.Net.bind(Unknown Source)
    at sun.nio.ch.ServerSocketChannelImpl.bind(Unknown Source)
    at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:134)
    at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:550)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1334)
    at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:506)
    at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:491)
    at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:973)
    at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:248)
    at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:356)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at java.lang.Thread.run(Unknown Source)
    
    why is this error happening..?
    please help me...

정보 = INFO
경고 = WARN

**Comment by Janmm14** [comment]
The ip address you requested is not assigned to the server where you ran bungeecord on.

**Comment by mintsoda2020** [comment]
i need solution..
