### ISSUE TITLE
Error in console when players connect

### ISSUE THREAD

**Issue by Mirt90** [SpigotMC/BungeeCord#3064]
`[09:54:46 ERROR]: java.io.EOFException
[09:54:46 ERROR]:       at java.io.DataInputStream.readFully(DataInputStream.java:197)
[09:54:46 ERROR]:       at java.io.DataInputStream.readUTF(DataInputStream.java:609)
[09:54:46 ERROR]:       at java.io.DataInputStream.readUTF(DataInputStream.java:564)
[09:54:46 ERROR]:       at com.lielamar.auth.bungee.listeners.OnPluginMessage.onQueryReceive(OnPluginMessage.java:43)
[09:54:46 ERROR]:       at sun.reflect.GeneratedMethodAccessor53.invoke(Unknown Source)
[09:54:46 ERROR]:       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[09:54:46 ERROR]:       at java.lang.reflect.Method.invoke(Method.java:498)
[09:54:46 ERROR]:       at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
[09:54:46 ERROR]:       at net.md_5.bungee.event.EventBus.post(EventBus.java:47)
[09:54:46 ERROR]:       at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:453)
[09:54:46 ERROR]:       at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:283)
[09:54:46 ERROR]:       at net.md_5.bungee.protocol.packet.PluginMessage.handle(PluginMessage.java:122)
[09:54:46 ERROR]:       at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:124)
[09:54:46 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[09:54:46 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[09:54:46 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[09:54:46 ERROR]:       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[09:54:46 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[09:54:46 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[09:54:46 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[09:54:46 ERROR]:       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[09:54:46 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[09:54:46 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[09:54:46 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[09:54:46 ERROR]:       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[09:54:46 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[09:54:46 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[09:54:46 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[09:54:46 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
[09:54:46 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311)
[09:54:46 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:425)
[09:54:46 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
[09:54:46 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[09:54:46 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[09:54:46 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[09:54:46 ERROR]:       at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[09:54:46 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[09:54:46 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[09:54:46 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[09:54:46 ERROR]:       at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[09:54:46 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[09:54:46 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[09:54:46 ERROR]:       at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[09:54:46 ERROR]:       at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
[09:54:46 ERROR]:       at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475)
[09:54:46 ERROR]:       at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
[09:54:46 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[09:54:46 ERROR]:       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[09:54:46 ERROR]:       at java.lang.Thread.run(Thread.java:748)`

**Comment by md-5** [comment]
com.lielamar.auth.bungee.listeners.OnPluginMessage.onQueryReceive(OnPluginMessage.java:43) [09:54:46 ER

Issue with this plugin
