### ISSUE TITLE
Error occurred while contacting login servers, are they down? --Help me please!

### ISSUE THREAD

**Issue by WolfieBoyy** [SpigotMC/BungeeCord#3072]
I keep getting the error "Error occurred while contacting login servers, are they down?" and no matter what I do it doesn't stop, I can connect to other servers fine, just not my one. Im running this off a ubuntu 18.04 VPS on Azure. I have updated everything, checked the dns, and so on, but only I get this error, no-one else does. ------19:30:09 [SEVERE] Error authenticating WolfieBoy_5868 with minecraft.net
net.pretronic.databasequery.api.exceptions.DatabaseQueryExecuteFailedException: [McNative] (Database-Driver) default - Error executing sql query: SELECT * FROM `mcnative_players`  WHERE `UniqueId`=?
    at net.pretronic.databasequery.sql.SQLDatabase.handleDatabaseQueryExecuteFailedException(SQLDatabase.java:196)
    at net.pretronic.databasequery.sql.SQLDatabase.lambda$executeResultQuery$1(SQLDatabase.java:142)
    at net.pretronic.databasequery.sql.SQLDatabase.executeResultQuery(SQLDatabase.java:134)
    at net.pretronic.databasequery.sql.SQLDatabase.executeResultQuery(SQLDatabase.java:141)
    at net.pretronic.databasequery.sql.query.type.SQLFindQuery.execute(SQLFindQuery.java:52)
    at net.pretronic.databasequery.sql.query.type.SQLFindQuery.execute(SQLFindQuery.java:44)
    at net.pretronic.databasequery.api.query.Query.execute(Query.java:44)
    at org.mcnative.runtime.common.player.data.DefaultPlayerDataProvider.getPlayerData(DefaultPlayerDataProvider.java:84)
    at org.mcnative.runtime.bungeecord.event.McNativeBridgeEventHandler.handleLogin(McNativeBridgeEventHandler.java:183)
    at org.mcnative.runtime.bungeecord.plugin.McNativeBungeeEventBus.post(McNativeBungeeEventBus.java:65)
    at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:412)
    at net.md_5.bungee.connection.InitialHandler.finish(InitialHandler.java:560)
    at net.md_5.bungee.connection.InitialHandler.access$700(InitialHandler.java:70)
    at net.md_5.bungee.connection.InitialHandler$5.done(InitialHandler.java:453)
    at net.md_5.bungee.connection.InitialHandler$5.done(InitialHandler.java:441)
    at net.md_5.bungee.http.HttpHandler.done(HttpHandler.java:68)
    at net.md_5.bungee.http.HttpHandler.channelRead0(HttpHandler.java:59)
    at net.md_5.bungee.http.HttpHandler.channelRead0(HttpHandler.java:14)
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
    at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1533)
    at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1282)
    at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1329)
    at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:508)
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:447)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
    at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: General error: "java.lang.NullPointerException"; SQL statement:
SELECT * FROM `mcnative_players`  WHERE `UniqueId`=? [50000-200]
    at org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
    at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
    at org.h2.message.DbException.get(DbException.java:194)
    at org.h2.message.DbException.convert(DbException.java:347)
    at org.h2.command.Command.executeQuery(Command.java:212)
    at org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:114)
    at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
    at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
    at net.pretronic.databasequery.sql.SQLDatabase.executeResultQuery(SQLDatabase.java:126)
    ... 49 more
Caused by: java.lang.NullPointerException
    at org.h2.mvstore.db.LobStorageMap.copyLob(LobStorageMap.java:259)
    at org.h2.value.ValueLobDb.copyToResult(ValueLobDb.java:557)
    at org.h2.value.ValueLobDb.copyToResult(ValueLobDb.java:41)
    at org.h2.result.LocalResultImpl.cloneLobs(LocalResultImpl.java:289)
    at org.h2.result.LocalResultImpl.addRow(LocalResultImpl.java:325)
    at org.h2.command.dml.Select.queryFlat(Select.java:739)
    at org.h2.command.dml.Select.queryWithoutCache(Select.java:844)
    at org.h2.command.dml.Query.queryWithoutCacheLazyCheck(Query.java:201)
    at org.h2.command.dml.Query.query(Query.java:489)
    at org.h2.command.dml.Query.query(Query.java:451)
    at org.h2.command.CommandContainer.query(CommandContainer.java:285)
    at org.h2.command.Command.executeQuery(Command.java:195)
    ... 53 more
>
------

**Comment by WolfieBoyy** [comment]
Also md-5 don't close this because I seriously don't know what to do.

**Comment by Janmm14** [comment]
He will close this because it is a plugin problem.

**Comment by md-5** [comment]
Issue with mcnative plugin
