### ISSUE TITLE
Help Bungeecord I can't connect to my serveur : c !

### ISSUE THREAD

**Issue by IzoukuSenpai** [SpigotMC/BungeeCord#3137]
[10:44:37 WARN] [io.netty.util.concurrent.AbstractEventExecutor]: A task raised an exception. Task: net.md_5.bungee.connection.InitialHandler$6$1@229f56c8
java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.lang.String
at net.md_5.bungee.UserConnection.addGroups(UserConnection.java:553) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:436f47f:437]
at net.md_5.bungee.UserConnection.init(UserConnection.java:171) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:436f47f:437]
at net.md_5.bungee.connection.InitialHandler$6$1.run(InitialHandler.java:549) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:436f47f:437]
at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:436f47f:437]
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:436f47f:437]
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:436f47f:437]
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:436f47f:437]
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:436f47f:437]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]

**Comment by IzoukuSenpai** [comment]
If you want to help me add me on discord Izouku_Senpai#9244

**Comment by Janmm14** [comment]
That is not how this works. We don'T contact you on discord to hlep you. If you write here, we answer here.

Your group section in bungee's config is malformed.
