### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by emanuelVINI01** [SpigotMC/BungeeCord#3145]
23:10:09 [SEVERE] Exception in thread "main" 
23:10:09 [SEVERE] java.util.ConcurrentModificationException
23:10:09 [SEVERE]     at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719)
23:10:09 [SEVERE]     at java.util.LinkedHashMap$LinkedValueIterator.next(LinkedHashMap.java:747)
23:10:09 [SEVERE]     at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:261)
23:10:09 [SEVERE]     at net.md_5.bungee.BungeeCord.start(BungeeCord.java:287)
23:10:09 [SEVERE]     at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
23:10:09 [SEVERE]     at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

**Comment by emanuelVINI01** [comment]
@md-5
