### ISSUE TITLE
getOnline exception

### ISSUE THREAD

**Issue by WongIong** [SpigotMC/BungeeCord#3192]
I am using Serverlistplus and turned "hideplayer" on. after that i get this message.

00:38:56 [SEVERE] [/139.162.68.13:57608] <-> InitialHandler - encountered exception
java.lang.NullPointerException: Cannot invoke "net.md_5.bungee.api.ServerPing$Players.getOnline()" because the return value of "net.md_5.bungee.api.ServerPing.getPlayers()" is null
at net.md_5.bungee.connection.InitialHandler$2.done(InitialHandler.java:199)
at net.md_5.bungee.connection.InitialHandler$2.done(InitialHandler.java:181)
at net.md_5.bungee.api.event.AsyncEvent.postCall(AsyncEvent.java:40)
at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:413)
at net.md_5.bungee.connection.InitialHandler.handle(InitialHandler.java:213)
at net.md_5.bungee.protocol.packet.LegacyPing.handle(LegacyPing.java:33)
at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:114)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
at org.geysermc.floodgate.addon.data.BungeeProxyDataHandler.channelRead(BungeeProxyDataHandler.java:101)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
at org.geysermc.floodgate.addon.data.PacketBlocker.channelRead(PacketBlocker.java:72)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:302)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311)
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:432)
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by xIsm4** [comment]
Just update ur BungeeCord i guess.

**Comment by xIsm4** [comment]
> Just update ur BungeeCord i guess, and stop using outdated MOTD plugins (I recommend u, to use the Motd of BungeeCord) Or CleanMotd.

**Comment by WongIong** [comment]
I am using SLP's branch, which is the newest version with bugs fixed.
Also i have updated the BC to the newest version then.

**Comment by MrIvanPlays** [comment]
Not BungeeCord's problem. 
ServerListPlus sets the players to null if the option mentioned is enabled. 
https://github.com/Minecrell/ServerListPlus/blob/master/Bungee/src/main/java/net/minecrell/serverlistplus/bungee/BungeePlugin.java#L217

This `null` set is calling the exception. So they should change it.

**Comment by Minecrell** [comment]
> This null set is calling the exception. So they should change it.

Setting this to `null` (effectively removing all player related information from the JSON generated from the `ServerPing`) will make the client display `???` instead of the player count. Like in this [example from the SLP wiki](https://github.com/Minecrell/ServerListPlus/wiki/Player-Slots):

![](https://cloud.githubusercontent.com/assets/3035868/3996274/df4ea102-2933-11e4-882a-b0c736df3ed5.png)

This has been a configuration option in SLP for a long time and I'm quite sure it used to work correctly.

---

Ah, looks like it only happens for legacy pings (does anyone still use MC < 1.7 nowadays??):

`at net.md_5.bungee.protocol.packet.LegacyPing.handle(LegacyPing.java:33)`

Looks like `InitialHandler.handle(LegacyPing ping)` doesn't handle `getPlayers()` returning null. iirc the way to achieve the same  effect for ancient legacy clients was to put `-1` in the online/max player count. So would just need to add some null checks there to handle this properly.

**Comment by xIsm4** [comment]
> Not BungeeCord's problem. ServerListPlus sets the players to null if the option mentioned is enabled. https://github.com/Minecrell/ServerListPlus/blob/master/Bungee/src/main/java/net/minecrell/serverlistplus/bungee/BungeePlugin.java#L217
> 
> This `null` set is calling the exception. So they should change it.


Well i mean, it's more used 1.7x than 1.15 and 1.8x

**Comment by WongIong** [comment]
But this problem shows up when i am using a 1.16 Client.
It does show me the ??? player count.
But console will spam these error.
