### ISSUE TITLE
Im get error: 08:10:48 [SEVERE] at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

### ISSUE THREAD

**Issue by Tykkiproo12** [SpigotMC/BungeeCord#3284]
Full log: 

08:10:47 [INFO] Using mbed TLS based native cipher.
2 | 08:10:47 [INFO] Using zlib based native compressor.
3 | 08:10:47 [INFO] Enabled BungeeCord version git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:34d416a:1635
4 | 08:10:47 [INFO] Not on Windows, attempting to use enhanced EpollEventLoop
5 | 08:10:47 [INFO] Epoll is working, utilising it!
6 | 08:10:47 [INFO] Discovered module: ModuleSpec(name=cmd_alert, file=modules/cmd_alert.jar, provider=JenkinsModuleSource())
7 | 08:10:47 [INFO] Discovered module: ModuleSpec(name=cmd_find, file=modules/cmd_find.jar, provider=JenkinsModuleSource())
8 | 08:10:47 [INFO] Discovered module: ModuleSpec(name=cmd_list, file=modules/cmd_list.jar, provider=JenkinsModuleSource())
9 | 08:10:47 [INFO] Discovered module: ModuleSpec(name=cmd_send, file=modules/cmd_send.jar, provider=JenkinsModuleSource())
10 | 08:10:47 [INFO] Discovered module: ModuleSpec(name=cmd_server, file=modules/cmd_server.jar, provider=JenkinsModuleSource())
11 | 08:10:47 [INFO] Discovered module: ModuleSpec(name=reconnect_yaml, file=modules/reconnect_yaml.jar, provider=JenkinsModuleSource())
12 | 08:10:47 [INFO] Loaded plugin reconnect_yaml version git:reconnect_yaml:1.18-R0.1-SNAPSHOT:34d416a:1635 by SpigotMC
13 | 08:10:47 [INFO] Loaded plugin LuckPerms version 5.4.9 by Luck
14 | 08:10:47 [WARNING] Error loading plugin Essentials
15 | java.lang.NoClassDefFoundError: org/bukkit/plugin/Plugin
16 | at java.base/java.lang.ClassLoader.defineClass1(Native Method)
17 | at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
18 | at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
19 | at net.md_5.bungee.api.plugin.PluginClassloader.findClass(PluginClassloader.java:152)
20 | at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
21 | at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:66)
22 | at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59)
23 | at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
24 | at java.base/java.lang.ClassLoader.defineClass1(Native Method)
25 | at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
26 | at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
27 | at net.md_5.bungee.api.plugin.PluginClassloader.findClass(PluginClassloader.java:152)
28 | at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
29 | at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:66)
30 | at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59)
31 | at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
32 | at java.base/java.lang.ClassLoader.defineClass1(Native Method)
33 | at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
34 | at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
35 | at net.md_5.bungee.api.plugin.PluginClassloader.findClass(PluginClassloader.java:152)
36 | at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
37 | at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:66)
38 | at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59)
39 | at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
40 | at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:340)
41 | at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:250)
42 | at net.md_5.bungee.BungeeCord.start(BungeeCord.java:271)
43 | at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
44 | at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
45 | Caused by: java.lang.ClassNotFoundException: org.bukkit.plugin.Plugin
46 | at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:103)
47 | at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59)
48 | at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
49 | ... 29 more
50 | 08:10:47 [INFO] Loaded plugin ExarotonBungeePlugin version 1.0.0 by null
51 | 08:10:47 [INFO] Loaded plugin BungeeGuard version 1.2-SNAPSHOT by Luck
52 | 08:10:47 [WARNING] Error loading plugin AntiCheatReloaded
53 | java.lang.NoClassDefFoundError: org/bukkit/plugin/java/JavaPlugin
54 | at java.base/java.lang.ClassLoader.defineClass1(Native Method)
55 | at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
56 | at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
57 | at net.md_5.bungee.api.plugin.PluginClassloader.findClass(PluginClassloader.java:152)
58 | at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
59 | at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:66)
60 | at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59)
61 | at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
62 | at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:340)
63 | at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:250)
64 | at net.md_5.bungee.BungeeCord.start(BungeeCord.java:271)
65 | at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
66 | at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
67 | Caused by: java.lang.ClassNotFoundException: org.bukkit.plugin.java.JavaPlugin
68 | at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:103)
69 | at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59)
70 | at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
71 | ... 13 more
72 | 08:10:47 [INFO] Loaded plugin cmd_list version git:cmd_list:1.18-R0.1-SNAPSHOT:34d416a:1635 by SpigotMC
73 | 08:10:47 [WARNING] Error loading plugin EssentialsChat
74 | java.lang.NoClassDefFoundError: org/bukkit/plugin/java/JavaPlugin
75 | at java.base/java.lang.ClassLoader.defineClass1(Native Method)
76 | at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
77 | at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
78 | at net.md_5.bungee.api.plugin.PluginClassloader.findClass(PluginClassloader.java:152)
79 | at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
80 | at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:66)
81 | at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59)
82 | at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
83 | at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:340)
84 | at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:250)
85 | at net.md_5.bungee.BungeeCord.start(BungeeCord.java:271)
86 | at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
87 | at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
88 | Caused by: java.lang.ClassNotFoundException: org.bukkit.plugin.java.JavaPlugin
89 | at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:103)
90 | at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59)
91 | at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
92 | ... 13 more
93 | 08:10:47 [WARNING] Error loading plugin Geyser-BungeeCord
94 | java.lang.UnsupportedClassVersionError: org/geysermc/geyser/platform/bungeecord/GeyserBungeePlugin has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 55.0
95 | at java.base/java.lang.ClassLoader.defineClass1(Native Method)
96 | at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
97 | at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
98 | at net.md_5.bungee.api.plugin.PluginClassloader.findClass(PluginClassloader.java:152)
99 | at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
100 | at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:66)
101 | at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59)
102 | at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
103 | at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:340)
104 | at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:250)
105 | at net.md_5.bungee.BungeeCord.start(BungeeCord.java:271)
106 | at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
107 | at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
108 | 08:10:47 [INFO] Loaded plugin cmd_find version git:cmd_find:1.18-R0.1-SNAPSHOT:34d416a:1635 by SpigotMC
109 | 08:10:47 [INFO] Loaded plugin AdvancedBan version 2.3.0 by Leoko
110 | 08:10:47 [INFO] Loaded plugin cmd_server version git:cmd_server:1.18-R0.1-SNAPSHOT:34d416a:1635 by SpigotMC
111 | 08:10:47 [INFO] Loaded plugin cmd_alert version git:cmd_alert:1.18-R0.1-SNAPSHOT:34d416a:1635 by SpigotMC
112 | 08:10:48 [WARNING] [floodgate] en_ is not a supported Floodgate language.
113 | 08:10:48 [INFO] [floodgate] Took 189ms to boot Floodgate
114 | 08:10:48 [INFO] Loaded plugin floodgate version 2.1.0-SNAPSHOT by GeyserMC
115 | 08:10:48 [INFO] Loaded plugin ServerSwitcher version 1.9 by Troydesante
116 | 08:10:48 [INFO] Loaded plugin cmd_send version git:cmd_send:1.18-R0.1-SNAPSHOT:34d416a:1635 by SpigotMC
117 | 08:10:48 [SEVERE] Exception in thread "main"
118 | 08:10:48 [SEVERE] java.lang.IllegalArgumentException: Invalid host/address: combomaa_lobby.exaroton.me:32509
119 | 08:10:48 [SEVERE] 	at net.md_5.bungee.Util.getAddr(Util.java:55)
120 | 08:10:48 [SEVERE] 	at net.md_5.bungee.conf.YamlConfig.getServers(YamlConfig.java:221)
121 | 08:10:48 [SEVERE] 	at net.md_5.bungee.conf.Configuration.load(Configuration.java:106)
122 | 08:10:48 [SEVERE] 	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:272)
123 | 08:10:48 [SEVERE] 	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
124 | 08:10:48 [SEVERE] 	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
125

<br class="Apple-interchange-newline">08:10:47 [INFO] Using mbed TLS based native cipher.
08:10:47 [INFO] Using zlib based native compressor.
08:10:47 [INFO] Enabled BungeeCord version git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:34d416a:1635
08:10:47 [INFO] Not on Windows, attempting to use enhanced EpollEventLoop
08:10:47 [INFO] Epoll is working, utilising it!
08:10:47 [INFO] Discovered module: ModuleSpec(name=cmd_alert, file=modules/cmd_alert.jar, provider=JenkinsModuleSource())
08:10:47 [INFO] Discovered module: ModuleSpec(name=cmd_find, file=modules/cmd_find.jar, provider=JenkinsModuleSource())
08:10:47 [INFO] Discovered module: ModuleSpec(name=cmd_list, file=modules/cmd_list.jar, provider=JenkinsModuleSource())
08:10:47 [INFO] Discovered module: ModuleSpec(name=cmd_send, file=modules/cmd_send.jar, provider=JenkinsModuleSource())
08:10:47 [INFO] Discovered module: ModuleSpec(name=cmd_server, file=modules/cmd_server.jar, provider=JenkinsModuleSource())
08:10:47 [INFO] Discovered module: ModuleSpec(name=reconnect_yaml, file=modules/reconnect_yaml.jar, provider=JenkinsModuleSource())
08:10:47 [INFO] Loaded plugin reconnect_yaml version git:reconnect_yaml:1.18-R0.1-SNAPSHOT:34d416a:1635 by SpigotMC
08:10:47 [INFO] Loaded plugin LuckPerms version 5.4.9 by Luck
08:10:47 [WARNING] Error loading plugin Essentials
java.lang.NoClassDefFoundError: org/bukkit/plugin/Plugin
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at net.md_5.bungee.api.plugin.PluginClassloader.findClass(PluginClassloader.java:15[2](https://exaroton.com/log/#L2))
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:66)
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at net.md_5.bungee.api.plugin.PluginClassloader.findClass(PluginClassloader.java:152)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:66)
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at net.md_5.bungee.api.plugin.PluginClassloader.findClass(PluginClassloader.java:152)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:66)
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:[3](https://exaroton.com/log/#L3)[4](https://exaroton.com/log/#L4)0)
	at net.md_[5](https://exaroton.com/log/#L5).bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:250)
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:271)
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:[6](https://exaroton.com/log/#L6)[7](https://exaroton.com/log/#L7))
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: java.lang.ClassNotFoundException: org.bukkit.plugin.Plugin
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:103)
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 29 more
0[8](https://exaroton.com/log/#L8):10:47 [INFO] Loaded plugin ExarotonBungeePlugin version 1.0.0 by null
08:10:47 [INFO] Loaded plugin BungeeGuard version 1.2-SNAPSHOT by Luck
08:10:47 [WARNING] Error loading plugin AntiCheatReloaded
java.lang.NoClassDefFoundError: org/bukkit/plugin/java/JavaPlugin
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at net.md_5.bungee.api.plugin.PluginClassloader.findClass(PluginClassloader.java:152)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:58[9](https://exaroton.com/log/#L9))
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:66)
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:340)
	at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:250)
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:271)
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: java.lang.ClassNotFoundException: org.bukkit.plugin.java.JavaPlugin
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:[10](https://exaroton.com/log/#L10)3)
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... [13](https://exaroton.com/log/#L13) more
08:10:47 [INFO] Loaded plugin cmd_list version git:cmd_list:1.18-R0.1-SNAPSHOT:34d416a:1635 by SpigotMC
08:10:47 [WARNING] Error loading plugin EssentialsChat
java.lang.NoClassDefFoundError: org/bukkit/plugin/java/JavaPlugin
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at net.md_5.bungee.api.plugin.PluginClassloader.findClass(PluginClassloader.java:[15](https://exaroton.com/log/#L15)2)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:66)
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:340)
	at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:250)
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:271)
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: java.lang.ClassNotFoundException: org.bukkit.plugin.java.JavaPlugin
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:103)
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 13 more
08:10:47 [WARNING] Error loading plugin Geyser-BungeeCord
java.lang.UnsupportedClassVersionError: org/geysermc/geyser/platform/bungeecord/GeyserBungeePlugin has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 55.0
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at net.md_5.bungee.api.plugin.PluginClassloader.findClass(PluginClassloader.java:152)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:66)
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:340)
	at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:250)
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:271)
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
08:10:47 [INFO] Loaded plugin cmd_find version git:cmd_find:1.18-R0.1-SNAPSHOT:34d4[16](https://exaroton.com/log/#L16)a:1635 by SpigotMC
08:10:47 [INFO] Loaded plugin AdvancedBan version 2.3.0 by Leoko
08:10:47 [INFO] Loaded plugin cmd_server version git:cmd_server:1.[18](https://exaroton.com/log/#L18)-R0.1-SNAPSHOT:34d416a:1635 by SpigotMC
08:10:47 [INFO] Loaded plugin cmd_alert version git:cmd_alert:1.18-R0.1-SNAPSHOT:34d416a:1635 by SpigotMC
08:10:48 [WARNING] [floodgate] en_ is not a supported Floodgate language.
08:10:48 [INFO] [floodgate] Took 189ms to boot Floodgate
08:10:48 [INFO] Loaded plugin floodgate version 2.1.0-SNAPSHOT by GeyserMC
08:10:48 [INFO] Loaded plugin ServerSwitcher version 1.9 by Troydesante
08:10:48 [INFO] Loaded plugin cmd_send version git:cmd_send:1.18-R0.1-SNAPSHOT:34d416a:1635 by SpigotMC
08:10:48 [SEVERE] Exception in thread "main" 
08:10:48 [SEVERE] java.lang.IllegalArgumentException: Invalid host/address: combomaa_lobby.exaroton.me:32509
08:10:48 [SEVERE] 	at net.md_5.bungee.Util.getAddr(Util.java:55)
08:10:48 [SEVERE] 	at net.md_5.bungee.conf.YamlConfig.getServers(YamlConfig.java:2[21](https://exaroton.com/log/#L21))
08:10:48 [SEVERE] 	at net.md_5.bungee.conf.Configuration.load(Configuration.java:106)
08:10:48 [SEVERE] 	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:[27](https://exaroton.com/log/#L27)2)
08:10:[48](https://exaroton.com/log/#L48) [SEVERE] 	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:[67](https://exaroton.com/log/#L67))
08:10:48 [SEVERE] 	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

**Comment by md-5** [comment]
You can't put bukkit plugins on bungee, and underscores are not valid domain names.

Use the forums for help please, this is a bug tracker.
