### ISSUE TITLE
Cannot connect to the server

### ISSUE THREAD

**Issue by f0xu2137** [SpigotMC/BungeeCord#3313]
![image](https://user-images.githubusercontent.com/57212337/172458530-ce9ea329-f48e-4f5b-834e-3fad72e65bc6.png)
0 plugins...
1.8.9 Client

**Comment by bob7l** [comment]
It's not currently compatible with cracked clients

**Comment by f0xu2137** [comment]
> 

I have minecraft premium

**Comment by fabegalo** [comment]
Same error

**Comment by md-5** [comment]
> I have minecraft premium

Your bungee is cracked though

**Comment by Camotoy** [comment]
I think this error still persists with offline mode BungeeCord, CI build #1639, and no plugins.

```
19:03:37 [INFO] [/127.0.0.1:54314] <-> InitialHandler has connected
19:03:37 [SEVERE] [Camotoy,/127.0.0.1:54314] <-> InitialHandler - encountered exception
io.netty.handler.codec.EncoderException: java.lang.NullPointerException: Cannot read the array length because "properties" is null
    at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
    at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
    at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
    at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
    at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
    at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020)
    at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311)
    at net.md_5.bungee.netty.ChannelWrapper.write(ChannelWrapper.java:60)
    at net.md_5.bungee.connection.InitialHandler$1.sendPacket(InitialHandler.java:96)
    at net.md_5.bungee.connection.InitialHandler$6$1.run(InitialHandler.java:553)
    at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:391)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.lang.NullPointerException: Cannot read the array length because "properties" is null
    at net.md_5.bungee.protocol.DefinedPacket.writeProperties(DefinedPacket.java:219)
    at net.md_5.bungee.protocol.packet.LoginSuccess.write(LoginSuccess.java:55)
    at net.md_5.bungee.protocol.MinecraftEncoder.encode(MinecraftEncoder.java:24)
    at net.md_5.bungee.protocol.MinecraftEncoder.encode(MinecraftEncoder.java:9)
    at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
    ... 16 more
```

**Comment by Camotoy** [comment]
The above issue is now resolved.
