### ISSUE TITLE
Cannot spoof chat on this client version 

### ISSUE THREAD

**Issue by xF3d33** [SpigotMC/BungeeCord#3327]
`16:12:01 [SEVERE] Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@246f8b8b, id=14238, owner=net.william278.huskchat.bungeecord.HuskChatBungee@7eb9bffa, task=net.william278.huskchat.bungeecord.listener.BungeeListener$$Lambda$2266/0x0000000801861640@5447a43d, delay=0, period=0, running=true) encountered an exception
java.lang.UnsupportedOperationException: Cannot spoof chat on this client version!
    at net.md_5.bungee.UserConnection.chat(UserConnection.java:422)
    at net.william278.huskchat.bungeecord.player.BungeePlayer.passThroughChat(BungeePlayer.java:53)
    at net.william278.huskchat.message.ChatMessage.dispatch(ChatMessage.java:86)
    at net.william278.huskchat.bungeecord.listener.BungeeListener.lambda$onPlayerChat$0(BungeeListener.java:28)
    at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.base/java.lang.Thread.run(Thread.java:833)`

**Comment by Janmm14** [comment]
Yeah. This should be made possible especially when the server does not activate the chat message validation system.

**Comment by WiIIiam278** [comment]
Hi, I'm the developer of this plugin. I've never seen "Cannot spoof chat on this client version" before - is it a new thing because of 1.19's annoying chat signing stuff?
Is there a regression with BungeeCord API that I'm not aware about? Bit confused over this one, never seen it before.

**Comment by Janmm14** [comment]
> Hi, I'm the developer of this plugin. I've never seen "Cannot spoof chat on this client version" before - is it a new thing because of 1.19's annoying chat signing stuff? Is there a regression with BungeeCord API that I'm not aware about? Bit confused over this one, never seen it before.

Yes its because of the chat signing.

**Comment by WiIIiam278** [comment]
I took a look, it's caused by this newly added bit for 1.19 handling. https://github.com/SpigotMC/BungeeCord/blob/eccdf87f2217ae3a0f6943134d8c61df3f9d0097/proxy/src/main/java/net/md_5/bungee/UserConnection.java#L420-L423
Could some clarification be provided on whether or not this is temporary? Seems a bit strange this was documented nowhere when it's an API breakage on 1.19

**Comment by md-5** [comment]
By definition you can't sign chat as the client, the whole reason Mojang added this feature is to stop things like Bungee spoofing.
Even if signing doesn't work properly in Bungee/Spigot now, it will in future and at that point spoofing will be impossible. Hence its better to stop spoofing now so it is not broken mid-version.

**Comment by WiIIiam278** [comment]
OK- so I take it #chat() is effectively deprecated, then? If so, will have to re-evaluate the approach I take.
Perhaps in the intermediary while it's still possible to disable the chat signing on the backend a toggle option for this could be provided in bungeecord? If it still works, that is.

**Comment by hsiachihMain** [comment]
yeah,i meet it too...what can i do?only say....f**k mi***soft
