### ISSUE TITLE
Error that I cannot figure out what it means

### ISSUE THREAD

**Issue by ssl42** [SpigotMC/BungeeCord#3328]
> 19:41:31 [INFO] Using mbed TLS based native cipher.
> 19:41:31 [INFO] Using zlib based native compressor.
> 19:41:31 [INFO] Enabled BungeeCord version git:BungeeCord-Bootstrap:1.19-R0.1-SNAPSHOT:ff5727c:1644
> 19:41:31 [INFO] Not on Windows, attempting to use enhanced EpollEventLoop
> 19:41:31 [INFO] Epoll is working, utilising it!
> 19:41:31 [INFO] Discovered module: ModuleSpec(name=cmd_alert, file=modules/cmd_alert.jar, provider=JenkinsModuleSource())
> 
> 19:41:31 [INFO] Discovered module: ModuleSpec(name=cmd_find, file=modules/cmd_find.jar, provider=JenkinsModuleSource())
> 
> 19:41:31 [INFO] Discovered module: ModuleSpec(name=cmd_list, file=modules/cmd_list.jar, provider=JenkinsModuleSource())
> 
> 19:41:31 [INFO] Discovered module: ModuleSpec(name=cmd_send, file=modules/cmd_send.jar, provider=JenkinsModuleSource())
> 
> 19:41:31 [INFO] Discovered module: ModuleSpec(name=cmd_server, file=modules/cmd_server.jar, provider=JenkinsModuleSource())
> 
> 19:41:31 [INFO] Discovered module: ModuleSpec(name=reconnect_yaml, file=modules/reconnect_yaml.jar, provider=JenkinsModuleSource())
> 
> 19:41:31 [INFO] Attempting to update plugin from null to ModuleVersion(build=1644, git=ff5727c)
> 
> 19:41:31 [INFO] Attempting to Jenkins download module cmd_alert v1644
> 
> 19:41:31 [INFO] Download complete
> 
> 19:41:31 [INFO] Attempting to update plugin from null to ModuleVersion(build=1644, git=ff5727c)
> 
> 19:41:31 [INFO] Attempting to Jenkins download module cmd_find v1644
> 
> 19:41:31 [INFO] Download complete
> 
> 19:41:31 [INFO] Attempting to update plugin from null to ModuleVersion(build=1644, git=ff5727c)
> 
> 19:41:31 [INFO] Attempting to Jenkins download module cmd_list v1644
> 
> 19:41:31 [INFO] Download complete
> 
> 19:41:31 [INFO] Attempting to update plugin from null to ModuleVersion(build=1644, git=ff5727c)
> 
> 19:41:31 [INFO] Attempting to Jenkins download module cmd_send v1644
> 
> 19:41:31 [INFO] Download complete
> 
> 19:41:31 [INFO] Attempting to update plugin from null to ModuleVersion(build=1644, git=ff5727c)
> 
> 19:41:31 [INFO] Attempting to Jenkins download module cmd_server v1644
> 
> 19:41:31 [INFO] Download complete
> 
> 19:41:31 [INFO] Attempting to update plugin from null to ModuleVersion(build=1644, git=ff5727c)
> 
> 19:41:31 [INFO] Attempting to Jenkins download module reconnect_yaml v1644
> 
> 19:41:31 [INFO] Download complete
> 
> 19:41:31 [INFO] Loaded plugin reconnect_yaml version git:reconnect_yaml:1.19-R0.1-SNAPSHOT:ff5727c:1644 by SpigotMC
> 19:41:31 [INFO] Loaded plugin cmd_find version git:cmd_find:1.19-R0.1-SNAPSHOT:ff5727c:1644 by SpigotMC
> 19:41:31 [INFO] Loaded plugin cmd_server version git:cmd_server:1.19-R0.1-SNAPSHOT:ff5727c:1644 by SpigotMC
> 19:41:31 [INFO] Loaded plugin cmd_alert version git:cmd_alert:1.19-R0.1-SNAPSHOT:ff5727c:1644 by SpigotMC
> 19:41:31 [INFO] Loaded plugin cmd_send version git:cmd_send:1.19-R0.1-SNAPSHOT:ff5727c:1644 by SpigotMC
> 19:41:31 [INFO] Loaded plugin cmd_list version git:cmd_list:1.19-R0.1-SNAPSHOT:ff5727c:1644 by SpigotMC
> 19:41:32 [WARNING] Forced host server pvp is not defined
> 19:41:32 [INFO] Enabled plugin reconnect_yaml version git:reconnect_yaml:1.19-R0.1-SNAPSHOT:ff5727c:1644 by SpigotMC
> 19:41:32 [INFO] Enabled plugin cmd_find version git:cmd_find:1.19-R0.1-SNAPSHOT:ff5727c:1644 by SpigotMC
> 19:41:32 [INFO] Enabled plugin cmd_server version git:cmd_server:1.19-R0.1-SNAPSHOT:ff5727c:1644 by SpigotMC
> 19:41:32 [INFO] Enabled plugin cmd_alert version git:cmd_alert:1.19-R0.1-SNAPSHOT:ff5727c:1644 by SpigotMC
> 19:41:32 [INFO] Enabled plugin cmd_send version git:cmd_send:1.19-R0.1-SNAPSHOT:ff5727c:1644 by SpigotMC
> 19:41:32 [INFO] Enabled plugin cmd_list version git:cmd_list:1.19-R0.1-SNAPSHOT:ff5727c:1644 by SpigotMC
> 19:41:32 [INFO] Listening on /0.0.0.0:25577
> 19:45:36 [INFO] Closing listener [id: 0xbe6cf159, L:/[0:0:0:0:0:0:0:0%0]:25577]
> 19:45:36 [INFO] Closing pending connections
> 19:45:36 [INFO] Disconnecting 0 connections
> 19:45:37 [INFO] Saving reconnect locations
> 19:45:37 [INFO] Disabling plugins
> 19:45:37 [INFO] Closing IO threads
> 19:45:40 [INFO] Using mbed TLS based native cipher.
> 19:45:40 [INFO] Using zlib based native compressor.
> 19:45:40 [INFO] Enabled BungeeCord version git:BungeeCord-Bootstrap:1.19-R0.1-SNAPSHOT:ff5727c:1644
> 19:45:40 [INFO] Not on Windows, attempting to use enhanced EpollEventLoop
> 19:45:40 [INFO] Epoll is working, utilising it!
> 19:45:40 [INFO] Discovered module: ModuleSpec(name=cmd_alert, file=modules/cmd_alert.jar, provider=JenkinsModuleSource())
> 
> 19:45:40 [INFO] Discovered module: ModuleSpec(name=cmd_find, file=modules/cmd_find.jar, provider=JenkinsModuleSource())
> 
> 19:45:40 [INFO] Discovered module: ModuleSpec(name=cmd_list, file=modules/cmd_list.jar, provider=JenkinsModuleSource())
> 
> 19:45:40 [INFO] Discovered module: ModuleSpec(name=cmd_send, file=modules/cmd_send.jar, provider=JenkinsModuleSource())
> 
> 19:45:40 [INFO] Discovered module: ModuleSpec(name=cmd_server, file=modules/cmd_server.jar, provider=JenkinsModuleSource())
> 
> 19:45:40 [INFO] Discovered module: ModuleSpec(name=reconnect_yaml, file=modules/reconnect_yaml.jar, provider=JenkinsModuleSource())
> 
> 19:45:41 [INFO] Loaded plugin reconnect_yaml version git:reconnect_yaml:1.19-R0.1-SNAPSHOT:ff5727c:1644 by SpigotMC
> 19:45:41 [INFO] Loaded plugin cmd_find version git:cmd_find:1.19-R0.1-SNAPSHOT:ff5727c:1644 by SpigotMC
> 19:45:41 [INFO] Loaded plugin cmd_server version git:cmd_server:1.19-R0.1-SNAPSHOT:ff5727c:1644 by SpigotMC
> 19:45:41 [INFO] Loaded plugin cmd_alert version git:cmd_alert:1.19-R0.1-SNAPSHOT:ff5727c:1644 by SpigotMC
> 19:45:41 [INFO] Loaded plugin cmd_send version git:cmd_send:1.19-R0.1-SNAPSHOT:ff5727c:1644 by SpigotMC
> 19:45:41 [INFO] Loaded plugin cmd_list version git:cmd_list:1.19-R0.1-SNAPSHOT:ff5727c:1644 by SpigotMC
> 19:45:41 [SEVERE] Exception in thread "main" 
> 19:45:41 [SEVERE] java.lang.RuntimeException: Invalid configuration encountered - this is a configuration error and NOT a bug! Please attempt to fix the error or see https://www.spigotmc.org/ for help.
> 
> 19:45:41 [SEVERE] 	at net.md_5.bungee.conf.YamlConfig.load(YamlConfig.java:73)
> 
> 19:45:41 [SEVERE] 	at net.md_5.bungee.conf.Configuration.load(Configuration.java:75)
> 
> 19:45:41 [SEVERE] 	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:272)
> 
> 19:45:41 [SEVERE] 	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
> 
> 19:45:41 [SEVERE] 	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
> 
> 19:45:41 [SEVERE] Caused by: while parsing a block mapping
>  in 'reader', line 22, column 3:
>       hub:
>       ^
> expected <block end>, but found '<block mapping start>'
>  in 'reader', line 28, column 5:
>         address: 31.214.247.108:31008
>         ^
> 
> 
> 19:45:41 [SEVERE] 	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:644)
> 
> 19:45:41 [SEVERE] 	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:166)
> 
> 19:45:41 [SEVERE] 	at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:59)
> 
> 19:45:41 [SEVERE] 	at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:45)
> 
> 19:45:41 [SEVERE] 	at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:140)
> 
> 19:45:41 [SEVERE] 	at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:119)
> 
> 19:45:41 [SEVERE] 	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:293)
> 
> 19:45:41 [SEVERE] 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:188)
> 
> 19:45:41 [SEVERE] 	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:314)
> 
> 19:45:41 [SEVERE] 	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:305)
> 
> 19:45:41 [SEVERE] 	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:286)
> 
> 19:45:41 [SEVERE] 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:188)
> 
> 19:45:41 [SEVERE] 	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:314)
> 
> 19:45:41 [SEVERE] 	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:305)
> 
> 19:45:41 [SEVERE] 	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:286)
> 
> 19:45:41 [SEVERE] 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:188)
> 
> 19:45:41 [SEVERE] 	at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:115)
> 
> 19:45:41 [SEVERE] 	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:142)
> 
> 19:45:41 [SEVERE] 	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:151)
> 
> 19:45:41 [SEVERE] 	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:491)
> 
> 19:45:41 [SEVERE] 	at org.yaml.snakeyaml.Yaml.load(Yaml.java:429)
> 
> 19:45:41 [SEVERE] 	at net.md_5.bungee.conf.YamlConfig.load(YamlConfig.java:70)
> 
> 19:45:41 [SEVERE] 	... 4 more
> 
> 19:46:52 [INFO] Using mbed TLS based native cipher.
> 19:46:52 [INFO] Using zlib based native compressor.
> 19:46:52 [INFO] Enabled BungeeCord version git:BungeeCord-Bootstrap:1.19-R0.1-SNAPSHOT:ff5727c:1644
> 19:46:52 [INFO] Not on Windows, attempting to use enhanced EpollEventLoop
> 19:46:52 [INFO] Epoll is working, utilising it!
> 19:46:52 [INFO] Discovered module: ModuleSpec(name=cmd_alert, file=modules/cmd_alert.jar, provider=JenkinsModuleSource())
> 
> 19:46:52 [INFO] Discovered module: ModuleSpec(name=cmd_find, file=modules/cmd_find.jar, provider=JenkinsModuleSource())
> 
> 19:46:52 [INFO] Discovered module: ModuleSpec(name=cmd_list, file=modules/cmd_list.jar, provider=JenkinsModuleSource())
> 
> 19:46:52 [INFO] Discovered module: ModuleSpec(name=cmd_send, file=modules/cmd_send.jar, provider=JenkinsModuleSource())
> 
> 19:46:52 [INFO] Discovered module: ModuleSpec(name=cmd_server, file=modules/cmd_server.jar, provider=JenkinsModuleSource())
> 
> 19:46:52 [INFO] Discovered module: ModuleSpec(name=reconnect_yaml, file=modules/reconnect_yaml.jar, provider=JenkinsModuleSource())
> 
> 19:46:53 [INFO] Loaded plugin reconnect_yaml version git:reconnect_yaml:1.19-R0.1-SNAPSHOT:ff5727c:1644 by SpigotMC
> 19:46:53 [INFO] Loaded plugin cmd_find version git:cmd_find:1.19-R0.1-SNAPSHOT:ff5727c:1644 by SpigotMC
> 19:46:53 [INFO] Loaded plugin cmd_server version git:cmd_server:1.19-R0.1-SNAPSHOT:ff5727c:1644 by SpigotMC
> 19:46:53 [INFO] Loaded plugin cmd_alert version git:cmd_alert:1.19-R0.1-SNAPSHOT:ff5727c:1644 by SpigotMC
> 19:46:53 [INFO] Loaded plugin cmd_send version git:cmd_send:1.19-R0.1-SNAPSHOT:ff5727c:1644 by SpigotMC
> 19:46:53 [INFO] Loaded plugin cmd_list version git:cmd_list:1.19-R0.1-SNAPSHOT:ff5727c:1644 by SpigotMC
> 19:46:53 [SEVERE] Exception in thread "main" 
> 19:46:53 [SEVERE] java.lang.RuntimeException: Invalid configuration encountered - this is a configuration error and NOT a bug! Please attempt to fix the error or see https://www.spigotmc.org/ for help.
> 
> 19:46:53 [SEVERE] 	at net.md_5.bungee.conf.YamlConfig.load(YamlConfig.java:73)
> 
> 19:46:53 [SEVERE] 	at net.md_5.bungee.conf.Configuration.load(Configuration.java:75)
> 
> 19:46:53 [SEVERE] 	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:272)
> 
> 19:46:53 [SEVERE] 	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
> 
> 19:46:53 [SEVERE] 	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
> 
> 19:46:53 [SEVERE] Caused by: while parsing a block mapping
>  in 'reader', line 22, column 3:
>       Hub:
>       ^
> expected <block end>, but found '<block mapping start>'
>  in 'reader', line 28, column 5:
>         address: 31.214.247.108:31008
>         ^
> 
> 
> 19:46:53 [SEVERE] 	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:644)
> 
> 19:46:53 [SEVERE] 	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:166)
> 
> 19:46:53 [SEVERE] 	at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:59)
> 
> 19:46:53 [SEVERE] 	at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:45)
> 
> 19:46:53 [SEVERE] 	at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:140)
> 
> 19:46:53 [SEVERE] 	at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:119)
> 
> 19:46:53 [SEVERE] 	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:293)
> 
> 19:46:53 [SEVERE] 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:188)
> 
> 19:46:53 [SEVERE] 	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:314)
> 
> 19:46:53 [SEVERE] 	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:305)
> 
> 19:46:53 [SEVERE] 	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:286)
> 
> 19:46:53 [SEVERE] 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:188)
> 
> 19:46:53 [SEVERE] 	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:314)
> 
> 19:46:53 [SEVERE] 	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:305)
> 
> 19:46:53 [SEVERE] 	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:286)
> 
> 19:46:53 [SEVERE] 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:188)
> 
> 19:46:53 [SEVERE] 	at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:115)
> 
> 19:46:53 [SEVERE] 	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:142)
> 
> 19:46:53 [SEVERE] 	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:151)
> 
> 19:46:53 [SEVERE] 	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:491)
> 
> 19:46:53 [SEVERE] 	at org.yaml.snakeyaml.Yaml.load(Yaml.java:429)
> 
> 19:46:53 [SEVERE] 	at net.md_5.bungee.conf.YamlConfig.load(YamlConfig.java:70)
> 
> 19:46:53 [SEVERE] 	... 4 more
> 
> 19:51:45 [INFO] Using mbed TLS based native cipher.
> 19:51:45 [INFO] Using zlib based native compressor.
> 19:51:45 [INFO] Enabled BungeeCord version git:BungeeCord-Bootstrap:1.19-R0.1-SNAPSHOT:ff5727c:1644
> 19:51:45 [INFO] Not on Windows, attempting to use enhanced EpollEventLoop
> 19:51:45 [INFO] Epoll is working, utilising it!
> 19:51:45 [INFO] Discovered module: ModuleSpec(name=cmd_alert, file=modules/cmd_alert.jar, provider=JenkinsModuleSource())
> 
> 19:51:45 [INFO] Discovered module: ModuleSpec(name=cmd_find, file=modules/cmd_find.jar, provider=JenkinsModuleSource())
> 
> 19:51:45 [INFO] Discovered module: ModuleSpec(name=cmd_list, file=modules/cmd_list.jar, provider=JenkinsModuleSource())
> 
> 19:51:45 [INFO] Discovered module: ModuleSpec(name=cmd_send, file=modules/cmd_send.jar, provider=JenkinsModuleSource())
> 
> 19:51:45 [INFO] Discovered module: ModuleSpec(name=cmd_server, file=modules/cmd_server.jar, provider=JenkinsModuleSource())
> 
> 19:51:45 [INFO] Discovered module: ModuleSpec(name=reconnect_yaml, file=modules/reconnect_yaml.jar, provider=JenkinsModuleSource())
> 
> 19:51:46 [INFO] Loaded plugin reconnect_yaml version git:reconnect_yaml:1.19-R0.1-SNAPSHOT:ff5727c:1644 by SpigotMC
> 19:51:46 [INFO] Loaded plugin cmd_find version git:cmd_find:1.19-R0.1-SNAPSHOT:ff5727c:1644 by SpigotMC
> 19:51:46 [INFO] Loaded plugin cmd_server version git:cmd_server:1.19-R0.1-SNAPSHOT:ff5727c:1644 by SpigotMC
> 19:51:46 [INFO] Loaded plugin cmd_alert version git:cmd_alert:1.19-R0.1-SNAPSHOT:ff5727c:1644 by SpigotMC
> 19:51:46 [INFO] Loaded plugin cmd_send version git:cmd_send:1.19-R0.1-SNAPSHOT:ff5727c:1644 by SpigotMC
> 19:51:46 [INFO] Loaded plugin cmd_list version git:cmd_list:1.19-R0.1-SNAPSHOT:ff5727c:1644 by SpigotMC
> 19:51:46 [SEVERE] Exception in thread "main" 
> 19:51:46 [SEVERE] java.lang.RuntimeException: Invalid configuration encountered - this is a configuration error and NOT a bug! Please attempt to fix the error or see https://www.spigotmc.org/ for help.
> 
> 19:51:46 [SEVERE] 	at net.md_5.bungee.conf.YamlConfig.load(YamlConfig.java:73)
> 
> 19:51:46 [SEVERE] 	at net.md_5.bungee.conf.Configuration.load(Configuration.java:75)
> 
> 19:51:46 [SEVERE] 	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:272)
> 
> 19:51:46 [SEVERE] 	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
> 
> 19:51:46 [SEVERE] 	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
> 
> 19:51:46 [SEVERE] Caused by: while parsing a block mapping
>  in 'reader', line 22, column 3:
>       Hub:
>       ^
> expected <block end>, but found '<block mapping start>'
>  in 'reader', line 28, column 5:
>         address: 31.214.247.108:31008
>         ^
> 
> 
> 19:51:46 [SEVERE] 	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:644)
> 
> 19:51:46 [SEVERE] 	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:166)
> 
> 19:51:46 [SEVERE] 	at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:59)
> 
> 19:51:46 [SEVERE] 	at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:45)
> 
> 19:51:46 [SEVERE] 	at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:140)
> 
> 19:51:46 [SEVERE] 	at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:119)
> 
> 19:51:46 [SEVERE] 	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:293)
> 
> 19:51:46 [SEVERE] 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:188)
> 
> 19:51:46 [SEVERE] 	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:314)
> 
> 19:51:46 [SEVERE] 	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:305)
> 
> 19:51:46 [SEVERE] 	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:286)
> 
> 19:51:46 [SEVERE] 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:188)
> 
> 19:51:46 [SEVERE] 	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:314)
> 
> 19:51:46 [SEVERE] 	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:305)
> 
> 19:51:46 [SEVERE] 	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:286)
> 
> 19:51:46 [SEVERE] 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:188)
> 
> 19:51:46 [SEVERE] 	at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:115)
> 
> 19:51:46 [SEVERE] 	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:142)
> 
> 19:51:46 [SEVERE] 	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:151)
> 
> 19:51:46 [SEVERE] 	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:491)
> 
> 19:51:46 [SEVERE] 	at org.yaml.snakeyaml.Yaml.load(Yaml.java:429)
> 
> 19:51:46 [SEVERE] 	at net.md_5.bungee.conf.YamlConfig.load(YamlConfig.java:70)
> 
> 19:51:46 [SEVERE] 	... 4 more
> 
>

**Comment by Janmm14** [comment]
Your configuration is not formatted correctly.

**Comment by MosesCuhhh** [comment]
Yep got the same issue, only happened when i added my second server, with 1 server it ran fine. How can i fix it?

**Comment by Janmm14** [comment]
> Yep got the same issue, only happened when i added my second server, with 1 server it ran fine. How can i fix it?

For further help which are sort of "user faults" please consult https://www.spigotmc.org forums, as the issue says.
There you should provide your configuration in a [code][/code] block so it is shown with the indentation you used.

**Comment by Radi0o** [comment]
its the java version i think

**Comment by Janmm14** [comment]
> its the java version i think

wrong
