### ISSUE TITLE
Error happened when a player was trying to join a 1.19 vanilla server via BungeeCord

### ISSUE THREAD

**Issue by MiKayule** [SpigotMC/BungeeCord#3338]
I can use a 1.19 vanilla client to join a server older than 1.19 with ViaVersion plugin, but can't join 1.19 vanilla servers, with the error information below:

`02:32:57 [SEVERE] [MiKayule] -> UpstreamBridge - encountered exception
io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Cannot get ID for packet class net.md_5.bungee.protocol.packet.SystemChat in phase GAME with direction TO_CLIENT
    at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
    at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
    at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
    at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
    at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
    at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020)
    at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311)
    at net.md_5.bungee.netty.ChannelWrapper.write(ChannelWrapper.java:60)
    at net.md_5.bungee.UserConnection$1.sendPacket(UserConnection.java:146)
    at net.md_5.bungee.UserConnection.sendMessage(UserConnection.java:488)
    at net.md_5.bungee.UserConnection.sendMessage(UserConnection.java:516)
    at net.md_5.bungee.UserConnection.sendMessage(UserConnection.java:457)
    at net.md_5.bungee.UserConnection.sendMessage(UserConnection.java:445)
    at net.md_5.bungee.UserConnection.sendMessage(UserConnection.java:430)
    at net.md_5.bungee.ServerConnector.handle(ServerConnector.java:367)
    at net.md_5.bungee.protocol.packet.Kick.handle(Kick.java:35)
    at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:114)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
    at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalArgumentException: Cannot get ID for packet class net.md_5.bungee.protocol.packet.SystemChat in phase GAME with direction TO_CLIENT
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:453)
    at net.md_5.bungee.protocol.Protocol$DirectionData.getId(Protocol.java:628)
    at net.md_5.bungee.protocol.MinecraftEncoder.encode(MinecraftEncoder.java:23)
    at net.md_5.bungee.protocol.MinecraftEncoder.encode(MinecraftEncoder.java:9)
    at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
    ... 42 more`
`02:32:57 [INFO] [MiKayule] disconnected with: EncoderException : java.lang.IllegalArgumentException: Cannot get ID for packet class net.md_5.bungee.protocol.packet.SystemChat in phase GAME with direction TO_CLIENT @ io.netty.handler.codec.MessageToByteEncoder:125`

Error would happen even if I remove all the plugins. After the error occurred, the client will be kicked immediately.

**Comment by MiKayule** [comment]
I also tried to join a 1.19 server with 1.18.2 and 1.15.2 vanilla client with ViaBackwards 4.3.0 plugin, that didn't work as well.

**Comment by Janmm14** [comment]
It seems like this error occurred after the vanilla server kicked you.

**Comment by MiKayule** [comment]
Problem resloved:
1. I used `1.19-rc2` server instead of `1.19` by mistake;
2. `enforce-secure-profile` and `online-mode` must be false in the `server.properties` of the vanilla server.
I'm sorry to bother you because of my mistakes.

**Comment by MiKayule** [comment]
> It seems like this error occurred after the vanilla server kicked you.
> 
> I'd say it lloks like a valid issue (didnt test myelf tho), but could you look into the vanlla server's log what it wrote?

Actually, there's exactly nothing in the vanilla server's log, maybe the vanilla server hadn't received any valid package during the whole process, and that's one of the reasons I tested it for hours but found nothing until now...
