### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by Molsy231** [SpigotMC/BungeeCord#3341]
Hello, I am Molsy, I am trying to create a Bungee cord server but the console always ends up with the [SEVERE] type things. It says [SEVERE] Exception in thread "main". I dont know how to fix this and I really need help. I am trying to run this server on my desktop and also tried looking on the internet to find an answer but can never find one. I really need help to fix this so i can run my server. The config for the server is perfectly fine i checked and its ok. But the last errors ([Severe]'s) are really making me mad. Please help me out, Molsy.

Log: 18:10:06 [SEVERE] Exception in thread "main"
18:10:06 [SEVERE] java.lang.reflect.InaccessibleObjectException: Unable to make private native java.lang.reflect.Field[] java.lang.Class.getDeclaredFields0(boolean) accessible: module java.base does not "opens java.lang" to unnamed module @3d8314f0

18:10:06 [SEVERE]     at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)

18:10:06 [SEVERE]     at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)

18:10:06 [SEVERE]     at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)

18:10:06 [SEVERE]     at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)

18:10:06 [SEVERE]     at ru.leymooo.botfilter.config.Config.setAccessible(Config.java:371)

18:10:06 [SEVERE]     at ru.leymooo.botfilter.config.Config.getField(Config.java:258)

18:10:06 [SEVERE]     at ru.leymooo.botfilter.config.Config.set(Config.java:54)

18:10:06 [SEVERE]     at ru.leymooo.botfilter.config.Config.set(Config.java:114)

18:10:06 [SEVERE]     at ru.leymooo.botfilter.config.Config.load(Config.java:99)

18:10:06 [SEVERE]     at ru.leymooo.botfilter.config.Settings.reload(Settings.java:60)

18:10:06 [SEVERE]     at ru.leymooo.botfilter.BotFilter.<init>(BotFilter.java:74)

18:10:06 [SEVERE]     at net.md_5.bungee.BungeeCord.start(BungeeCord.java:282)

18:10:06 [SEVERE]     at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:49)

18:10:06 [SEVERE]     at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

**Comment by Janmm14** [comment]
This is a plugin issue. Plugin isuses do not belong here. Use [spigotmc.org](https://www.spigotmc.org) forum "Bungeecord Plugin Help".

**Comment by Molsy231** [comment]
They helped me but now I have another problem:
18:37:49 [SEVERE] Exception in thread "main"
18:37:49 [SEVERE] java.lang.IllegalArgumentException: Server lobby-1 (priority 0) is not defined

18:37:49 [SEVERE]     at com.google.common.base.Preconditions.checkArgument(Preconditions.java:359)

18:37:49 [SEVERE]     at net.md_5.bungee.conf.Configuration.load(Configuration.java:117)

18:37:49 [SEVERE]     at net.md_5.bungee.BungeeCord.start(BungeeCord.java:298)

18:37:49 [SEVERE]     at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:49)

18:37:49 [SEVERE]     at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

**Comment by Janmm14** [comment]
Bungeecord configuration issues also belong into the [spigotmc.org](https://www.spigotmc.org) forums!
