### ISSUE TITLE
ConcurrentModificationException : null @ java.util.HashMap$HashIterator:1597

### ISSUE THREAD

**Issue by DasKabel** [SpigotMC/BungeeCord#3408]
### Bungeecord version

git:BungeeCord-Bootstrap:1.19-R0.1-SNAPSHOT:5467e3a:1671

### Server version

Vanilla

### Client version

1.19.3

### Bungeecord plugins

SkinsRestorer

### The bug

When multiple players are connected to the Bungeecord server and one of them leaves the Server the rest of all the other players gets disconnected with the Message: ConcurrentModificationException : null @ java.util.HashMap$HashIterator:1597

After update from 1.19.2 including all config files

### Log output (links)

```
18:15:44 [INFO] [darki_dragon] <-> ServerConnector [lobby] has connected
18:44:21 [INFO] [Das_Kabel] -> UpstreamBridge has disconnected
18:44:21 [INFO] [Das_Kabel] <-> DownstreamBridge <-> [lobby] has disconnected
18:44:21 [SEVERE] [darki_dragon] <-> DownstreamBridge <-> [lobby] - encountered exception
java.util.ConcurrentModificationException
        at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1597)
        at java.base/java.util.HashMap$KeyIterator.next(HashMap.java:1620)
        at net.md_5.bungee.tab.ServerUnique.onUpdate(ServerUnique.java:41)
        at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:161)
        at net.md_5.bungee.protocol.packet.PlayerListItemRemove.handle(PlayerListItemRemove.java:43)
        at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:114)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.base/java.lang.Thread.run(Thread.java:833)
18:44:21 [INFO] [darki_dragon] disconnected with: §fConcurrentModificationException : null @ java.util.HashMap$HashIterator:1597
18:44:21 [INFO] [darki_dragon] -> UpstreamBridge has disconnected
18:44:21 [INFO] [darki_dragon] <-> DownstreamBridge <-> [lobby] has disconnected
18:44:21 [INFO] [/91.1.234.244:56050] <-> InitialHandler has pinged
18:44:28 [INFO] [darki_dragon,/178.24.232.165:10461] <-> InitialHandler has connected
18:44:28 [INFO] [Das_Kabel,/91.1.234.244:56057] <-> InitialHandler has connected
18:44:28 [INFO] [Das_Kabel] <-> ServerConnector [lobby] has connected
18:44:29 [INFO] [darki_dragon] <-> ServerConnector [lobby] has connected
18:44:42 [INFO] [Das_Kabel] -> UpstreamBridge has disconnected
18:44:42 [INFO] [Das_Kabel] <-> DownstreamBridge <-> [lobby] has disconnected
```

### Checking

- [X] I am using BungeeCord and **not a fork**. Issues with forks should not be reported here.
- [X] I think this is **not** an issue with a bungeecord plugin.
- [ ] I have not read these checkboxes and therefore I just ticked them all.
- [X] This is not a question or plugin creation help request.

**Comment by md-5** [comment]
And without skins restorer?
Tab packets changed and this plugin breaks the api

**Comment by md-5** [comment]
Fix pushed, though please note skinsrestorer is not supported and relevant packets did change this release
