### ISSUE TITLE
Error when someone connecting

### ISSUE THREAD

**Issue by SnoxikMox** [SpigotMC/BungeeCord#3442]
### Bungeecord version

git:BungeeCord-Bootstrap:1.19-R0.1-SNAPSHOT:1b6d845:1679

### Server version

git-Dionysus-"42ce9ca" (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

### Client version

1.8.8

### Bungeecord plugins

BungeeTabListPlus-3.6.0.jar
mineLogin-1.5.4-bungeecord-public.jar (i removed it and the error persisted)

### The bug

When someone connecting to the server i have this error in console and that person cant ping server and connect to it

18:12:07 [SEVERE] Error authenticating _Shifu with minecraft.net
io.netty.channel.ConnectTimeoutException: connection timed out: sessionserver.mojang.com/13.107.237.45:443
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$2.run(AbstractEpollChannel.java:613)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:406)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:833)

### Checking

- [X] I am using BungeeCord and **not a fork**. Issues with forks should not be reported here.
- [X] I think this is **not** an issue with a bungeecord plugin.
- [ ] I have not read these checkboxes and therefore I just ticked them all.
- [X] This is not a question or plugin creation help request.

**Comment by Outfluencer** [comment]
Session servers are unavailable, maybe problem of the firewall or the server was down while due to maintenance or something

**Comment by SnoxikMox** [comment]
i think it's not a firewall issue because if i refresh the list a few times it works but when i refresh again it doesn't work

**Comment by SnoxikMox** [comment]
> Session servers are unavailable, maybe problem of the firewall or the server was down due to maintenance or something

i think it's not a firewall issue because if i refresh the list a few times it works but when i refresh again it doesn't work
