### ISSUE TITLE
"could not decode packet" when OP'd player joins 1.19.4 proxy (1.18.2 client/server)

### ISSUE THREAD

**Issue by Dakotaa** [SpigotMC/BungeeCord#3446]
### Bungeecord version

1683

### Server version

Purpur-1632 (1.18.2)

### Client version

1.18.2

### Bungeecord plugins

None

### The bug

Upon updating to 1.19.4 bungee, any OP player who joins the server can not connect. A "could not decode packet" error is spammed in the console until they cancel the connection. ONLY affects players with OP. Regular players can connect fine.

### Log output (links)

```
01:07:47 [INFO] [Dakotaa] <-> ServerConnector [factions] has connected
01:07:47 [WARNING] [Dakotaa] <-> DownstreamBridge <-> [factions] - could not decode packet! java.lang.IllegalArgumentException: No provider for argument server�targetminecraft:resource_locationminecraft:ask_server�	targetPosminecraft:bloc
01:07:47 [INFO] [Dakotaa] <-> DownstreamBridge <-> [factions] has disconnected
01:07:47 [INFO] [Dakotaa] <-> ServerConnector [spawn] has connected
01:07:47 [WARNING] [Dakotaa] <-> DownstreamBridge <-> [spawn] - could not decode packet! java.lang.IllegalArgumentException: No provider for argument �%targetsminecr
01:07:47 [INFO] [Dakotaa] <-> DownstreamBridge <-> [spawn] has disconnected
```

error continues repeatedly while player is "connected". (on Waterfall it kicks the player after the first error)

### Checking

- [X] I am using BungeeCord and **not a fork**. Issues with forks should not be reported here.
- [X] I think this is **not** an issue with a bungeecord plugin.
- [ ] I have not read these checkboxes and therefore I just ticked them all.
- [X] This is not a question or plugin creation help request.

**Comment by md-5** [comment]
Thanks, this should now be fixed

**Comment by ImLvna** [comment]
This seems to still be happening on the latest build, although the logs are less descriptive:
`[WARNING] [Username] <-> DownstreamBridge <-> [Servername] - could not decode packet! java.lang.ArrayIndexOutOfBoundsException: Index 51 out of bounds for length 49`

**Comment by justorl** [comment]
also still be happening

**Comment by Guarmanda** [comment]
still happening

**Comment by Guarmanda** [comment]
01:19:53 [WARNING] [/147.45.112.177:65110] <-> InitialHandler - could not decode packet!
io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: index: 3, length: 47 (expected: range(0, 3))
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333)
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:455)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
    at io.netty.handler.codec.ByteToMessageDecoder.handlerRemoved(ByteToMessageDecoder.java:266)
    at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:537)
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:469)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1407)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:918)
    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:799)
    at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:501)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:399)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.IndexOutOfBoundsException: index: 3, length: 47 (expected: range(0, 3))
    at io.netty.buffer.AbstractByteBuf.checkRangeBounds(AbstractByteBuf.java:1390)
    at io.netty.buffer.AbstractByteBuf.checkIndex0(AbstractByteBuf.java:1397)
    at io.netty.buffer.PooledSlicedByteBuf.getBytes(PooledSlicedByteBuf.java:234)
    at io.netty.buffer.ByteBufUtil.decodeString(ByteBufUtil.java:1360)
    at io.netty.buffer.AbstractByteBuf.toString(AbstractByteBuf.java:1246)
    at net.md_5.bungee.protocol.DefinedPacket.readString(DefinedPacket.java:85)
    at net.md_5.bungee.protocol.packet.Handshake.read(Handshake.java:27)
    at net.md_5.bungee.protocol.DefinedPacket.read(DefinedPacket.java:529)
    at net.md_5.bungee.protocol.DefinedPacket.read(DefinedPacket.java:524)
    at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:42)
    at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:11)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
    ... 27 more
