### ISSUE TITLE
Hostname/IP validation is too strict

### ISSUE THREAD

**Issue by RaphiMC** [SpigotMC/BungeeCord#3480]
### Bungeecord version

git:BungeeCord-Bootstrap:1.20-R0.1-SNAPSHOT:c7adcf9:1716

### Bungeecord plugins

none

### The bug

If I want to use `raphimc.net_25564_1.8.x.viaproxy.127-0-0-1.nip.io:25568` as a hostname for my backend server in the bungeecord config it complains that the address is not valid. Pinging `raphimc.net_25564_1.8.x.viaproxy.127-0-0-1.nip.io` in cmd resolves to localhost as it should. The reason I want to use such a long hostname is to pass on information (Through the address in the handshake packet) to the "backend server" (Another proxy) to know where to connect to. Trying to connect to that address with a minecraft client works fine.

### Log output (links)

```
09:11:32 [SCHWERWIEGEND] Exception in thread "main"
09:11:32 [SCHWERWIEGEND] java.lang.IllegalArgumentException: Invalid host/address: raphimc.net_25564_1.8.x.viaproxy.127-0-0-1.nip.io:25568
09:11:32 [SCHWERWIEGEND]     at net.md_5.bungee.Util.getAddr(Util.java:55)
09:11:32 [SCHWERWIEGEND]     at net.md_5.bungee.conf.YamlConfig.getServers(YamlConfig.java:221)
09:11:32 [SCHWERWIEGEND]     at net.md_5.bungee.conf.Configuration.load(Configuration.java:111)
09:11:32 [SCHWERWIEGEND]     at net.md_5.bungee.BungeeCord.start(BungeeCord.java:282)
09:11:32 [SCHWERWIEGEND]     at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
09:11:32 [SCHWERWIEGEND]     at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
```

### Checking

- [X] I am using BungeeCord and **not a fork**. Issues with forks should not be reported here.
- [X] I think this is **not** an issue with a bungeecord plugin.
- [ ] I have not read these checkboxes and therefore I just ticked them all.
- [X] This is not a question or plugin creation help request.

**Comment by RaphiMC** [comment]
Velocity has the same issue: https://github.com/PaperMC/Velocity/issues/1031
