### ISSUE TITLE
Cannot get ID for packet class net.md_5.bungee.protocol.packet.PlayerListItem

### ISSUE THREAD

**Issue by FreeSoccerHDX** [SpigotMC/BungeeCord#3517]
### Bungeecord version

git:BungeeCord-Bootstrap:1.20-R0.2-SNAPSHOT:cfe00fa:1734 by md_5

### Client version

1.20.1

### Bungeecord plugins

BungeeWhiteList
(and my own plugin that does not much and nothing with packets so far at all)

### The bug

Sending a PlayerListItem-Packet results in a Kick for the Player.
```
ProxiedPlayer pp = ...
PlayerListItem playerListItem = new PlayerListItem();
playerListItem.setAction(PlayerListItem.Action.ADD_PLAYER);
PlayerListItem.Item item = new PlayerListItem.Item();
item.setUuid(UUID.randomUUID());
item.setUsername("§bUs_"+pp.getName());
item.setDisplayName("§eDis_"+pp.getDisplayName());
item.setPing(10000);

pp.unsafe().sendPacket(playerListItem);
```

### Log output (links)

io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Cannot get ID for packet class net.md_5.bungee.protocol.packet.PlayerListItem in phase GAME with direction TO_CLIENT
    at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
    at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
    at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940)
    at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1247)
    at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalArgumentException: Cannot get ID for packet class net.md_5.bungee.protocol.packet.PlayerListItem in phase GAME with direction TO_CLIENT
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:463)
    at net.md_5.bungee.protocol.Protocol$DirectionData.getId(Protocol.java:813)
    at net.md_5.bungee.protocol.MinecraftEncoder.encode(MinecraftEncoder.java:25)
    at net.md_5.bungee.protocol.MinecraftEncoder.encode(MinecraftEncoder.java:10)
    at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)

### Checking

- [X] I am using BungeeCord and **not a fork**. Issues with forks should not be reported here.
- [X] I think this is **not** an issue with a bungeecord plugin.
- [ ] I have not read these checkboxes and therefore I just ticked them all.
- [X] This is not a question or plugin creation help request.

**Comment by md-5** [comment]
This packet is not used in 1.20.1, there is a different packet. Please refer to the list of packets in Protocol.java
