### ISSUE TITLE
Bungee kicking players

### ISSUE THREAD

**Issue by SpearDevelopment1** [SpigotMC/BungeeCord#3520]
### Bungeecord version

BungeeCord-Bootstrap:1.20-R0.2-SNAPSHOT:f486a25:173

### Server version

Paper version git-Paper-1620 (MC: 1.12.2)

### Client version

1.12.2

### Bungeecord plugins

pxBungee

### The bug

When my skyblock server reaches 20 players it starts kicking them, only happens with bungeecord. I get the error listed below. does not happen in lobby server, have tried with spigot instead of paper same result.

### Log output (links)

```java.lang.NullPointerException: Cannot invoke "net.md_5.bungee.protocol.MinecraftEncoder.getProtocol()" because the return value of "io.netty.channel.ChannelPipeline.get(java.lang.Class)" is null
    at net.md_5.bungee.netty.ChannelWrapper.getEncodeProtocol(ChannelWrapper.java:51)
    at net.md_5.bungee.connection.UpstreamBridge.handle(UpstreamBridge.java:139)
    at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:132)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
    at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
    at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at java.base/java.lang.Thread.run(Thread.java:833)```

### Checking

- [X] I am using BungeeCord and **not a fork**. Issues with forks should not be reported here.
- [X] I think this is **not** an issue with a bungeecord plugin.
- [X] I have not read these checkboxes and therefore I just ticked them all.
- [X] This is not a question or plugin creation help request.

**Comment by Janmm14** [comment]
Log output incomplete.
\`\`\` needs to be on a newline at the end of the code block as well.
Unable to read checkboxes.

**Comment by md-5** [comment]
What is pxBungee?

Try without plugins. I fail to see how this can ever be null.

**Comment by SpearDevelopment1** [comment]
pxBungee is a core system provided refine development it does /hub, bungeeperms etc

**Comment by SpearDevelopment1** [comment]
> What is pxBungee?
> 
> Try without plugins. I fail to see how this can ever be null.

Tried without pxBungee still happening.

**Comment by bob7l** [comment]
Can't reproduce. Did you try with absolutely no plugins? With that wording it sounds like you only removed pxBungee

**Comment by neziw** [comment]
Just paste full log

**Comment by bob7l** [comment]
This error seems to be subsequent to another error from what I've seen. Scroll higher up and find the first error that pops up (Likely a "Cannot get ID for packet class" error)

**Comment by SpearDevelopment1** [comment]
Not getting any error now but its still kicking.

**Comment by SpearDevelopment1** [comment]
full log: https://paste.learnspigot.com/uwexacejid.less

**Comment by bob7l** [comment]
> full log: https://paste.learnspigot.com/uwexacejid.less

You're using Waterfall, and ViaRewind ViaBackwards and ViaVersion are outdated.

**Comment by SpearDevelopment1** [comment]
Must be outdated then give me a minute.

**Comment by SpearDevelopment1** [comment]
It's not saving logs anymore. I checked the proxy.log files and the logs folder. the one i sent is outdated because  it hasn't overridden it.

**Comment by SpearDevelopment1** [comment]
Its still kicking them but without errors.
