### ISSUE TITLE
Cannot get ID for packet class net.md_5.bungee.protocol.packet.LoginSuccess

### ISSUE THREAD

**Issue by BboyZeroOne** [SpigotMC/BungeeCord#3552]
### Bungeecord version

git:BungeeCord-Bootstrap:1.20-R0.2-SNAPSHOT:a7dbbc2:1756 by md_5

### Server version

git-Paper-196 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 773dd72)

### Client version

1.20.1

### Bungeecord plugins

BungeeCord Version:1756

### The bug

Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: Cannot get ID for packet class net.md_5.bungee.protocol.packet.LoginSuccess in phase GAME with direction TO CLIENT @ io.netty.handler.codec.MessageToByteEncoder:125

### Checking

- [X] I am using BungeeCord and **not a fork**. Issues with forks should not be reported here.
- [X] I think this is **not** an issue with a bungeecord plugin.
- [ ] I have not read these checkboxes and therefore I just ticked them all.
- [X] This is not a question or plugin creation help request.

**Comment by MynamisTG** [comment]
Same problem - java.lang.IllegalStateException: Not expecting login
    at com.google.common.base.Preconditions.checkState(Preconditions.java:512)
    at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:766)
    at net.md_5.bungee.protocol.packet.Login.handle(Login.java:283)
    at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:124)

**Comment by xism4** [comment]
> Same problem - java.lang.IllegalStateException: Not expecting login
> at com.google.common.base.Preconditions.checkState(Preconditions.java:512)
> at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:766)
> at net.md_5.bungee.protocol.packet.Login.handle(Login.java:283)
> at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:124)

Are you using ViaVersion?

**Comment by Janmm14** [comment]
> @MynamisTG wrote:
> Same problem - java.lang.IllegalStateException: Not expecting login at com.google.common.base.Preconditions.checkState(Preconditions.java:512) at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:766) at net.md_5.bungee.protocol.packet.Login.handle(Login.java:283) at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:124)

Not the same issue at all!

**Comment by Sckaletz** [comment]
We have the same issue.

https://paste.gg/p/anonymous/a5ef4957a56b4fffbc075fd27e8cf1c1

When connecting to the server without Bungeecord, it connects fine. But through Bungeecord the player can't connect and is kicked.

The server is a PaperSpigot 1.8.8 with [ViaVersion-4.9.3-SNAPSHOT.jar](https://ci.viaversion.com/job/ViaVersion/750/artifact/build/libs/ViaVersion-4.9.3-SNAPSHOT.jar)

Bungeecord build #1777.

**Comment by xiaoyao778** [comment]
EncoderException : java.lang.IllegalArgumentException: Cannot get ID for packet class net.md_5.bungee.protocol.packet.LoginSuccess in phase GAME with direction TO_CLIENT @ io.netty.handler.codec.MessageToByteEncoder:125

**Comment by xiaoyao778** [comment]
同样的问题，我不知道应该怎么解决，版本1.20.2

**Comment by Anath4n** [comment]
> > EncoderException : java.lang.IllegalArgumentException: Cannot get ID for packet class net.md_5.bungee.protocol.packet.LoginSuccess in phase GAME with direction TO_CLIENT @ io.netty.handler.codec.MessageToByteEncoder:125
> 
> if you have viaversion, use it only in the backend servers and not in the bungeecord server

does this work??
