### ISSUE TITLE
Players kicked when partial command executed after #3584

### ISSUE THREAD

**Issue by brickmonster** [SpigotMC/BungeeCord#3585]
### Bungeecord version

f5af111:1784

### Server version

3981-Spigot-053fa2a-5876cca (MC: 1.20.4)

### Client version

1.20.4

### Bungeecord plugins

None

### The bug

Only happens after #3584 was fixed.
BungeeCord and Spigot (built with buildtools --rev 1.20.4) servers both have no plugins.

When a player runs `/me` with no arguments, an exception is logged and they get kicked with the exception's message.

This also happens with `/data` and `/summon`, which probably means it happens on any brigadier node that doesn't have a `.executes` callback.

### Log output (links)

```
java.lang.Error: Cannot write an error tag to NBT stream (No item named "" in this compound tag.)
    at se.llbit.nbt.ErrorTag.tagType(ErrorTag.java:61)
    at net.md_5.bungee.protocol.TagUtil.toJson(TagUtil.java:152)
    at net.md_5.bungee.protocol.TagUtil.toJson(TagUtil.java:192)
    at net.md_5.bungee.protocol.TagUtil.toJson(TagUtil.java:206)
    at net.md_5.bungee.protocol.DefinedPacket.readBaseComponent(DefinedPacket.java:110)
    at net.md_5.bungee.protocol.packet.SystemChat.read(SystemChat.java:27)
    at net.md_5.bungee.protocol.DefinedPacket.read(DefinedPacket.java:507)
    at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:42)
    at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:11)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
    at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at java.base/java.lang.Thread.run(Thread.java:1583)
```

### Checking

- [X] I am using BungeeCord and **not a fork**. Issues with forks should not be reported here.
- [X] I think this is **not** an issue with a bungeecord plugin.
- [ ] I have not read these checkboxes and therefore I just ticked them all.
- [X] This is not a question or plugin creation help request.

**Comment by brickmonster** [comment]
Reproduced in vanilla when running any command that doesn't exist.
