### ISSUE TITLE
BungeeCord segfaults on Alpine

### ISSUE THREAD

**Issue by killme** [SpigotMC/BungeeCord#3707]
### Bungeecord version

git:BungeeCord-Bootstrap:1.20-R0.3-SNAPSHOT:412dbbf:unknown

### Client version

1.20.6

### Bungeecord plugins

None

### The bug

- When running the proxy in an Alpine Docker container, the server crashes when connecting with an unsupported client. This works fine inside of an Ubuntu docker container.
- Similarly, the `net.md_5.bungee.NativeCipherTest` unit test crashes when built/running on Alpine, and this works fine on Ubuntu

Could this be a musl/glibc incompatibility issue?

### Log output (links)

```
12:45:42 [INFO] [/192.168.2.2:36918] <-> InitialHandler has connected
12:45:43 [INFO] [Username] <-> ServerConnector [lobby] has connected
12:45:43 [INFO] [Username] disconnected with: Kicked whilst connecting to lobby: Unsupported protocol version 766
>#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00000000000021d0, pid=169, tid=208
#
# JRE version: OpenJDK Runtime Environment (21.0.3+9) (build 21.0.3+9-alpine-r0)
# Java VM: OpenJDK 64-Bit Server VM (21.0.3+9-alpine-r0, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  [bungeecord-native-cipher5548898582649455736.so+0x5660]  mbedtls_platform_zeroize+0x20
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to /mnt/core.169)
#
# An error report file with more information is saved as:
# /mnt/hs_err_pid169.log
12:45:43 [INFO] [Username] -> UpstreamBridge has disconnected
>#
# If you would like to submit a bug report, please visit:
#   https://gitlab.alpinelinux.org/alpine/aports/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
Aborted (core dumped)
```

**Crash dump:** https://gist.github.com/killme/c7c7cd9759ecc52655bd29522f5feddc

---

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.2.2:test (default-test) on project bungeecord-native: 
[ERROR] 
[ERROR] Please refer to /mnt/native/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd '/mnt/native' && '/usr/lib/jvm/java-21-openjdk/bin/java' '-jar' '/mnt/native/target/surefire/surefirebooter-20240714125321234_3.jar' '/mnt/native/target/surefire' '2024-07-14T12-53-21_104-jvmRun1' 'surefire-20240714125321234_1tmp' 'surefire_0-20240714125321234_2tmp'
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 134
[ERROR] Crashed tests:
[ERROR] net.md_5.bungee.NativeCipherTest
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd '/mnt/native' && '/usr/lib/jvm/java-21-openjdk/bin/java' '-jar' '/mnt/native/target/surefire/surefirebooter-20240714125321234_3.jar' '/mnt/native/target/surefire' '2024-07-14T12-53-21_104-jvmRun1' 'surefire-20240714125321234_1tmp' 'surefire_0-20240714125321234_2tmp'
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 134
[ERROR] Crashed tests:
[ERROR] net.md_5.bungee.NativeCipherTest
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:643)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:285)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:250)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1240)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1089)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:905)
[ERROR] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:126)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:328)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:316)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:174)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.access$000(MojoExecutor.java:75)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor$1.run(MojoExecutor.java:162)
[ERROR] 	at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute(DefaultMojosExecutionStrategy.java:39)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:159)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:105)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:73)
[ERROR] 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:53)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:118)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:261)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:173)
[ERROR] 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:101)
[ERROR] 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:906)
[ERROR] 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:283)
[ERROR] 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:206)
[ERROR] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:283)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:226)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:407)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:348)
```

[hs_err_pid655.log](https://github.com/user-attachments/files/16227318/hs_err_pid655.log)

---

Container used for testing:
```
FROM alpine

RUN apk update && apk add openjdk21-jdk maven
```

### Checking

- [X] I am using BungeeCord and **not a fork**. Issues with forks should not be reported here.
- [X] I think this is **not** an issue with a bungeecord plugin.
- [ ] I have not read these checkboxes and therefore I just ticked them all.
- [X] This is not a question or plugin creation help request.

**Comment by md-5** [comment]
> git:BungeeCord-Bootstrap:1.20-R0.3-SNAPSHOT:412dbbf:unknown

This appears to be some sort of custom version.

Please try the 1851 and 1852 https://ci.md-5.net/job/BungeeCord/

**Comment by Rigner** [comment]
Hey @md-5, I can reproduce this on the latest BungeeCord build from the CI.

`Enabled BungeeCord version git:BungeeCord-Bootstrap:1.21-R0.1-SNAPSHOT:b64615e:1855`

https://gist.github.com/Rigner/1bdae4b8e18e7644779f3c42cb51a4d1

**Comment by md-5** [comment]
cc \ @lax1dude

**Comment by lax1dude** [comment]
@md-5 Alright I'll figure it out tomorrow morning

**Comment by md-5** [comment]
Thanks!

**Comment by lax1dude** [comment]
I'm on my phone but I was able to read the JVM error dump, I noticed the address that caused the segmentation fault (si_addr) is also the current value of the CPU's instruction pointer (`RIP=0x00000000000021d0`) so something about that mbedtls free function causes it to jump to a bad address, and attempting to load that address to execute it is causing the segmentation fault. I'm gonna install alpine tomorrow and try to reproduce it.

**Comment by lax1dude** [comment]
I'm 99% sure the source of this crash is a problem with how mbedtls was compiled. The `mbedtls_platform_zeroize` function that it appears to be crashing in uses a function pointer in order to call the libc memset function. If this global variable isn't correctly initialized to the address of the libc memset function, and just contains garbage data, that would explain how the CPU's instruction pointer is ending up at a random unmapped address whenever `mbedtls_platform_zeroize` is called. The compiler could also be optimizing this in some weird way that breaks when you use musl instead of glibc.

[tf-psa-crypto/drivers/builtin/src/platform_util.c#L91](https://github.com/Mbed-TLS/mbedtls/blob/development/tf-psa-crypto/drivers/builtin/src/platform_util.c#L91)

**Comment by lax1dude** [comment]
It doesn't look like the crash happens if I compile native-cipher.so on alpine linux

**Comment by md-5** [comment]
I think the key question is whether this happens prior to your commit changing natives

**Comment by Rigner** [comment]
Tested the fix from the PR, works fine on the setup where I had the crash 😃
