### ISSUE TITLE
A task raised an exception. Task: net.md_5.bungee.connection.InitialHandler$6$1@1ba5363a

### ISSUE THREAD

**Issue by SchlumpfkopfYT** [SpigotMC/BungeeCord#3723]
### Bungeecord version

Bungeecord-Bootstrap:1,21_RO.1

### Server version

Spigot 1.19.2

### Client version

1.16.5

### Bungeecord plugins

/

### The bug

00:37:35 [WARNUNG] A task raised an exception. Task: net.md_5.bungee.connection.InitialHandler$6$1@1ba5363a
java.lang.IllegalStateException: Cancelled ServerConnectEvent with no server or disconnect.
    at net.md_5.bungee.UserConnection.connect(UserConnection.java:320)
    at net.md_5.bungee.UserConnection.connect(UserConnection.java:301)
    at net.md_5.bungee.connection.InitialHandler$7.done(InitialHandler.java:689)
    at net.md_5.bungee.connection.InitialHandler$7.done(InitialHandler.java:679)
    at net.md_5.bungee.api.event.AsyncEvent.postCall(AsyncEvent.java:40)
    at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:414)
    at net.md_5.bungee.connection.InitialHandler.finish2(InitialHandler.java:694)
    at net.md_5.bungee.connection.InitialHandler.access$1300(InitialHandler.java:81)
    at net.md_5.bungee.connection.InitialHandler$6$1.run(InitialHandler.java:644)
    at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:405)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at java.base/java.lang.Thread.run(Thread.java:840)

### Log output (links)

00:37:35 [WARNUNG] A task raised an exception. Task: net.md_5.bungee.connection.InitialHandler$6$1@1ba5363a
java.lang.IllegalStateException: Cancelled ServerConnectEvent with no server or disconnect.
    at net.md_5.bungee.UserConnection.connect(UserConnection.java:320)
    at net.md_5.bungee.UserConnection.connect(UserConnection.java:301)
    at net.md_5.bungee.connection.InitialHandler$7.done(InitialHandler.java:689)
    at net.md_5.bungee.connection.InitialHandler$7.done(InitialHandler.java:679)
    at net.md_5.bungee.api.event.AsyncEvent.postCall(AsyncEvent.java:40)
    at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:414)
    at net.md_5.bungee.connection.InitialHandler.finish2(InitialHandler.java:694)
    at net.md_5.bungee.connection.InitialHandler.access$1300(InitialHandler.java:81)
    at net.md_5.bungee.connection.InitialHandler$6$1.run(InitialHandler.java:644)
    at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:405)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at java.base/java.lang.Thread.run(Thread.java:840)

### Checking

- [X] I am using BungeeCord and **not a fork**. Issues with forks should not be reported here.
- [X] I think this is **not** an issue with a bungeecord plugin.
- [X] I have not read these checkboxes and therefore I just ticked them all.
- [X] This is not a question or plugin creation help request.

**Comment by SchlumpfkopfYT** [comment]
Do not use   <dependency>
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
            <version>2.8.8</version>
        </dependency>

**Comment by Janmm14** [comment]
This is usually a plugin mistake.
