### ISSUE TITLE
Cannot get ID for packet class net.md_5.bungee.protocol.packet.PlayerListItemRemove

### ISSUE THREAD

**Issue by hotspuraz** [SpigotMC/BungeeCord#3756]
### Bungeecord version

BungeeCord-1877 (Jenkins)

### Server version

1.21.1

### Client version

1.21.1

### Bungeecord plugins

```
ajQueuePlus-2.7.0
DomainStats-Bungee
floodgate-bungee-112
LuckPerms-Bungee-5.4.141
Nameless-Plugin-BungeeCord-3.4.0
nuvotifier
Pl-Hide-Pro-2.6.3
protocolize-bungeecord-2.3.1
RedirectPlus-2.12.0
ServerListMotd
spark-1.10.110-bungeecord
tebex-bungeecord-2.1.0
UltraStaffChat-5.2.2
```

### The bug

Players get kicked, seemingly at random, with the attached error message. I've removed every bungeecord plugin and run the proxy on nothing, with the kick errors when players connect, or switch worlds, still occurring. I'm at a complete loss now, and no other devs, system admins, or server owners seem to know the cause either.
![image](https://github.com/user-attachments/assets/a0f7983d-f47a-40c8-90fd-2af260d3f1da)

### Log output (links)

```16:41:07 [SEVERE] [InLaLaLand13] -> UpstreamBridge - encountered exception
io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Cannot get ID for packet class net.md_5.bungee.protocol.packet.PlayerListItemRemove in phase CONFIGURATION with direction TO_CLIENT
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:893)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:875)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:984)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:868)
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:893)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:956)
	at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1263)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:405)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.IllegalArgumentException: Cannot get ID for packet class net.md_5.bungee.protocol.packet.PlayerListItemRemove in phase CONFIGURATION with direction TO_CLIENT
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:463)
	at net.md_5.bungee.protocol.Protocol$DirectionData.getId(Protocol.java:992)
	at net.md_5.bungee.protocol.MinecraftEncoder.encode(MinecraftEncoder.java:26)
	at net.md_5.bungee.protocol.MinecraftEncoder.encode(MinecraftEncoder.java:10)
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
	... 15 more```

### Checking

- [X] I am using BungeeCord and **not a fork**. Issues with forks should not be reported here.
- [X] I think this is **not** an issue with a bungeecord plugin.
- [ ] I have not read these checkboxes and therefore I just ticked them all.
- [X] This is not a question or plugin creation help request.

**Comment by Outfluencer** [comment]
What plugins dou you have installed on your backend server, and what version does it use?

**Comment by hotspuraz** [comment]
Is this an error that can be triggered by a plugin on a spigot server?

**Comment by Outfluencer** [comment]
I am not sure thats why i am asking

**Comment by hotspuraz** [comment]
```
advancedregionmarket-3.5.4-SNAPSHOT.jar
AntiPopup-9.2.jar
AtherialLibPlugin.jar
Banfromclaim-1.7.4.jar
BlockRegen-3.10.8.jar
ChestShop-423.jar
Chunky-1.4.10.jar
ChunkyBorder-1.2.13.jar
CMI-9.7.6.10.jar
CMIEInjector1.0.2.4.jar
CMILib1.5.1.6.jar
CoreProtect-22.4.jar
CsCMD-1.0-SNAPSHOT.jar
DecentHolograms-2.8.11.jar
DenyTravel.jar
Duels-3.5.4.jar
EnchantGui 3.9.1.jar
EnchantsSquared_2.5.13.jar
floodgate-spigot-110.jar
GriefPrevention-16.18.4.jar
GSit-1.10.0.jar
HeadDatabase-4.20.4.jar
images-2.5.1.jar
imevo-adjustments-1.0.jar
ImevoAntiGlow-1.1.jar
ImevoAnvil-1.1.jar
ImEvoEvents.jar
ImevoHiddenArmor-1.1.jar
ImevoLevels-1.1.jar
ImevoMap-1.1.jar
ImevoQuest-1.1.jar
ImevoSearchShop-v1.0.3.jar
Insights-6.19.2.jar
ItemsAdder_4.0.2-beta-release-12.jar
JakesRTP-v0.14.9.jar
LastLoginAPI-1.7.4.jar
LiteAnnouncer-1.3.1.3.jar
LiteBans-2.16.1.jar
LoneLibs_1.0.58.jar
LuckPerms-Bukkit-5.4.131.jar
MarriageMaster-2.7.6.jar
2.38 MiB
Sep 14th, 2024 10:49AM
MineableSpawners-1.2.jar
MobFarmManager3.0.2.2.jar
Multiverse-Core-4.3.1.jar
Notes-1.1.jar
nuvotifier-2.7.3.jar
2.73 MiB
Sep 14th, 2024 10:49AM
OtherAnimalTeleport2.3-b86.jar
packetevents-spigot-2.5.0.jar
Parties-3.2.15.jar
PhoenixCrates-3.7-dev-53.jar
Pl-Hide-Pro-2.11.1.jar
PlaceholderAPI-2.11.6.jar
PlayerParticles-8.7.jar
PlayerWarps 7.6.1.jar
PremiumVanish-2.9.14.jar
ProtocolLib-726.jar
PvPManager-3.18.26.jar
Rankup-3.14.4.jar
ShopGUIPlus-1.98.1.jar
SilenceMobs-1.10_1.0.8.jar
SmartInvs-1.2.7.jar
spark-1.10.71-bukkit.jar
Suffix.jar
TAB v4.1.9.jar
tebex-bukkit-2.0.6.jar
TreeFeller-1.24.1.jar
UltimateAutoRestart 2024.07.jar
UpgradeableHoppers-4.17.8.jar
Vault-1.7.4.jar
ViaBackwards-5.0.3.jar
ViaVersion-5.0.5.jar
VoidGen-2.2.1.jar
VotingPlugin-6.17.2.jar
Vulcan-2.9.1.jar
Welcome-1.0.jar
worldedit-bukkit-7.3.6.jar
worldguard-bukkit-7.0.11-dist.jar
zAuctionHouse-3.2.2.5.jar
ZNPCsPlus-2.0.0-SNAPSHOT.jar
```

**Comment by Outfluencer** [comment]
whats the version of the backend server? is it really 1.21 or is it something like 1.20.4 and you are joining with 1.21 with viaversion?

**Comment by hotspuraz** [comment]
It is 1.21.1 - latest puffermc version

**Comment by Outfluencer** [comment]
Does it happen if no plugins are installed on the backend? if not you could try to find out what plugin is causing the issue

**Comment by hotspuraz** [comment]
Issue is that it's not a frequent kick, so testing it takes hundreds of relogs

**Comment by Outfluencer** [comment]
I understand you could try to debug it by setting the server to offline mode and bot it

**Comment by hotspuraz** [comment]
Well i'd have to create an entire duplicate network for that lol

**Comment by Outfluencer** [comment]
if you dont want to do it on the same server, yes

**Comment by Outfluencer** [comment]
but you only need one or two copies of the backend and one bungee

**Comment by hotspuraz** [comment]
well with 100+ players online, doing it on the live server is asking for trouble xD

**Comment by Outfluencer** [comment]
just create a bungee and two backend with all the plugins on the main server

**Comment by hotspuraz** [comment]
Difficulty with that is where, all my dedi's are heavily protected against anything not connecting via the proxy port. Might be easiest to use a web host

**Comment by hotspuraz** [comment]
Oh of course, why didn't I think of that

**Comment by Outfluencer** [comment]
looking at the bungeecord code i think i found the issue

**Comment by Outfluencer** [comment]
i think i can fix it for you

**Comment by hotspuraz** [comment]
Well after several weeks of trying to diagnose this issue, I would appreciate it a lot if you could lol

**Comment by Outfluencer** [comment]
I am very sure that its fixed with this change.

**Comment by Outfluencer** [comment]
The problem was that bungeecord sends a TabListRemove Packet to all players if a player disconnects,
That packet is PLAY state only, but we dont queue or check for the encoding state of the player we send the packet to.

I changed it to queue the packet if not in the PLAY state

**Comment by hotspuraz** [comment]
I see, so no need to continue building a full proxy local host to bot and test this on? lol

**Comment by Outfluencer** [comment]
Yes no need for this

**Comment by Outfluencer** [comment]
> Legend, I'll get bungee updated asap and hopefully this issue will be resolved and I won't get 20+ reports a day asking why md_5 is kicking everyone lol

md_5 needs to merge first

**Comment by hotspuraz** [comment]
All good, thank you for your help
