### ISSUE TITLE
ERROR: Unexpected disconnect during server login, did you forget to enable BungeeCord / IP forwarding on your server?

### ISSUE THREAD

**Issue by apifinyyy** [SpigotMC/BungeeCord#3768]
### Bungeecord version

BungeeCord-Bootstrap:1.21-R0.1-SNAPSHOT:15bd33b:1890

### Server version

MC: 1.21.4

### Client version

1.21.4

### Bungeecord plugins

none

### The bug

I attempt to join the proxy via a custom domain. I load. I am then greeted with an error: "Unexpected disconnect during server login, did you forget to enable BungeeCord / IP forwarding on your server?"

I am trying to run a double proxy setup with velocity too.

I have removed any known invasive plugins from the main server. (geyser as well as floodgate just in case)

FULL PLUGIN LIST:
Spigot Plugins: BetterTeams, Chunky, Citizens, DiscordSRV, Essentials, ExcellentCrates, FreedChat, InvSeePlusPlus, LifeStealZ, LuckPerms, Maintenance, nightcore, ProtocolLib, Spawn, TAB, Vanish, Vault, ViaBackwards, ViaVersion, Votifier, VotingPlugin, Vulcan, WorldEdit, WorldGuard ( All plugins have been updated to their respective latest builds )
Paper Plugins: FancyHolograms ( All plugins have been updated to their respective latest builds )

I have followed the regular readily available, as well as official guides to the best of my knowledge.

File downloads:
[soulstealbungeeproxy.zip](https://github.com/user-attachments/files/18140490/soulstealbungeeproxy.zip)
[soulstealmain.zip](https://github.com/user-attachments/files/18140491/soulstealmain.zip)
[soulstealvelocityproxy.zip](https://github.com/user-attachments/files/18140492/soulstealvelocityproxy.zip)
![customdomainsetup](https://github.com/user-attachments/assets/863662e7-73c9-4a96-a387-ad6e4bcbf269)

### Log output (links)

12:45:02 [INFO] [apifinysalt,/206.83.99.35:39707] <-> InitialHandler has connected
12:45:03 [INFO] [apifinysalt] <-> ServerConnector [lifesteal] has connected
12:45:03 [INFO] [apifinysalt] disconnected with: Unexpected disconnect during server login, did you forget to enable BungeeCord / IP forwarding on your server?
12:45:03 [INFO] [apifinysalt] <-> ServerConnector [lifesteal] has disconnected
12:45:03 [INFO] [apifinysalt] -> UpstreamBridge has disconnected

### Checking

- [X] I am using BungeeCord and **not a fork**. Issues with forks should not be reported here.
- [X] I think this is **not** an issue with a bungeecord plugin.
- [ ] I have not read these checkboxes and therefore I just ticked them all.
- [X] This is not a question or plugin creation help request.

**Comment by apifinyyy** [comment]
Enabled and new errors!

[23:32:09 WARN]: io.netty.handler.timeout.ReadTimeoutException
[23:33:09 WARN]: io.netty.handler.timeout.ReadTimeoutException
[23:33:21 WARN]: io.netty.handler.codec.haproxy.HAProxyProtocolException: header length (over 1452) exceeds the allowed maximum (108)
[23:33:21 WARN]:        at io.netty.handler.codec.haproxy.HAProxyMessageDecoder.fail(HAProxyMessageDecoder.java:311)
[23:33:21 WARN]:        at io.netty.handler.codec.haproxy.HAProxyMessageDecoder.failOverLimit(HAProxyMessageDecoder.java:301)
[23:33:21 WARN]:        at io.netty.handler.codec.haproxy.HAProxyMessageDecoder.access$400(HAProxyMessageDecoder.java:33)
[23:33:21 WARN]:        at io.netty.handler.codec.haproxy.HAProxyMessageDecoder$HeaderExtractor.extract(HAProxyMessageDecoder.java:389)
[23:33:21 WARN]:        at io.netty.handler.codec.haproxy.HAProxyMessageDecoder.decodeLine(HAProxyMessageDecoder.java:292)
[23:33:21 WARN]:        at io.netty.handler.codec.haproxy.HAProxyMessageDecoder.decode(HAProxyMessageDecoder.java:246)
[23:33:21 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:530)
[23:33:21 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:469)
[23:33:21 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
[23:33:21 WARN]:        at io.netty.handler.codec.haproxy.HAProxyMessageDecoder.channelRead(HAProxyMessageDecoder.java:228)
[23:33:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[23:33:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[23:33:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[23:33:21 WARN]:        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:289)
[23:33:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[23:33:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[23:33:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[23:33:21 WARN]:        at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
[23:33:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[23:33:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[23:33:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[23:33:21 WARN]:        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1357)
[23:33:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
[23:33:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[23:33:21 WARN]:        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:868)
[23:33:21 WARN]:        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:799)
[23:33:21 WARN]:        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:501)
[23:33:21 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:399)
[23:33:21 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[23:33:21 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[23:33:21 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by apifinyyy** [comment]
Please note that i couldnt see a debug option on the proxy, this is the main servers debug in its console when i try to join

**Comment by Outfluencer** [comment]
Looks like you habe a HA proxy plugin on your backend or maybe you have enabled it in paper idk

**Comment by Outfluencer** [comment]
You cant join because the server tries to read a ha proxy message

BungeeCord is not a HAProxy

**Comment by apifinyyy** [comment]
i have it enabled on my velocity proxy but nothing else? i have it enabled for minehut

**Comment by apifinyyy** [comment]
if its still an issue like that then ill disable it

**Comment by Outfluencer** [comment]
I dont understand your multi proxy system

But what you try to do is not supported.
Bungee supports incomming haproxy connection but does not pretend to be one itself
So you need to disable it

**Comment by apifinyyy** [comment]
aight. thanks. your the professional so ima just listen lmao. thanks for help

**Comment by apifinyyy** [comment]
okay after deleting both proxys and re making the bungeecord i still get the same error...

**Comment by apifinyyy** [comment]
would proxy protocal be the thing causing it? i have that enabled on the main server. idk i just cant find any hapoxy setting on the main server

**Comment by apifinyyy** [comment]
OMG IT WAS IT I disabled proxy protocal and that was the hapoxy.

**Comment by apifinyyy** [comment]
For anyone having this issue go into config on your main servers and ensure proxy-protocal under bungeecord is disabled
