### ISSUE TITLE
Could not bind port

### ISSUE THREAD

**Issue by Zere** [SpigotMC/BungeeCord#428]
I keep getting this error when starting up BungeeCord:

12:59:19 [WARNING] Could not bind to host spleef.net/76.103.159.69:25565
java.net.BindException: Can't assign requested address
    at sun.nio.ch.Net.bind0(Native Method)
    at sun.nio.ch.Net.bind(Net.java:344)
    at sun.nio.ch.Net.bind(Net.java:336)
    at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:199)
    at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
    at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:98)
    at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:646)
    at io.netty.channel.DefaultChannelPipeline$HeadHandler.bind(DefaultChannelPipeline.java:1296)
    at io.netty.channel.DefaultChannelHandlerContext.invokeBind0(DefaultChannelHandlerContext.java:1026)
    at io.netty.channel.DefaultChannelHandlerContext.invokeBind(DefaultChannelHandlerContext.java:1012)
    at io.netty.channel.DefaultChannelHandlerContext.bind(DefaultChannelHandlerContext.java:1006)
    at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:1072)
    at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:250)
    at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:332)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:328)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:331)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:109)
    at java.lang.Thread.run(Thread.java:722)
end
12:59:22 [INFO] Closing pending connections
12:59:22 [INFO] Disconnecting 0 connections
12:59:22 [INFO] Closing IO threads
12:59:25 [INFO] Saving reconnect locations
12:59:25 [INFO] Disabling plugins
12:59:25 [INFO] Thankyou and goodbye

What am I doing wrong? Thanks so much

**Comment by TheBlueKingLP** [comment]
i have this problem too,but i use 0.0.0.0 and use localhost can login,but use public ip can't

**Comment by minecrafter** [comment]
@TheBlueKingLP you have bumped an issue from two years ago. Use the Spigot forums.
