### ISSUE TITLE
Build #537 - IllegalStateException.

### ISSUE THREAD

**Issue by Asphodan** [SpigotMC/BungeeCord#446]
10:42:55 [INFO] [aliiztheman] disconnected with: [Kicked] Flying is not enabled on this server
10:42:55 [INFO] [aliiztheman] <-> DownstreamBridge <-> [grid] has disconnected
10:42:55 [INFO] [aliiztheman] -> UpstreamBridge has disconnected
10:42:55 [SEVERE] Jun 18, 2013 10:42:55 AM io.netty.util.concurrent.SingleThreadEventExecutor runAllTasks
WARNING: A task raised an exception.
java.lang.IllegalStateException: complete already
    at io.netty.util.concurrent.DefaultPromise.setFailure(DefaultPromise.java:400)
    at io.netty.util.concurrent.PromiseTask.setFailureInternal(PromiseTask.java:61)
    at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:145)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:353)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:365)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: complete already
    at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:382)
    at io.netty.util.concurrent.PromiseTask.setSuccessInternal(PromiseTask.java:80)
    at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:125)
    ... 4 more

10:44:46 [WARNING] [dsboy66] -> UpstreamBridge - IOException: Connection reset by peer
10:44:46 [INFO] [dsboy66] disconnected with: IOException : Connection reset by peer @ sun.nio.ch.FileDispatcherImpl:-2
10:44:46 [INFO] [dsboy66] -> UpstreamBridge has disconnected
10:44:46 [INFO] [dsboy66] <-> DownstreamBridge <-> [grid] has disconnected

**Comment by inteladyne** [comment]
After adding a few changes to the **FQDN** this error seems to have disappeared. Just add **sent** name and hosts and **FQDN** works perfectly to _fix the error message_.

**Comment by Janmm14** [comment]
@inteladyne
This issue is two years old.
@md-5 please close
